// AUTO-GENERATED by scripts/generate.ts — DO NOT EDIT
import { z } from "zod";
import { githubRequest } from "../client.js";

export const activityTools = [
  {
    name: "github_activity_list_public_events",
    description: "List public events",
    inputSchema: z.object({
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/events`, undefined, { per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_activity_get_feeds",
    description: "Get feeds",
    inputSchema: z.object({}),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/feeds`, undefined, undefined);
    },
  },
  {
    name: "github_activity_list_public_events_for_repo_network",
    description: "List public events for a network of repositories",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/networks/${args.owner}/${args.repo}/events`, undefined, { per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_activity_list_notifications_for_authenticated_user",
    description: "List notifications for the authenticated user",
    inputSchema: z.object({
      all: z.boolean().optional().describe("If `true`, show notifications marked as read."),
      participating: z.boolean().optional().describe("If `true`, only shows notifications in which the user is directly participating or mentioned."),
      since: z.string().optional().describe("Only show results that were last updated after the given time. This is a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ`."),
      before: z.string().optional().describe("Only show notifications updated before the given time. This is a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ`."),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      per_page: z.number().optional().describe("The number of results per page (max 50). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/notifications`, undefined, { all: args.all, participating: args.participating, since: args.since, before: args.before, page: args.page, per_page: args.per_page });
    },
  },
  {
    name: "github_activity_mark_notifications_as_read",
    description: "Mark notifications as read",
    inputSchema: z.object({
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("PUT", `/notifications`, args.body, undefined);
    },
  },
  {
    name: "github_activity_get_thread",
    description: "Get a thread",
    inputSchema: z.object({
      thread_id: z.string().describe("thread_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/notifications/threads/${args.thread_id}`, undefined, undefined);
    },
  },
  {
    name: "github_activity_mark_thread_as_read",
    description: "Mark a thread as read",
    inputSchema: z.object({
      thread_id: z.string().describe("thread_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("PATCH", `/notifications/threads/${args.thread_id}`, undefined, undefined);
    },
  },
  {
    name: "github_activity_mark_thread_as_done",
    description: "Mark a thread as done",
    inputSchema: z.object({
      thread_id: z.string().describe("thread_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("DELETE", `/notifications/threads/${args.thread_id}`, undefined, undefined);
    },
  },
  {
    name: "github_activity_get_thread_subscription_for_authenticated_user",
    description: "Get a thread subscription for the authenticated user",
    inputSchema: z.object({
      thread_id: z.string().describe("thread_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/notifications/threads/${args.thread_id}/subscription`, undefined, undefined);
    },
  },
  {
    name: "github_activity_set_thread_subscription",
    description: "Set a thread subscription",
    inputSchema: z.object({
      thread_id: z.string().describe("thread_id"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("PUT", `/notifications/threads/${args.thread_id}/subscription`, args.body, undefined);
    },
  },
  {
    name: "github_activity_delete_thread_subscription",
    description: "Delete a thread subscription",
    inputSchema: z.object({
      thread_id: z.string().describe("thread_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("DELETE", `/notifications/threads/${args.thread_id}/subscription`, undefined, undefined);
    },
  },
  {
    name: "github_activity_list_public_org_events",
    description: "List public organization events",
    inputSchema: z.object({
      org: z.string().describe("org"),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/events`, undefined, { per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_activity_list_repo_events",
    description: "List repository events",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/events`, undefined, { per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_activity_list_repo_notifications_for_authenticated_user",
    description: "List repository notifications for the authenticated user",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      all: z.boolean().optional().describe("If `true`, show notifications marked as read."),
      participating: z.boolean().optional().describe("If `true`, only shows notifications in which the user is directly participating or mentioned."),
      since: z.string().optional().describe("Only show results that were last updated after the given time. This is a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ`."),
      before: z.string().optional().describe("Only show notifications updated before the given time. This is a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ`."),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/notifications`, undefined, { all: args.all, participating: args.participating, since: args.since, before: args.before, per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_activity_mark_repo_notifications_as_read",
    description: "Mark repository notifications as read",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("PUT", `/repos/${args.owner}/${args.repo}/notifications`, args.body, undefined);
    },
  },
  {
    name: "github_activity_list_stargazers_for_repo",
    description: "List stargazers",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/stargazers`, undefined, { per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_activity_list_watchers_for_repo",
    description: "List watchers",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/subscribers`, undefined, { per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_activity_get_repo_subscription",
    description: "Get a repository subscription",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/subscription`, undefined, undefined);
    },
  },
  {
    name: "github_activity_set_repo_subscription",
    description: "Set a repository subscription",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("PUT", `/repos/${args.owner}/${args.repo}/subscription`, args.body, undefined);
    },
  },
  {
    name: "github_activity_delete_repo_subscription",
    description: "Delete a repository subscription",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("DELETE", `/repos/${args.owner}/${args.repo}/subscription`, undefined, undefined);
    },
  },
  {
    name: "github_activity_list_repos_starred_by_authenticated_user",
    description: "List repositories starred by the authenticated user",
    inputSchema: z.object({
      sort: z.enum(["created", "updated"]).optional().describe("The property to sort the results by. `created` means when the repository was starred. `updated` means when the repository was last pushed to."),
      direction: z.enum(["asc", "desc"]).optional().describe("The direction to sort the results by."),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/user/starred`, undefined, { sort: args.sort, direction: args.direction, per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_activity_check_repo_is_starred_by_authenticated_user",
    description: "Check if a repository is starred by the authenticated user",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/user/starred/${args.owner}/${args.repo}`, undefined, undefined);
    },
  },
  {
    name: "github_activity_star_repo_for_authenticated_user",
    description: "Star a repository for the authenticated user",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("PUT", `/user/starred/${args.owner}/${args.repo}`, undefined, undefined);
    },
  },
  {
    name: "github_activity_unstar_repo_for_authenticated_user",
    description: "Unstar a repository for the authenticated user",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("DELETE", `/user/starred/${args.owner}/${args.repo}`, undefined, undefined);
    },
  },
  {
    name: "github_activity_list_watched_repos_for_authenticated_user",
    description: "List repositories watched by the authenticated user",
    inputSchema: z.object({
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/user/subscriptions`, undefined, { per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_activity_list_events_for_authenticated_user",
    description: "List events for the authenticated user",
    inputSchema: z.object({
      username: z.string().describe("username"),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/users/${args.username}/events`, undefined, { per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_activity_list_org_events_for_authenticated_user",
    description: "List organization events for the authenticated user",
    inputSchema: z.object({
      username: z.string().describe("username"),
      org: z.string().describe("org"),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/users/${args.username}/events/orgs/${args.org}`, undefined, { per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_activity_list_public_events_for_user",
    description: "List public events for a user",
    inputSchema: z.object({
      username: z.string().describe("username"),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/users/${args.username}/events/public`, undefined, { per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_activity_list_received_events_for_user",
    description: "List events received by the authenticated user",
    inputSchema: z.object({
      username: z.string().describe("username"),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/users/${args.username}/received_events`, undefined, { per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_activity_list_received_public_events_for_user",
    description: "List public events received by a user",
    inputSchema: z.object({
      username: z.string().describe("username"),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/users/${args.username}/received_events/public`, undefined, { per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_activity_list_repos_starred_by_user",
    description: "List repositories starred by a user",
    inputSchema: z.object({
      username: z.string().describe("username"),
      sort: z.enum(["created", "updated"]).optional().describe("The property to sort the results by. `created` means when the repository was starred. `updated` means when the repository was last pushed to."),
      direction: z.enum(["asc", "desc"]).optional().describe("The direction to sort the results by."),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/users/${args.username}/starred`, undefined, { sort: args.sort, direction: args.direction, per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_activity_list_repos_watched_by_user",
    description: "List repositories watched by a user",
    inputSchema: z.object({
      username: z.string().describe("username"),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/users/${args.username}/subscriptions`, undefined, { per_page: args.per_page, page: args.page });
    },
  },
];
