// AUTO-GENERATED by scripts/generate.ts — DO NOT EDIT
import { z } from "zod";
import { githubRequest } from "../client.js";

export const appsTools = [
  {
    name: "github_apps_get_authenticated",
    description: "Get the authenticated app",
    inputSchema: z.object({}),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/app`, undefined, undefined);
    },
  },
  {
    name: "github_apps_create_from_manifest",
    description: "Create a GitHub App from a manifest",
    inputSchema: z.object({
      code: z.string().describe("code")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/app-manifests/${args.code}/conversions`, undefined, undefined);
    },
  },
  {
    name: "github_apps_get_webhook_config_for_app",
    description: "Get a webhook configuration for an app",
    inputSchema: z.object({}),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/app/hook/config`, undefined, undefined);
    },
  },
  {
    name: "github_apps_update_webhook_config_for_app",
    description: "Update a webhook configuration for an app",
    inputSchema: z.object({
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("PATCH", `/app/hook/config`, args.body, undefined);
    },
  },
  {
    name: "github_apps_list_webhook_deliveries",
    description: "List deliveries for an app webhook",
    inputSchema: z.object({
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      cursor: z.string().optional().describe("Used for pagination: the starting delivery from which the page of deliveries is fetched. Refer to the `link` header for the next and previous page cursors."),
      status: z.enum(["success", "failure"]).optional().describe("Returns webhook deliveries filtered by delivery outcome classification based on `status_code` range. A `status` of `success` returns deliveries with a `status_code` in the 200-399 range (inclusive). A `status` of `failure` returns deliveries with a `status_code` in the 400-599 range (inclusive).")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/app/hook/deliveries`, undefined, { per_page: args.per_page, cursor: args.cursor, status: args.status });
    },
  },
  {
    name: "github_apps_get_webhook_delivery",
    description: "Get a delivery for an app webhook",
    inputSchema: z.object({
      delivery_id: z.string().describe("delivery_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/app/hook/deliveries/${args.delivery_id}`, undefined, undefined);
    },
  },
  {
    name: "github_apps_redeliver_webhook_delivery",
    description: "Redeliver a delivery for an app webhook",
    inputSchema: z.object({
      delivery_id: z.string().describe("delivery_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/app/hook/deliveries/${args.delivery_id}/attempts`, undefined, undefined);
    },
  },
  {
    name: "github_apps_list_installation_requests_for_authenticated_app",
    description: "List installation requests for the authenticated app",
    inputSchema: z.object({
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/app/installation-requests`, undefined, { per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_apps_list_installations",
    description: "List installations for the authenticated app",
    inputSchema: z.object({
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      since: z.string().optional().describe("Only show results that were last updated after the given time. This is a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ`."),
      outdated: z.string().optional().describe("outdated")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/app/installations`, undefined, { per_page: args.per_page, page: args.page, since: args.since, outdated: args.outdated });
    },
  },
  {
    name: "github_apps_get_installation",
    description: "Get an installation for the authenticated app",
    inputSchema: z.object({
      installation_id: z.string().describe("installation_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/app/installations/${args.installation_id}`, undefined, undefined);
    },
  },
  {
    name: "github_apps_delete_installation",
    description: "Delete an installation for the authenticated app",
    inputSchema: z.object({
      installation_id: z.string().describe("installation_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("DELETE", `/app/installations/${args.installation_id}`, undefined, undefined);
    },
  },
  {
    name: "github_apps_create_installation_access_token",
    description: "Create an installation access token for an app",
    inputSchema: z.object({
      installation_id: z.string().describe("installation_id"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/app/installations/${args.installation_id}/access_tokens`, args.body, undefined);
    },
  },
  {
    name: "github_apps_suspend_installation",
    description: "Suspend an app installation",
    inputSchema: z.object({
      installation_id: z.string().describe("installation_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("PUT", `/app/installations/${args.installation_id}/suspended`, undefined, undefined);
    },
  },
  {
    name: "github_apps_unsuspend_installation",
    description: "Unsuspend an app installation",
    inputSchema: z.object({
      installation_id: z.string().describe("installation_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("DELETE", `/app/installations/${args.installation_id}/suspended`, undefined, undefined);
    },
  },
  {
    name: "github_apps_delete_authorization",
    description: "Delete an app authorization",
    inputSchema: z.object({
      client_id: z.string().describe("client_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("DELETE", `/applications/${args.client_id}/grant`, undefined, undefined);
    },
  },
  {
    name: "github_apps_check_token",
    description: "Check a token",
    inputSchema: z.object({
      client_id: z.string().describe("client_id"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/applications/${args.client_id}/token`, args.body, undefined);
    },
  },
  {
    name: "github_apps_reset_token",
    description: "Reset a token",
    inputSchema: z.object({
      client_id: z.string().describe("client_id"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("PATCH", `/applications/${args.client_id}/token`, args.body, undefined);
    },
  },
  {
    name: "github_apps_delete_token",
    description: "Delete an app token",
    inputSchema: z.object({
      client_id: z.string().describe("client_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("DELETE", `/applications/${args.client_id}/token`, undefined, undefined);
    },
  },
  {
    name: "github_apps_scope_token",
    description: "Create a scoped access token",
    inputSchema: z.object({
      client_id: z.string().describe("client_id"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/applications/${args.client_id}/token/scoped`, args.body, undefined);
    },
  },
  {
    name: "github_apps_get_by_slug",
    description: "Get an app",
    inputSchema: z.object({
      app_slug: z.string().describe("app_slug")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/apps/${args.app_slug}`, undefined, undefined);
    },
  },
  {
    name: "github_apps_list_repos_accessible_to_installation",
    description: "List repositories accessible to the app installation",
    inputSchema: z.object({
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/installation/repositories`, undefined, { per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_apps_revoke_installation_access_token",
    description: "Revoke an installation access token",
    inputSchema: z.object({}),
    handler: async (args: Record<string, any>) => {
      return githubRequest("DELETE", `/installation/token`, undefined, undefined);
    },
  },
  {
    name: "github_apps_get_subscription_plan_for_account",
    description: "Get a subscription plan for an account",
    inputSchema: z.object({
      account_id: z.string().describe("account_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/marketplace_listing/accounts/${args.account_id}`, undefined, undefined);
    },
  },
  {
    name: "github_apps_list_plans",
    description: "List plans",
    inputSchema: z.object({
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/marketplace_listing/plans`, undefined, { per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_apps_list_accounts_for_plan",
    description: "List accounts for a plan",
    inputSchema: z.object({
      plan_id: z.string().describe("plan_id"),
      sort: z.enum(["created", "updated"]).optional().describe("The property to sort the results by."),
      direction: z.enum(["asc", "desc"]).optional().describe("To return the oldest accounts first, set to `asc`. Ignored without the `sort` parameter."),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/marketplace_listing/plans/${args.plan_id}/accounts`, undefined, { sort: args.sort, direction: args.direction, per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_apps_get_subscription_plan_for_account_stubbed",
    description: "Get a subscription plan for an account (stubbed)",
    inputSchema: z.object({
      account_id: z.string().describe("account_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/marketplace_listing/stubbed/accounts/${args.account_id}`, undefined, undefined);
    },
  },
  {
    name: "github_apps_list_plans_stubbed",
    description: "List plans (stubbed)",
    inputSchema: z.object({
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/marketplace_listing/stubbed/plans`, undefined, { per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_apps_list_accounts_for_plan_stubbed",
    description: "List accounts for a plan (stubbed)",
    inputSchema: z.object({
      plan_id: z.string().describe("plan_id"),
      sort: z.enum(["created", "updated"]).optional().describe("The property to sort the results by."),
      direction: z.enum(["asc", "desc"]).optional().describe("To return the oldest accounts first, set to `asc`. Ignored without the `sort` parameter."),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/marketplace_listing/stubbed/plans/${args.plan_id}/accounts`, undefined, { sort: args.sort, direction: args.direction, per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_apps_get_org_installation",
    description: "Get an organization installation for the authenticated app",
    inputSchema: z.object({
      org: z.string().describe("org")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/installation`, undefined, undefined);
    },
  },
  {
    name: "github_apps_get_repo_installation",
    description: "Get a repository installation for the authenticated app",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/installation`, undefined, undefined);
    },
  },
  {
    name: "github_apps_list_installations_for_authenticated_user",
    description: "List app installations accessible to the user access token",
    inputSchema: z.object({
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/user/installations`, undefined, { per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_apps_list_installation_repos_for_authenticated_user",
    description: "List repositories accessible to the user access token",
    inputSchema: z.object({
      installation_id: z.string().describe("installation_id"),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/user/installations/${args.installation_id}/repositories`, undefined, { per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_apps_add_repo_to_installation_for_authenticated_user",
    description: "Add a repository to an app installation",
    inputSchema: z.object({
      installation_id: z.string().describe("installation_id"),
      repository_id: z.string().describe("repository_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("PUT", `/user/installations/${args.installation_id}/repositories/${args.repository_id}`, undefined, undefined);
    },
  },
  {
    name: "github_apps_remove_repo_from_installation_for_authenticated_user",
    description: "Remove a repository from an app installation",
    inputSchema: z.object({
      installation_id: z.string().describe("installation_id"),
      repository_id: z.string().describe("repository_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("DELETE", `/user/installations/${args.installation_id}/repositories/${args.repository_id}`, undefined, undefined);
    },
  },
  {
    name: "github_apps_list_subscriptions_for_authenticated_user",
    description: "List subscriptions for the authenticated user",
    inputSchema: z.object({
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/user/marketplace_purchases`, undefined, { per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_apps_list_subscriptions_for_authenticated_user_stubbed",
    description: "List subscriptions for the authenticated user (stubbed)",
    inputSchema: z.object({
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/user/marketplace_purchases/stubbed`, undefined, { per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_apps_get_user_installation",
    description: "Get a user installation for the authenticated app",
    inputSchema: z.object({
      username: z.string().describe("username")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/users/${args.username}/installation`, undefined, undefined);
    },
  },
];
