// AUTO-GENERATED by scripts/generate.ts — DO NOT EDIT
import { z } from "zod";
import { githubRequest } from "../client.js";

export const billingTools = [
  {
    name: "github_billing_get_all_budgets_org",
    description: "Get all budgets for an organization",
    inputSchema: z.object({
      org: z.string().describe("org"),
      page: z.number().optional().describe("The page number of the results to fetch."),
      per_page: z.number().optional().describe("The number of results per page (max 10)."),
      scope: z.enum(["enterprise", "organization", "repository", "cost_center"]).optional().describe("Filter budgets by scope type.")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/organizations/${args.org}/settings/billing/budgets`, undefined, { page: args.page, per_page: args.per_page, scope: args.scope });
    },
  },
  {
    name: "github_billing_get_budget_org",
    description: "Get a budget by ID for an organization",
    inputSchema: z.object({
      org: z.string().describe("org"),
      budget_id: z.string().describe("budget_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/organizations/${args.org}/settings/billing/budgets/${args.budget_id}`, undefined, undefined);
    },
  },
  {
    name: "github_billing_update_budget_org",
    description: "Update a budget for an organization",
    inputSchema: z.object({
      org: z.string().describe("org"),
      budget_id: z.string().describe("budget_id"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("PATCH", `/organizations/${args.org}/settings/billing/budgets/${args.budget_id}`, args.body, undefined);
    },
  },
  {
    name: "github_billing_delete_budget_org",
    description: "Delete a budget for an organization",
    inputSchema: z.object({
      org: z.string().describe("org"),
      budget_id: z.string().describe("budget_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("DELETE", `/organizations/${args.org}/settings/billing/budgets/${args.budget_id}`, undefined, undefined);
    },
  },
  {
    name: "github_billing_get_github_billing_premium_request_usage_report_org",
    description: "Get billing premium request usage report for an organization",
    inputSchema: z.object({
      org: z.string().describe("org"),
      year: z.number().optional().describe("If specified, only return results for a single year. The value of `year` is an integer with four digits representing a year. For example, `2025`. Default value is the current year."),
      month: z.number().optional().describe("If specified, only return results for a single month. The value of `month` is an integer between `1` and `12`. Default value is the current month. If no year is specified the default `year` is used."),
      day: z.number().optional().describe("If specified, only return results for a single day. The value of `day` is an integer between `1` and `31`. If no `year` or `month` is specified, the default `year` and `month` are used."),
      user: z.string().optional().describe("The user name to query usage for. The name is not case sensitive."),
      model: z.string().optional().describe("The model name to query usage for. The name is not case sensitive."),
      product: z.string().optional().describe("The product name to query usage for. The name is not case sensitive.")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/organizations/${args.org}/settings/billing/premium_request/usage`, undefined, { year: args.year, month: args.month, day: args.day, user: args.user, model: args.model, product: args.product });
    },
  },
  {
    name: "github_billing_get_github_billing_usage_report_org",
    description: "Get billing usage report for an organization",
    inputSchema: z.object({
      org: z.string().describe("org"),
      year: z.number().optional().describe("If specified, only return results for a single year. The value of `year` is an integer with four digits representing a year. For example, `2025`. Default value is the current year."),
      month: z.number().optional().describe("If specified, only return results for a single month. The value of `month` is an integer between `1` and `12`. If no year is specified the default `year` is used."),
      day: z.number().optional().describe("If specified, only return results for a single day. The value of `day` is an integer between `1` and `31`. If no `year` or `month` is specified, the default `year` and `month` are used.")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/organizations/${args.org}/settings/billing/usage`, undefined, { year: args.year, month: args.month, day: args.day });
    },
  },
  {
    name: "github_billing_get_github_billing_usage_summary_report_org",
    description: "Get billing usage summary for an organization",
    inputSchema: z.object({
      org: z.string().describe("org"),
      year: z.number().optional().describe("If specified, only return results for a single year. The value of `year` is an integer with four digits representing a year. For example, `2025`. Default value is the current year."),
      month: z.number().optional().describe("If specified, only return results for a single month. The value of `month` is an integer between `1` and `12`. Default value is the current month. If no year is specified the default `year` is used."),
      day: z.number().optional().describe("If specified, only return results for a single day. The value of `day` is an integer between `1` and `31`. If no `year` or `month` is specified, the default `year` and `month` are used."),
      repository: z.string().optional().describe("The repository name to query for usage in the format owner/repository."),
      product: z.string().optional().describe("The product name to query usage for. The name is not case sensitive."),
      sku: z.string().optional().describe("The SKU to query for usage.")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/organizations/${args.org}/settings/billing/usage/summary`, undefined, { year: args.year, month: args.month, day: args.day, repository: args.repository, product: args.product, sku: args.sku });
    },
  },
  {
    name: "github_billing_get_github_billing_premium_request_usage_report_user",
    description: "Get billing premium request usage report for a user",
    inputSchema: z.object({
      username: z.string().describe("username"),
      year: z.number().optional().describe("If specified, only return results for a single year. The value of `year` is an integer with four digits representing a year. For example, `2025`. Default value is the current year."),
      month: z.number().optional().describe("If specified, only return results for a single month. The value of `month` is an integer between `1` and `12`. Default value is the current month. If no year is specified the default `year` is used."),
      day: z.number().optional().describe("If specified, only return results for a single day. The value of `day` is an integer between `1` and `31`. If no `year` or `month` is specified, the default `year` and `month` are used."),
      model: z.string().optional().describe("The model name to query usage for. The name is not case sensitive."),
      product: z.string().optional().describe("The product name to query usage for. The name is not case sensitive.")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/users/${args.username}/settings/billing/premium_request/usage`, undefined, { year: args.year, month: args.month, day: args.day, model: args.model, product: args.product });
    },
  },
  {
    name: "github_billing_get_github_billing_usage_report_user",
    description: "Get billing usage report for a user",
    inputSchema: z.object({
      username: z.string().describe("username"),
      year: z.number().optional().describe("If specified, only return results for a single year. The value of `year` is an integer with four digits representing a year. For example, `2025`. Default value is the current year."),
      month: z.number().optional().describe("If specified, only return results for a single month. The value of `month` is an integer between `1` and `12`. If no year is specified the default `year` is used."),
      day: z.number().optional().describe("If specified, only return results for a single day. The value of `day` is an integer between `1` and `31`. If no `year` or `month` is specified, the default `year` and `month` are used.")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/users/${args.username}/settings/billing/usage`, undefined, { year: args.year, month: args.month, day: args.day });
    },
  },
  {
    name: "github_billing_get_github_billing_usage_summary_report_user",
    description: "Get billing usage summary for a user",
    inputSchema: z.object({
      username: z.string().describe("username"),
      year: z.number().optional().describe("If specified, only return results for a single year. The value of `year` is an integer with four digits representing a year. For example, `2025`. Default value is the current year."),
      month: z.number().optional().describe("If specified, only return results for a single month. The value of `month` is an integer between `1` and `12`. Default value is the current month. If no year is specified the default `year` is used."),
      day: z.number().optional().describe("If specified, only return results for a single day. The value of `day` is an integer between `1` and `31`. If no `year` or `month` is specified, the default `year` and `month` are used."),
      repository: z.string().optional().describe("The repository name to query for usage in the format owner/repository."),
      product: z.string().optional().describe("The product name to query usage for. The name is not case sensitive."),
      sku: z.string().optional().describe("The SKU to query for usage.")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/users/${args.username}/settings/billing/usage/summary`, undefined, { year: args.year, month: args.month, day: args.day, repository: args.repository, product: args.product, sku: args.sku });
    },
  },
];
