// AUTO-GENERATED by scripts/generate.ts — DO NOT EDIT
import { z } from "zod";
import { githubRequest } from "../client.js";

export const campaignsTools = [
  {
    name: "github_campaigns_list_org_campaigns",
    description: "List campaigns for an organization",
    inputSchema: z.object({
      org: z.string().describe("org"),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      direction: z.enum(["asc", "desc"]).optional().describe("The direction to sort the results by."),
      state: z.unknown().optional().describe("If specified, only campaigns with this state will be returned."),
      sort: z.enum(["created", "updated", "ends_at", "published"]).optional().describe("The property by which to sort the results.")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/campaigns`, undefined, { page: args.page, per_page: args.per_page, direction: args.direction, state: args.state, sort: args.sort });
    },
  },
  {
    name: "github_campaigns_create_campaign",
    description: "Create a campaign for an organization",
    inputSchema: z.object({
      org: z.string().describe("org"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/orgs/${args.org}/campaigns`, args.body, undefined);
    },
  },
  {
    name: "github_campaigns_get_campaign_summary",
    description: "Get a campaign for an organization",
    inputSchema: z.object({
      org: z.string().describe("org"),
      campaign_number: z.string().describe("campaign_number")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/campaigns/${args.campaign_number}`, undefined, undefined);
    },
  },
  {
    name: "github_campaigns_update_campaign",
    description: "Update a campaign",
    inputSchema: z.object({
      org: z.string().describe("org"),
      campaign_number: z.string().describe("campaign_number"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("PATCH", `/orgs/${args.org}/campaigns/${args.campaign_number}`, args.body, undefined);
    },
  },
  {
    name: "github_campaigns_delete_campaign",
    description: "Delete a campaign for an organization",
    inputSchema: z.object({
      org: z.string().describe("org"),
      campaign_number: z.string().describe("campaign_number")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("DELETE", `/orgs/${args.org}/campaigns/${args.campaign_number}`, undefined, undefined);
    },
  },
];
