// AUTO-GENERATED by scripts/generate.ts — DO NOT EDIT
import { z } from "zod";
import { githubRequest } from "../client.js";

export const checksTools = [
  {
    name: "github_checks_create",
    description: "Create a check run",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/repos/${args.owner}/${args.repo}/check-runs`, args.body, undefined);
    },
  },
  {
    name: "github_checks_get",
    description: "Get a check run",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      check_run_id: z.string().describe("check_run_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/check-runs/${args.check_run_id}`, undefined, undefined);
    },
  },
  {
    name: "github_checks_update",
    description: "Update a check run",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      check_run_id: z.string().describe("check_run_id"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("PATCH", `/repos/${args.owner}/${args.repo}/check-runs/${args.check_run_id}`, args.body, undefined);
    },
  },
  {
    name: "github_checks_list_annotations",
    description: "List check run annotations",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      check_run_id: z.string().describe("check_run_id"),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/check-runs/${args.check_run_id}/annotations`, undefined, { per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_checks_rerequest_run",
    description: "Rerequest a check run",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      check_run_id: z.string().describe("check_run_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/repos/${args.owner}/${args.repo}/check-runs/${args.check_run_id}/rerequest`, undefined, undefined);
    },
  },
  {
    name: "github_checks_create_suite",
    description: "Create a check suite",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/repos/${args.owner}/${args.repo}/check-suites`, args.body, undefined);
    },
  },
  {
    name: "github_checks_set_suites_preferences",
    description: "Update repository preferences for check suites",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("PATCH", `/repos/${args.owner}/${args.repo}/check-suites/preferences`, args.body, undefined);
    },
  },
  {
    name: "github_checks_get_suite",
    description: "Get a check suite",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      check_suite_id: z.string().describe("check_suite_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/check-suites/${args.check_suite_id}`, undefined, undefined);
    },
  },
  {
    name: "github_checks_list_for_suite",
    description: "List check runs in a check suite",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      check_suite_id: z.string().describe("check_suite_id"),
      check_name: z.string().optional().describe("Returns check runs with the specified `name`."),
      status: z.enum(["queued", "in_progress", "completed"]).optional().describe("Returns check runs with the specified `status`."),
      filter: z.enum(["latest", "all"]).optional().describe("Filters check runs by their `completed_at` timestamp. `latest` returns the most recent check runs."),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/check-suites/${args.check_suite_id}/check-runs`, undefined, { check_name: args.check_name, status: args.status, filter: args.filter, per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_checks_rerequest_suite",
    description: "Rerequest a check suite",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      check_suite_id: z.string().describe("check_suite_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/repos/${args.owner}/${args.repo}/check-suites/${args.check_suite_id}/rerequest`, undefined, undefined);
    },
  },
  {
    name: "github_checks_list_for_ref",
    description: "List check runs for a Git reference",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      ref: z.string().describe("ref"),
      check_name: z.string().optional().describe("Returns check runs with the specified `name`."),
      status: z.enum(["queued", "in_progress", "completed"]).optional().describe("Returns check runs with the specified `status`."),
      filter: z.enum(["latest", "all"]).optional().describe("Filters check runs by their `completed_at` timestamp. `latest` returns the most recent check runs."),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      app_id: z.number().optional().describe("app_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/commits/${args.ref}/check-runs`, undefined, { check_name: args.check_name, status: args.status, filter: args.filter, per_page: args.per_page, page: args.page, app_id: args.app_id });
    },
  },
  {
    name: "github_checks_list_suites_for_ref",
    description: "List check suites for a Git reference",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      ref: z.string().describe("ref"),
      app_id: z.number().optional().describe("Filters check suites by GitHub App `id`."),
      check_name: z.string().optional().describe("Returns check runs with the specified `name`."),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/commits/${args.ref}/check-suites`, undefined, { app_id: args.app_id, check_name: args.check_name, per_page: args.per_page, page: args.page });
    },
  },
];
