// AUTO-GENERATED by scripts/generate.ts — DO NOT EDIT
import { z } from "zod";
import { githubRequest } from "../client.js";

export const codesOfConductTools = [
  {
    name: "github_codes_of_conduct_get_all_codes_of_conduct",
    description: "Get all codes of conduct",
    inputSchema: z.object({}),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/codes_of_conduct`, undefined, undefined);
    },
  },
  {
    name: "github_codes_of_conduct_get_conduct_code",
    description: "Get a code of conduct",
    inputSchema: z.object({
      key: z.string().describe("key")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/codes_of_conduct/${args.key}`, undefined, undefined);
    },
  },
];
