// AUTO-GENERATED by scripts/generate.ts — DO NOT EDIT
import { z } from "zod";
import { githubRequest } from "../client.js";

export const codespacesTools = [
  {
    name: "github_codespaces_list_in_organization",
    description: "List codespaces for the organization",
    inputSchema: z.object({
      org: z.string().describe("org"),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/codespaces`, undefined, { per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_codespaces_set_codespaces_access",
    description: "Manage access control for organization codespaces",
    inputSchema: z.object({
      org: z.string().describe("org"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("PUT", `/orgs/${args.org}/codespaces/access`, args.body, undefined);
    },
  },
  {
    name: "github_codespaces_set_codespaces_access_users",
    description: "Add users to Codespaces access for an organization",
    inputSchema: z.object({
      org: z.string().describe("org"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/orgs/${args.org}/codespaces/access/selected_users`, args.body, undefined);
    },
  },
  {
    name: "github_codespaces_delete_codespaces_access_users",
    description: "Remove users from Codespaces access for an organization",
    inputSchema: z.object({
      org: z.string().describe("org")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("DELETE", `/orgs/${args.org}/codespaces/access/selected_users`, undefined, undefined);
    },
  },
  {
    name: "github_codespaces_list_org_secrets",
    description: "List organization secrets",
    inputSchema: z.object({
      org: z.string().describe("org"),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/codespaces/secrets`, undefined, { per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_codespaces_get_org_public_key",
    description: "Get an organization public key",
    inputSchema: z.object({
      org: z.string().describe("org")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/codespaces/secrets/public-key`, undefined, undefined);
    },
  },
  {
    name: "github_codespaces_get_org_secret",
    description: "Get an organization secret",
    inputSchema: z.object({
      org: z.string().describe("org"),
      secret_name: z.string().describe("secret_name")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/codespaces/secrets/${args.secret_name}`, undefined, undefined);
    },
  },
  {
    name: "github_codespaces_create_or_update_org_secret",
    description: "Create or update an organization secret",
    inputSchema: z.object({
      org: z.string().describe("org"),
      secret_name: z.string().describe("secret_name"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("PUT", `/orgs/${args.org}/codespaces/secrets/${args.secret_name}`, args.body, undefined);
    },
  },
  {
    name: "github_codespaces_delete_org_secret",
    description: "Delete an organization secret",
    inputSchema: z.object({
      org: z.string().describe("org"),
      secret_name: z.string().describe("secret_name")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("DELETE", `/orgs/${args.org}/codespaces/secrets/${args.secret_name}`, undefined, undefined);
    },
  },
  {
    name: "github_codespaces_list_selected_repos_for_org_secret",
    description: "List selected repositories for an organization secret",
    inputSchema: z.object({
      org: z.string().describe("org"),
      secret_name: z.string().describe("secret_name"),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/codespaces/secrets/${args.secret_name}/repositories`, undefined, { page: args.page, per_page: args.per_page });
    },
  },
  {
    name: "github_codespaces_set_selected_repos_for_org_secret",
    description: "Set selected repositories for an organization secret",
    inputSchema: z.object({
      org: z.string().describe("org"),
      secret_name: z.string().describe("secret_name"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("PUT", `/orgs/${args.org}/codespaces/secrets/${args.secret_name}/repositories`, args.body, undefined);
    },
  },
  {
    name: "github_codespaces_add_selected_repo_to_org_secret",
    description: "Add selected repository to an organization secret",
    inputSchema: z.object({
      org: z.string().describe("org"),
      secret_name: z.string().describe("secret_name"),
      repository_id: z.string().describe("repository_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("PUT", `/orgs/${args.org}/codespaces/secrets/${args.secret_name}/repositories/${args.repository_id}`, undefined, undefined);
    },
  },
  {
    name: "github_codespaces_remove_selected_repo_from_org_secret",
    description: "Remove selected repository from an organization secret",
    inputSchema: z.object({
      org: z.string().describe("org"),
      secret_name: z.string().describe("secret_name"),
      repository_id: z.string().describe("repository_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("DELETE", `/orgs/${args.org}/codespaces/secrets/${args.secret_name}/repositories/${args.repository_id}`, undefined, undefined);
    },
  },
  {
    name: "github_codespaces_get_codespaces_for_user_in_org",
    description: "List codespaces for a user in organization",
    inputSchema: z.object({
      org: z.string().describe("org"),
      username: z.string().describe("username"),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/members/${args.username}/codespaces`, undefined, { per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_codespaces_delete_from_organization",
    description: "Delete a codespace from the organization",
    inputSchema: z.object({
      org: z.string().describe("org"),
      username: z.string().describe("username"),
      codespace_name: z.string().describe("codespace_name")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("DELETE", `/orgs/${args.org}/members/${args.username}/codespaces/${args.codespace_name}`, undefined, undefined);
    },
  },
  {
    name: "github_codespaces_stop_in_organization",
    description: "Stop a codespace for an organization user",
    inputSchema: z.object({
      org: z.string().describe("org"),
      username: z.string().describe("username"),
      codespace_name: z.string().describe("codespace_name")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/orgs/${args.org}/members/${args.username}/codespaces/${args.codespace_name}/stop`, undefined, undefined);
    },
  },
  {
    name: "github_codespaces_list_in_repository_for_authenticated_user",
    description: "List codespaces in a repository for the authenticated user",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/codespaces`, undefined, { per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_codespaces_create_with_repo_for_authenticated_user",
    description: "Create a codespace in a repository",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/repos/${args.owner}/${args.repo}/codespaces`, args.body, undefined);
    },
  },
  {
    name: "github_codespaces_list_devcontainers_in_repository_for_authenticated_user",
    description: "List devcontainer configurations in a repository for the authenticated user",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/codespaces/devcontainers`, undefined, { per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_codespaces_repo_machines_for_authenticated_user",
    description: "List available machine types for a repository",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      location: z.string().optional().describe("The location to check for available machines. Assigned by IP if not provided."),
      client_ip: z.string().optional().describe("IP for location auto-detection when proxying a request"),
      ref: z.string().optional().describe("The branch or commit to check for prebuild availability and devcontainer restrictions.")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/codespaces/machines`, undefined, { location: args.location, client_ip: args.client_ip, ref: args.ref });
    },
  },
  {
    name: "github_codespaces_pre_flight_with_repo_for_authenticated_user",
    description: "Get default attributes for a codespace",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      ref: z.string().optional().describe("The branch or commit to check for a default devcontainer path. If not specified, the default branch will be checked."),
      client_ip: z.string().optional().describe("An alternative IP for default location auto-detection, such as when proxying a request.")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/codespaces/new`, undefined, { ref: args.ref, client_ip: args.client_ip });
    },
  },
  {
    name: "github_codespaces_check_permissions_for_devcontainer",
    description: "Check if permissions defined by a devcontainer have been accepted by the authenticated user",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      ref: z.string().describe("The git reference that points to the location of the devcontainer configuration to use for the permission check. The value of `ref` will typically be a branch name (`heads/BRANCH_NAME`). For more information, see \"[Git References](https://git-scm.com/book/en/v2/Git-Internals-Git-References)\" in the Git documentation."),
      devcontainer_path: z.string().describe("Path to the devcontainer.json configuration to use for the permission check.")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/codespaces/permissions_check`, undefined, { ref: args.ref, devcontainer_path: args.devcontainer_path });
    },
  },
  {
    name: "github_codespaces_list_repo_secrets",
    description: "List repository secrets",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/codespaces/secrets`, undefined, { per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_codespaces_get_repo_public_key",
    description: "Get a repository public key",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/codespaces/secrets/public-key`, undefined, undefined);
    },
  },
  {
    name: "github_codespaces_get_repo_secret",
    description: "Get a repository secret",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      secret_name: z.string().describe("secret_name")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/codespaces/secrets/${args.secret_name}`, undefined, undefined);
    },
  },
  {
    name: "github_codespaces_create_or_update_repo_secret",
    description: "Create or update a repository secret",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      secret_name: z.string().describe("secret_name"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("PUT", `/repos/${args.owner}/${args.repo}/codespaces/secrets/${args.secret_name}`, args.body, undefined);
    },
  },
  {
    name: "github_codespaces_delete_repo_secret",
    description: "Delete a repository secret",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      secret_name: z.string().describe("secret_name")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("DELETE", `/repos/${args.owner}/${args.repo}/codespaces/secrets/${args.secret_name}`, undefined, undefined);
    },
  },
  {
    name: "github_codespaces_create_with_pr_for_authenticated_user",
    description: "Create a codespace from a pull request",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      pull_number: z.string().describe("pull_number"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/repos/${args.owner}/${args.repo}/pulls/${args.pull_number}/codespaces`, args.body, undefined);
    },
  },
  {
    name: "github_codespaces_list_for_authenticated_user",
    description: "List codespaces for the authenticated user",
    inputSchema: z.object({
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      repository_id: z.number().optional().describe("ID of the Repository to filter on")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/user/codespaces`, undefined, { per_page: args.per_page, page: args.page, repository_id: args.repository_id });
    },
  },
  {
    name: "github_codespaces_create_for_authenticated_user",
    description: "Create a codespace for the authenticated user",
    inputSchema: z.object({
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/user/codespaces`, args.body, undefined);
    },
  },
  {
    name: "github_codespaces_list_secrets_for_authenticated_user",
    description: "List secrets for the authenticated user",
    inputSchema: z.object({
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/user/codespaces/secrets`, undefined, { per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_codespaces_get_public_key_for_authenticated_user",
    description: "Get public key for the authenticated user",
    inputSchema: z.object({}),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/user/codespaces/secrets/public-key`, undefined, undefined);
    },
  },
  {
    name: "github_codespaces_get_secret_for_authenticated_user",
    description: "Get a secret for the authenticated user",
    inputSchema: z.object({
      secret_name: z.string().describe("secret_name")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/user/codespaces/secrets/${args.secret_name}`, undefined, undefined);
    },
  },
  {
    name: "github_codespaces_create_or_update_secret_for_authenticated_user",
    description: "Create or update a secret for the authenticated user",
    inputSchema: z.object({
      secret_name: z.string().describe("secret_name"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("PUT", `/user/codespaces/secrets/${args.secret_name}`, args.body, undefined);
    },
  },
  {
    name: "github_codespaces_delete_secret_for_authenticated_user",
    description: "Delete a secret for the authenticated user",
    inputSchema: z.object({
      secret_name: z.string().describe("secret_name")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("DELETE", `/user/codespaces/secrets/${args.secret_name}`, undefined, undefined);
    },
  },
  {
    name: "github_codespaces_list_repositories_for_secret_for_authenticated_user",
    description: "List selected repositories for a user secret",
    inputSchema: z.object({
      secret_name: z.string().describe("secret_name")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/user/codespaces/secrets/${args.secret_name}/repositories`, undefined, undefined);
    },
  },
  {
    name: "github_codespaces_set_repositories_for_secret_for_authenticated_user",
    description: "Set selected repositories for a user secret",
    inputSchema: z.object({
      secret_name: z.string().describe("secret_name"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("PUT", `/user/codespaces/secrets/${args.secret_name}/repositories`, args.body, undefined);
    },
  },
  {
    name: "github_codespaces_add_repository_for_secret_for_authenticated_user",
    description: "Add a selected repository to a user secret",
    inputSchema: z.object({
      secret_name: z.string().describe("secret_name"),
      repository_id: z.string().describe("repository_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("PUT", `/user/codespaces/secrets/${args.secret_name}/repositories/${args.repository_id}`, undefined, undefined);
    },
  },
  {
    name: "github_codespaces_remove_repository_for_secret_for_authenticated_user",
    description: "Remove a selected repository from a user secret",
    inputSchema: z.object({
      secret_name: z.string().describe("secret_name"),
      repository_id: z.string().describe("repository_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("DELETE", `/user/codespaces/secrets/${args.secret_name}/repositories/${args.repository_id}`, undefined, undefined);
    },
  },
  {
    name: "github_codespaces_get_for_authenticated_user",
    description: "Get a codespace for the authenticated user",
    inputSchema: z.object({
      codespace_name: z.string().describe("codespace_name")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/user/codespaces/${args.codespace_name}`, undefined, undefined);
    },
  },
  {
    name: "github_codespaces_update_for_authenticated_user",
    description: "Update a codespace for the authenticated user",
    inputSchema: z.object({
      codespace_name: z.string().describe("codespace_name"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("PATCH", `/user/codespaces/${args.codespace_name}`, args.body, undefined);
    },
  },
  {
    name: "github_codespaces_delete_for_authenticated_user",
    description: "Delete a codespace for the authenticated user",
    inputSchema: z.object({
      codespace_name: z.string().describe("codespace_name")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("DELETE", `/user/codespaces/${args.codespace_name}`, undefined, undefined);
    },
  },
  {
    name: "github_codespaces_export_for_authenticated_user",
    description: "Export a codespace for the authenticated user",
    inputSchema: z.object({
      codespace_name: z.string().describe("codespace_name")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/user/codespaces/${args.codespace_name}/exports`, undefined, undefined);
    },
  },
  {
    name: "github_codespaces_get_export_details_for_authenticated_user",
    description: "Get details about a codespace export",
    inputSchema: z.object({
      codespace_name: z.string().describe("codespace_name"),
      export_id: z.string().describe("export_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/user/codespaces/${args.codespace_name}/exports/${args.export_id}`, undefined, undefined);
    },
  },
  {
    name: "github_codespaces_codespace_machines_for_authenticated_user",
    description: "List machine types for a codespace",
    inputSchema: z.object({
      codespace_name: z.string().describe("codespace_name")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/user/codespaces/${args.codespace_name}/machines`, undefined, undefined);
    },
  },
  {
    name: "github_codespaces_publish_for_authenticated_user",
    description: "Create a repository from an unpublished codespace",
    inputSchema: z.object({
      codespace_name: z.string().describe("codespace_name"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/user/codespaces/${args.codespace_name}/publish`, args.body, undefined);
    },
  },
  {
    name: "github_codespaces_start_for_authenticated_user",
    description: "Start a codespace for the authenticated user",
    inputSchema: z.object({
      codespace_name: z.string().describe("codespace_name")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/user/codespaces/${args.codespace_name}/start`, undefined, undefined);
    },
  },
  {
    name: "github_codespaces_stop_for_authenticated_user",
    description: "Stop a codespace for the authenticated user",
    inputSchema: z.object({
      codespace_name: z.string().describe("codespace_name")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/user/codespaces/${args.codespace_name}/stop`, undefined, undefined);
    },
  },
];
