// AUTO-GENERATED by scripts/generate.ts — DO NOT EDIT
import { z } from "zod";
import { githubRequest } from "../client.js";

export const codeScanningTools = [
  {
    name: "github_code_scanning_list_alerts_for_org",
    description: "List code scanning alerts for an organization",
    inputSchema: z.object({
      org: z.string().describe("org"),
      tool_name: z.unknown().optional().describe("The name of a code scanning tool. Only results by this tool will be listed. You can specify the tool by using either `tool_name` or `tool_guid`, but not both."),
      tool_guid: z.unknown().optional().describe("The GUID of a code scanning tool. Only results by this tool will be listed. Note that some code scanning tools may not include a GUID in their analysis data. You can specify the tool by using either `tool_guid` or `tool_name`, but not both."),
      before: z.string().optional().describe("A cursor, as given in the [Link header](https://docs.github.com/rest/guides/using-pagination-in-the-rest-api#using-link-headers). If specified, the query only searches for results before this cursor. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      after: z.string().optional().describe("A cursor, as given in the [Link header](https://docs.github.com/rest/guides/using-pagination-in-the-rest-api#using-link-headers). If specified, the query only searches for results after this cursor. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      direction: z.enum(["asc", "desc"]).optional().describe("The direction to sort the results by."),
      state: z.unknown().optional().describe("If specified, only code scanning alerts with this state will be returned."),
      sort: z.enum(["created", "updated"]).optional().describe("The property by which to sort the results."),
      severity: z.unknown().optional().describe("If specified, only code scanning alerts with this severity will be returned."),
      assignees: z.string().optional().describe("Filter alerts by assignees. Provide a comma-separated list of user handles (e.g., `octocat` or `octocat,hubot`). Use `*` to list alerts with at least one assignee or `none` to list alerts with no assignees.")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/code-scanning/alerts`, undefined, { tool_name: args.tool_name, tool_guid: args.tool_guid, before: args.before, after: args.after, page: args.page, per_page: args.per_page, direction: args.direction, state: args.state, sort: args.sort, severity: args.severity, assignees: args.assignees });
    },
  },
  {
    name: "github_code_scanning_list_alerts_for_repo",
    description: "List code scanning alerts for a repository",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      tool_name: z.unknown().optional().describe("The name of a code scanning tool. Only results by this tool will be listed. You can specify the tool by using either `tool_name` or `tool_guid`, but not both."),
      tool_guid: z.unknown().optional().describe("The GUID of a code scanning tool. Only results by this tool will be listed. Note that some code scanning tools may not include a GUID in their analysis data. You can specify the tool by using either `tool_guid` or `tool_name`, but not both."),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      ref: z.unknown().optional().describe("The Git reference for the results you want to list. The `ref` for a branch can be formatted either as `refs/heads/<branch name>` or simply `<branch name>`. To reference a pull request use `refs/pull/<number>/merge`."),
      pr: z.number().optional().describe("The number of the pull request for the results you want to list."),
      direction: z.enum(["asc", "desc"]).optional().describe("The direction to sort the results by."),
      before: z.string().optional().describe("A cursor, as given in the [Link header](https://docs.github.com/rest/guides/using-pagination-in-the-rest-api#using-link-headers). If specified, the query only searches for results before this cursor. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      after: z.string().optional().describe("A cursor, as given in the [Link header](https://docs.github.com/rest/guides/using-pagination-in-the-rest-api#using-link-headers). If specified, the query only searches for results after this cursor. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      sort: z.enum(["created", "updated"]).optional().describe("The property by which to sort the results."),
      state: z.unknown().optional().describe("If specified, only code scanning alerts with this state will be returned."),
      severity: z.unknown().optional().describe("If specified, only code scanning alerts with this severity will be returned."),
      assignees: z.string().optional().describe("Filter alerts by assignees. Provide a comma-separated list of user handles (e.g., `octocat` or `octocat,hubot`). Use `*` to list alerts with at least one assignee or `none` to list alerts with no assignees.")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/code-scanning/alerts`, undefined, { tool_name: args.tool_name, tool_guid: args.tool_guid, page: args.page, per_page: args.per_page, ref: args.ref, pr: args.pr, direction: args.direction, before: args.before, after: args.after, sort: args.sort, state: args.state, severity: args.severity, assignees: args.assignees });
    },
  },
  {
    name: "github_code_scanning_get_alert",
    description: "Get a code scanning alert",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      alert_number: z.string().describe("alert_number")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/code-scanning/alerts/${args.alert_number}`, undefined, undefined);
    },
  },
  {
    name: "github_code_scanning_update_alert",
    description: "Update a code scanning alert",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      alert_number: z.string().describe("alert_number"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("PATCH", `/repos/${args.owner}/${args.repo}/code-scanning/alerts/${args.alert_number}`, args.body, undefined);
    },
  },
  {
    name: "github_code_scanning_get_autofix",
    description: "Get the status of an autofix for a code scanning alert",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      alert_number: z.string().describe("alert_number")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/code-scanning/alerts/${args.alert_number}/autofix`, undefined, undefined);
    },
  },
  {
    name: "github_code_scanning_create_autofix",
    description: "Create an autofix for a code scanning alert",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      alert_number: z.string().describe("alert_number")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/repos/${args.owner}/${args.repo}/code-scanning/alerts/${args.alert_number}/autofix`, undefined, undefined);
    },
  },
  {
    name: "github_code_scanning_commit_autofix",
    description: "Commit an autofix for a code scanning alert",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      alert_number: z.string().describe("alert_number"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/repos/${args.owner}/${args.repo}/code-scanning/alerts/${args.alert_number}/autofix/commits`, args.body, undefined);
    },
  },
  {
    name: "github_code_scanning_list_alert_instances",
    description: "List instances of a code scanning alert",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      alert_number: z.string().describe("alert_number"),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      ref: z.unknown().optional().describe("The Git reference for the results you want to list. The `ref` for a branch can be formatted either as `refs/heads/<branch name>` or simply `<branch name>`. To reference a pull request use `refs/pull/<number>/merge`."),
      pr: z.number().optional().describe("The number of the pull request for the results you want to list.")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/code-scanning/alerts/${args.alert_number}/instances`, undefined, { page: args.page, per_page: args.per_page, ref: args.ref, pr: args.pr });
    },
  },
  {
    name: "github_code_scanning_list_recent_analyses",
    description: "List code scanning analyses for a repository",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      tool_name: z.unknown().optional().describe("The name of a code scanning tool. Only results by this tool will be listed. You can specify the tool by using either `tool_name` or `tool_guid`, but not both."),
      tool_guid: z.unknown().optional().describe("The GUID of a code scanning tool. Only results by this tool will be listed. Note that some code scanning tools may not include a GUID in their analysis data. You can specify the tool by using either `tool_guid` or `tool_name`, but not both."),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      pr: z.number().optional().describe("The number of the pull request for the results you want to list."),
      ref: z.unknown().optional().describe("The Git reference for the analyses you want to list. The `ref` for a branch can be formatted either as `refs/heads/<branch name>` or simply `<branch name>`. To reference a pull request use `refs/pull/<number>/merge`."),
      sarif_id: z.unknown().optional().describe("Filter analyses belonging to the same SARIF upload."),
      direction: z.enum(["asc", "desc"]).optional().describe("The direction to sort the results by."),
      sort: z.enum(["created"]).optional().describe("The property by which to sort the results.")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/code-scanning/analyses`, undefined, { tool_name: args.tool_name, tool_guid: args.tool_guid, page: args.page, per_page: args.per_page, pr: args.pr, ref: args.ref, sarif_id: args.sarif_id, direction: args.direction, sort: args.sort });
    },
  },
  {
    name: "github_code_scanning_get_analysis",
    description: "Get a code scanning analysis for a repository",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      analysis_id: z.string().describe("analysis_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/code-scanning/analyses/${args.analysis_id}`, undefined, undefined);
    },
  },
  {
    name: "github_code_scanning_delete_analysis",
    description: "Delete a code scanning analysis from a repository",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      analysis_id: z.string().describe("analysis_id"),
      confirm_delete: z.string().optional().describe("Allow deletion if the specified analysis is the last in a set. If you attempt to delete the final analysis in a set without setting this parameter to `true`, you'll get a 400 response with the message: `Analysis is last of its type and deletion may result in the loss of historical alert data. Please specify confirm_delete.`")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("DELETE", `/repos/${args.owner}/${args.repo}/code-scanning/analyses/${args.analysis_id}`, undefined, { confirm_delete: args.confirm_delete });
    },
  },
  {
    name: "github_code_scanning_list_codeql_databases",
    description: "List CodeQL databases for a repository",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/code-scanning/codeql/databases`, undefined, undefined);
    },
  },
  {
    name: "github_code_scanning_get_codeql_database",
    description: "Get a CodeQL database for a repository",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      language: z.string().describe("language")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/code-scanning/codeql/databases/${args.language}`, undefined, undefined);
    },
  },
  {
    name: "github_code_scanning_delete_codeql_database",
    description: "Delete a CodeQL database",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      language: z.string().describe("language")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("DELETE", `/repos/${args.owner}/${args.repo}/code-scanning/codeql/databases/${args.language}`, undefined, undefined);
    },
  },
  {
    name: "github_code_scanning_create_variant_analysis",
    description: "Create a CodeQL variant analysis",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/repos/${args.owner}/${args.repo}/code-scanning/codeql/variant-analyses`, args.body, undefined);
    },
  },
  {
    name: "github_code_scanning_get_variant_analysis",
    description: "Get the summary of a CodeQL variant analysis",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      codeql_variant_analysis_id: z.string().describe("codeql_variant_analysis_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/code-scanning/codeql/variant-analyses/${args.codeql_variant_analysis_id}`, undefined, undefined);
    },
  },
  {
    name: "github_code_scanning_get_variant_analysis_repo_task",
    description: "Get the analysis status of a repository in a CodeQL variant analysis",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      codeql_variant_analysis_id: z.string().describe("codeql_variant_analysis_id"),
      repo_owner: z.string().describe("repo_owner"),
      repo_name: z.string().describe("repo_name")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/code-scanning/codeql/variant-analyses/${args.codeql_variant_analysis_id}/repos/${args.repo_owner}/${args.repo_name}`, undefined, undefined);
    },
  },
  {
    name: "github_code_scanning_get_default_setup",
    description: "Get a code scanning default setup configuration",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/code-scanning/default-setup`, undefined, undefined);
    },
  },
  {
    name: "github_code_scanning_update_default_setup",
    description: "Update a code scanning default setup configuration",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("PATCH", `/repos/${args.owner}/${args.repo}/code-scanning/default-setup`, args.body, undefined);
    },
  },
  {
    name: "github_code_scanning_upload_sarif",
    description: "Upload an analysis as SARIF data",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/repos/${args.owner}/${args.repo}/code-scanning/sarifs`, args.body, undefined);
    },
  },
  {
    name: "github_code_scanning_get_sarif",
    description: "Get information about a SARIF upload",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      sarif_id: z.string().describe("sarif_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/code-scanning/sarifs/${args.sarif_id}`, undefined, undefined);
    },
  },
];
