// AUTO-GENERATED by scripts/generate.ts — DO NOT EDIT
import { z } from "zod";
import { githubRequest } from "../client.js";

export const copilotTools = [
  {
    name: "github_copilot_copilot_enterprise_one_day_usage_metrics",
    description: "Get Copilot enterprise usage metrics for a specific day",
    inputSchema: z.object({
      enterprise: z.string().describe("enterprise"),
      day: z.string().describe("The day to request data for, in `YYYY-MM-DD` format.")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/enterprises/${args.enterprise}/copilot/metrics/reports/enterprise-1-day`, undefined, { day: args.day });
    },
  },
  {
    name: "github_copilot_copilot_enterprise_usage_metrics",
    description: "Get Copilot enterprise usage metrics",
    inputSchema: z.object({
      enterprise: z.string().describe("enterprise")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/enterprises/${args.enterprise}/copilot/metrics/reports/enterprise-28-day/latest`, undefined, undefined);
    },
  },
  {
    name: "github_copilot_copilot_users_one_day_usage_metrics",
    description: "Get Copilot users usage metrics for a specific day",
    inputSchema: z.object({
      enterprise: z.string().describe("enterprise"),
      day: z.string().describe("The day to request data for, in `YYYY-MM-DD` format.")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/enterprises/${args.enterprise}/copilot/metrics/reports/users-1-day`, undefined, { day: args.day });
    },
  },
  {
    name: "github_copilot_copilot_users_usage_metrics",
    description: "Get Copilot users usage metrics",
    inputSchema: z.object({
      enterprise: z.string().describe("enterprise")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/enterprises/${args.enterprise}/copilot/metrics/reports/users-28-day/latest`, undefined, undefined);
    },
  },
  {
    name: "github_copilot_get_copilot_organization_details",
    description: "Get Copilot seat information and settings for an organization",
    inputSchema: z.object({
      org: z.string().describe("org")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/copilot/billing`, undefined, undefined);
    },
  },
  {
    name: "github_copilot_list_copilot_seats",
    description: "List all Copilot seat assignments for an organization",
    inputSchema: z.object({
      org: z.string().describe("org"),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/copilot/billing/seats`, undefined, { page: args.page, per_page: args.per_page });
    },
  },
  {
    name: "github_copilot_add_copilot_seats_for_teams",
    description: "Add teams to the Copilot subscription for an organization",
    inputSchema: z.object({
      org: z.string().describe("org"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/orgs/${args.org}/copilot/billing/selected_teams`, args.body, undefined);
    },
  },
  {
    name: "github_copilot_cancel_copilot_seat_assignment_for_teams",
    description: "Remove teams from the Copilot subscription for an organization",
    inputSchema: z.object({
      org: z.string().describe("org")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("DELETE", `/orgs/${args.org}/copilot/billing/selected_teams`, undefined, undefined);
    },
  },
  {
    name: "github_copilot_add_copilot_seats_for_users",
    description: "Add users to the Copilot subscription for an organization",
    inputSchema: z.object({
      org: z.string().describe("org"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/orgs/${args.org}/copilot/billing/selected_users`, args.body, undefined);
    },
  },
  {
    name: "github_copilot_cancel_copilot_seat_assignment_for_users",
    description: "Remove users from the Copilot subscription for an organization",
    inputSchema: z.object({
      org: z.string().describe("org")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("DELETE", `/orgs/${args.org}/copilot/billing/selected_users`, undefined, undefined);
    },
  },
  {
    name: "github_copilot_get_copilot_coding_agent_permissions_organization",
    description: "Get Copilot coding agent permissions for an organization",
    inputSchema: z.object({
      org: z.string().describe("org")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/copilot/coding-agent/permissions`, undefined, undefined);
    },
  },
  {
    name: "github_copilot_set_copilot_coding_agent_permissions_organization",
    description: "Set Copilot coding agent permissions for an organization",
    inputSchema: z.object({
      org: z.string().describe("org"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("PUT", `/orgs/${args.org}/copilot/coding-agent/permissions`, args.body, undefined);
    },
  },
  {
    name: "github_copilot_list_copilot_coding_agent_selected_repositories_for_organization",
    description: "List repositories enabled for Copilot coding agent in an organization",
    inputSchema: z.object({
      org: z.string().describe("org"),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/copilot/coding-agent/permissions/repositories`, undefined, { per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_copilot_set_copilot_coding_agent_selected_repositories_for_organization",
    description: "Set selected repositories for Copilot coding agent in an organization",
    inputSchema: z.object({
      org: z.string().describe("org"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("PUT", `/orgs/${args.org}/copilot/coding-agent/permissions/repositories`, args.body, undefined);
    },
  },
  {
    name: "github_copilot_enable_copilot_coding_agent_for_repository_in_organization",
    description: "Enable a repository for Copilot coding agent in an organization",
    inputSchema: z.object({
      org: z.string().describe("org"),
      repository_id: z.string().describe("repository_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("PUT", `/orgs/${args.org}/copilot/coding-agent/permissions/repositories/${args.repository_id}`, undefined, undefined);
    },
  },
  {
    name: "github_copilot_disable_copilot_coding_agent_for_repository_in_organization",
    description: "Disable a repository for Copilot coding agent in an organization",
    inputSchema: z.object({
      org: z.string().describe("org"),
      repository_id: z.string().describe("repository_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("DELETE", `/orgs/${args.org}/copilot/coding-agent/permissions/repositories/${args.repository_id}`, undefined, undefined);
    },
  },
  {
    name: "github_copilot_copilot_content_exclusion_for_organization",
    description: "Get Copilot content exclusion rules for an organization",
    inputSchema: z.object({
      org: z.string().describe("org")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/copilot/content_exclusion`, undefined, undefined);
    },
  },
  {
    name: "github_copilot_set_copilot_content_exclusion_for_organization",
    description: "Set Copilot content exclusion rules for an organization",
    inputSchema: z.object({
      org: z.string().describe("org"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("PUT", `/orgs/${args.org}/copilot/content_exclusion`, args.body, undefined);
    },
  },
  {
    name: "github_copilot_copilot_metrics_for_organization",
    description: "Get Copilot metrics for an organization",
    inputSchema: z.object({
      org: z.string().describe("org"),
      since: z.string().optional().describe("Show usage metrics since this date. This is a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format (`YYYY-MM-DDTHH:MM:SSZ`). Maximum value is 100 days ago."),
      until: z.string().optional().describe("Show usage metrics until this date. This is a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format (`YYYY-MM-DDTHH:MM:SSZ`) and should not preceed the `since` date if it is passed."),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      per_page: z.number().optional().describe("The number of days of metrics to display per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/copilot/metrics`, undefined, { since: args.since, until: args.until, page: args.page, per_page: args.per_page });
    },
  },
  {
    name: "github_copilot_copilot_organization_one_day_usage_metrics",
    description: "Get Copilot organization usage metrics for a specific day",
    inputSchema: z.object({
      org: z.string().describe("org"),
      day: z.string().describe("The day to request data for, in `YYYY-MM-DD` format.")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/copilot/metrics/reports/organization-1-day`, undefined, { day: args.day });
    },
  },
  {
    name: "github_copilot_copilot_organization_usage_metrics",
    description: "Get Copilot organization usage metrics",
    inputSchema: z.object({
      org: z.string().describe("org")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/copilot/metrics/reports/organization-28-day/latest`, undefined, undefined);
    },
  },
  {
    name: "github_copilot_copilot_organization_users_one_day_usage_metrics",
    description: "Get Copilot organization users usage metrics for a specific day",
    inputSchema: z.object({
      org: z.string().describe("org"),
      day: z.string().describe("The day to request data for, in `YYYY-MM-DD` format.")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/copilot/metrics/reports/users-1-day`, undefined, { day: args.day });
    },
  },
  {
    name: "github_copilot_copilot_organization_users_usage_metrics",
    description: "Get Copilot organization users usage metrics",
    inputSchema: z.object({
      org: z.string().describe("org")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/copilot/metrics/reports/users-28-day/latest`, undefined, undefined);
    },
  },
  {
    name: "github_copilot_get_copilot_seat_details_for_user",
    description: "Get Copilot seat assignment details for a user",
    inputSchema: z.object({
      org: z.string().describe("org"),
      username: z.string().describe("username")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/members/${args.username}/copilot`, undefined, undefined);
    },
  },
  {
    name: "github_copilot_copilot_metrics_for_team",
    description: "Get Copilot metrics for a team",
    inputSchema: z.object({
      org: z.string().describe("org"),
      team_slug: z.string().describe("team_slug"),
      since: z.string().optional().describe("Show usage metrics since this date. This is a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format (`YYYY-MM-DDTHH:MM:SSZ`). Maximum value is 100 days ago."),
      until: z.string().optional().describe("Show usage metrics until this date. This is a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format (`YYYY-MM-DDTHH:MM:SSZ`) and should not preceed the `since` date if it is passed."),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      per_page: z.number().optional().describe("The number of days of metrics to display per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/team/${args.team_slug}/copilot/metrics`, undefined, { since: args.since, until: args.until, page: args.page, per_page: args.per_page });
    },
  },
];
