// AUTO-GENERATED by scripts/generate.ts — DO NOT EDIT
import { z } from "zod";
import { githubRequest } from "../client.js";

export const credentialsTools = [
  {
    name: "github_credentials_revoke",
    description: "Revoke a list of credentials",
    inputSchema: z.object({
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/credentials/revoke`, args.body, undefined);
    },
  },
];
