// AUTO-GENERATED by scripts/generate.ts — DO NOT EDIT
import { z } from "zod";
import { githubRequest } from "../client.js";

export const dependabotTools = [
  {
    name: "github_dependabot_list_alerts_for_enterprise",
    description: "List Dependabot alerts for an enterprise",
    inputSchema: z.object({
      enterprise: z.string().describe("enterprise"),
      classification: z.string().optional().describe("A comma-separated list of vulnerability classifications. If specified, only alerts for vulnerabilities with these classifications will be returned.  Can be: `malware`, `general`"),
      state: z.string().optional().describe("A comma-separated list of states. If specified, only alerts with these states will be returned.  Can be: `auto_dismissed`, `dismissed`, `fixed`, `open`"),
      severity: z.string().optional().describe("A comma-separated list of severities. If specified, only alerts with these severities will be returned.  Can be: `low`, `medium`, `high`, `critical`"),
      ecosystem: z.string().optional().describe("A comma-separated list of ecosystems. If specified, only alerts for these ecosystems will be returned.  Can be: `composer`, `go`, `maven`, `npm`, `nuget`, `pip`, `pub`, `rubygems`, `rust`"),
      package: z.string().optional().describe("A comma-separated list of package names. If specified, only alerts for these packages will be returned."),
      epss_percentage: z.string().optional().describe("CVE Exploit Prediction Scoring System (EPSS) percentage. Can be specified as: - An exact number (`n`) - Comparators such as `>n`, `<n`, `>=n`, `<=n` - A range like `n..n`, where `n` is a number from 0.0 to 1.0  Filters the list of alerts based on EPSS percentages. If specified, only alerts with the provided EPSS percentages will be returned."),
      has: z.unknown().optional().describe("Filters the list of alerts based on whether the alert has the given value. If specified, only alerts meeting this criterion will be returned. Multiple `has` filters can be passed to filter for alerts that have all of the values. Currently, only `patch` is supported."),
      assignee: z.string().optional().describe("Filter alerts by assignees. Provide a comma-separated list of user handles (e.g., `octocat` or `octocat,hubot`) to return alerts assigned to any of the specified users. Use `*` to list alerts with at least one assignee or `none` to list alerts with no assignees."),
      scope: z.enum(["development", "runtime"]).optional().describe("The scope of the vulnerable dependency. If specified, only alerts with this scope will be returned."),
      sort: z.enum(["created", "updated", "epss_percentage"]).optional().describe("The property by which to sort the results. `created` means when the alert was created. `updated` means when the alert's state last changed. `epss_percentage` sorts alerts by the Exploit Prediction Scoring System (EPSS) percentage."),
      direction: z.enum(["asc", "desc"]).optional().describe("The direction to sort the results by."),
      before: z.string().optional().describe("A cursor, as given in the [Link header](https://docs.github.com/rest/guides/using-pagination-in-the-rest-api#using-link-headers). If specified, the query only searches for results before this cursor. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      after: z.string().optional().describe("A cursor, as given in the [Link header](https://docs.github.com/rest/guides/using-pagination-in-the-rest-api#using-link-headers). If specified, the query only searches for results after this cursor. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/enterprises/${args.enterprise}/dependabot/alerts`, undefined, { classification: args.classification, state: args.state, severity: args.severity, ecosystem: args.ecosystem, package: args.package, epss_percentage: args.epss_percentage, has: args.has, assignee: args.assignee, scope: args.scope, sort: args.sort, direction: args.direction, before: args.before, after: args.after, per_page: args.per_page });
    },
  },
  {
    name: "github_dependabot_repository_access_for_org",
    description: "Lists the repositories Dependabot can access in an organization",
    inputSchema: z.object({
      org: z.string().describe("org"),
      page: z.number().optional().describe("The page number of results to fetch."),
      per_page: z.number().optional().describe("Number of results per page.")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/organizations/${args.org}/dependabot/repository-access`, undefined, { page: args.page, per_page: args.per_page });
    },
  },
  {
    name: "github_dependabot_update_repository_access_for_org",
    description: "Updates Dependabot's repository access list for an organization",
    inputSchema: z.object({
      org: z.string().describe("org"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("PATCH", `/organizations/${args.org}/dependabot/repository-access`, args.body, undefined);
    },
  },
  {
    name: "github_dependabot_set_repository_access_default_level",
    description: "Set the default repository access level for Dependabot",
    inputSchema: z.object({
      org: z.string().describe("org"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("PUT", `/organizations/${args.org}/dependabot/repository-access/default-level`, args.body, undefined);
    },
  },
  {
    name: "github_dependabot_list_alerts_for_org",
    description: "List Dependabot alerts for an organization",
    inputSchema: z.object({
      org: z.string().describe("org"),
      classification: z.string().optional().describe("A comma-separated list of vulnerability classifications. If specified, only alerts for vulnerabilities with these classifications will be returned.  Can be: `malware`, `general`"),
      state: z.string().optional().describe("A comma-separated list of states. If specified, only alerts with these states will be returned.  Can be: `auto_dismissed`, `dismissed`, `fixed`, `open`"),
      severity: z.string().optional().describe("A comma-separated list of severities. If specified, only alerts with these severities will be returned.  Can be: `low`, `medium`, `high`, `critical`"),
      ecosystem: z.string().optional().describe("A comma-separated list of ecosystems. If specified, only alerts for these ecosystems will be returned.  Can be: `composer`, `go`, `maven`, `npm`, `nuget`, `pip`, `pub`, `rubygems`, `rust`"),
      package: z.string().optional().describe("A comma-separated list of package names. If specified, only alerts for these packages will be returned."),
      epss_percentage: z.string().optional().describe("CVE Exploit Prediction Scoring System (EPSS) percentage. Can be specified as: - An exact number (`n`) - Comparators such as `>n`, `<n`, `>=n`, `<=n` - A range like `n..n`, where `n` is a number from 0.0 to 1.0  Filters the list of alerts based on EPSS percentages. If specified, only alerts with the provided EPSS percentages will be returned."),
      artifact_registry_url: z.string().optional().describe("A comma-separated list of artifact registry URLs. If specified, only alerts for repositories with storage records matching these URLs will be returned."),
      artifact_registry: z.string().optional().describe("A comma-separated list of Artifact Registry name strings. If specified, only alerts for repositories with storage records matching these registries will be returned.  Can be: `jfrog-artifactory`"),
      has: z.unknown().optional().describe("Filters the list of alerts based on whether the alert has the given value. If specified, only alerts meeting this criterion will be returned. Multiple `has` filters can be passed to filter for alerts that have all of the values."),
      assignee: z.string().optional().describe("Filter alerts by assignees. Provide a comma-separated list of user handles (e.g., `octocat` or `octocat,hubot`) to return alerts assigned to any of the specified users. Use `*` to list alerts with at least one assignee or `none` to list alerts with no assignees."),
      runtime_risk: z.string().optional().describe("A comma-separated list of runtime risk strings. If specified, only alerts for repositories with deployment records matching these risks will be returned.  Can be: `critical-resource`, `internet-exposed`, `sensitive-data`, `lateral-movement`"),
      scope: z.enum(["development", "runtime"]).optional().describe("The scope of the vulnerable dependency. If specified, only alerts with this scope will be returned."),
      sort: z.enum(["created", "updated", "epss_percentage"]).optional().describe("The property by which to sort the results. `created` means when the alert was created. `updated` means when the alert's state last changed. `epss_percentage` sorts alerts by the Exploit Prediction Scoring System (EPSS) percentage."),
      direction: z.enum(["asc", "desc"]).optional().describe("The direction to sort the results by."),
      before: z.string().optional().describe("A cursor, as given in the [Link header](https://docs.github.com/rest/guides/using-pagination-in-the-rest-api#using-link-headers). If specified, the query only searches for results before this cursor. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      after: z.string().optional().describe("A cursor, as given in the [Link header](https://docs.github.com/rest/guides/using-pagination-in-the-rest-api#using-link-headers). If specified, the query only searches for results after this cursor. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/dependabot/alerts`, undefined, { classification: args.classification, state: args.state, severity: args.severity, ecosystem: args.ecosystem, package: args.package, epss_percentage: args.epss_percentage, artifact_registry_url: args.artifact_registry_url, artifact_registry: args.artifact_registry, has: args.has, assignee: args.assignee, runtime_risk: args.runtime_risk, scope: args.scope, sort: args.sort, direction: args.direction, before: args.before, after: args.after, per_page: args.per_page });
    },
  },
  {
    name: "github_dependabot_list_org_secrets",
    description: "List organization secrets",
    inputSchema: z.object({
      org: z.string().describe("org"),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/dependabot/secrets`, undefined, { per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_dependabot_get_org_public_key",
    description: "Get an organization public key",
    inputSchema: z.object({
      org: z.string().describe("org")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/dependabot/secrets/public-key`, undefined, undefined);
    },
  },
  {
    name: "github_dependabot_get_org_secret",
    description: "Get an organization secret",
    inputSchema: z.object({
      org: z.string().describe("org"),
      secret_name: z.string().describe("secret_name")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/dependabot/secrets/${args.secret_name}`, undefined, undefined);
    },
  },
  {
    name: "github_dependabot_create_or_update_org_secret",
    description: "Create or update an organization secret",
    inputSchema: z.object({
      org: z.string().describe("org"),
      secret_name: z.string().describe("secret_name"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("PUT", `/orgs/${args.org}/dependabot/secrets/${args.secret_name}`, args.body, undefined);
    },
  },
  {
    name: "github_dependabot_delete_org_secret",
    description: "Delete an organization secret",
    inputSchema: z.object({
      org: z.string().describe("org"),
      secret_name: z.string().describe("secret_name")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("DELETE", `/orgs/${args.org}/dependabot/secrets/${args.secret_name}`, undefined, undefined);
    },
  },
  {
    name: "github_dependabot_list_selected_repos_for_org_secret",
    description: "List selected repositories for an organization secret",
    inputSchema: z.object({
      org: z.string().describe("org"),
      secret_name: z.string().describe("secret_name"),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/dependabot/secrets/${args.secret_name}/repositories`, undefined, { page: args.page, per_page: args.per_page });
    },
  },
  {
    name: "github_dependabot_set_selected_repos_for_org_secret",
    description: "Set selected repositories for an organization secret",
    inputSchema: z.object({
      org: z.string().describe("org"),
      secret_name: z.string().describe("secret_name"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("PUT", `/orgs/${args.org}/dependabot/secrets/${args.secret_name}/repositories`, args.body, undefined);
    },
  },
  {
    name: "github_dependabot_add_selected_repo_to_org_secret",
    description: "Add selected repository to an organization secret",
    inputSchema: z.object({
      org: z.string().describe("org"),
      secret_name: z.string().describe("secret_name"),
      repository_id: z.string().describe("repository_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("PUT", `/orgs/${args.org}/dependabot/secrets/${args.secret_name}/repositories/${args.repository_id}`, undefined, undefined);
    },
  },
  {
    name: "github_dependabot_remove_selected_repo_from_org_secret",
    description: "Remove selected repository from an organization secret",
    inputSchema: z.object({
      org: z.string().describe("org"),
      secret_name: z.string().describe("secret_name"),
      repository_id: z.string().describe("repository_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("DELETE", `/orgs/${args.org}/dependabot/secrets/${args.secret_name}/repositories/${args.repository_id}`, undefined, undefined);
    },
  },
  {
    name: "github_dependabot_list_alerts_for_repo",
    description: "List Dependabot alerts for a repository",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      classification: z.string().optional().describe("A comma-separated list of vulnerability classifications. If specified, only alerts for vulnerabilities with these classifications will be returned.  Can be: `malware`, `general`"),
      state: z.string().optional().describe("A comma-separated list of states. If specified, only alerts with these states will be returned.  Can be: `auto_dismissed`, `dismissed`, `fixed`, `open`"),
      severity: z.string().optional().describe("A comma-separated list of severities. If specified, only alerts with these severities will be returned.  Can be: `low`, `medium`, `high`, `critical`"),
      ecosystem: z.string().optional().describe("A comma-separated list of ecosystems. If specified, only alerts for these ecosystems will be returned.  Can be: `composer`, `go`, `maven`, `npm`, `nuget`, `pip`, `pub`, `rubygems`, `rust`"),
      package: z.string().optional().describe("A comma-separated list of package names. If specified, only alerts for these packages will be returned."),
      manifest: z.string().optional().describe("A comma-separated list of full manifest paths. If specified, only alerts for these manifests will be returned."),
      epss_percentage: z.string().optional().describe("CVE Exploit Prediction Scoring System (EPSS) percentage. Can be specified as: - An exact number (`n`) - Comparators such as `>n`, `<n`, `>=n`, `<=n` - A range like `n..n`, where `n` is a number from 0.0 to 1.0  Filters the list of alerts based on EPSS percentages. If specified, only alerts with the provided EPSS percentages will be returned."),
      has: z.unknown().optional().describe("Filters the list of alerts based on whether the alert has the given value. If specified, only alerts meeting this criterion will be returned. Multiple `has` filters can be passed to filter for alerts that have all of the values. Currently, only `patch` is supported."),
      assignee: z.string().optional().describe("Filter alerts by assignees. Provide a comma-separated list of user handles (e.g., `octocat` or `octocat,hubot`) to return alerts assigned to any of the specified users. Use `*` to list alerts with at least one assignee or `none` to list alerts with no assignees."),
      scope: z.enum(["development", "runtime"]).optional().describe("The scope of the vulnerable dependency. If specified, only alerts with this scope will be returned."),
      sort: z.enum(["created", "updated", "epss_percentage"]).optional().describe("The property by which to sort the results. `created` means when the alert was created. `updated` means when the alert's state last changed. `epss_percentage` sorts alerts by the Exploit Prediction Scoring System (EPSS) percentage."),
      direction: z.enum(["asc", "desc"]).optional().describe("The direction to sort the results by."),
      before: z.string().optional().describe("A cursor, as given in the [Link header](https://docs.github.com/rest/guides/using-pagination-in-the-rest-api#using-link-headers). If specified, the query only searches for results before this cursor. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      after: z.string().optional().describe("A cursor, as given in the [Link header](https://docs.github.com/rest/guides/using-pagination-in-the-rest-api#using-link-headers). If specified, the query only searches for results after this cursor. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/dependabot/alerts`, undefined, { classification: args.classification, state: args.state, severity: args.severity, ecosystem: args.ecosystem, package: args.package, manifest: args.manifest, epss_percentage: args.epss_percentage, has: args.has, assignee: args.assignee, scope: args.scope, sort: args.sort, direction: args.direction, before: args.before, after: args.after, per_page: args.per_page });
    },
  },
  {
    name: "github_dependabot_get_alert",
    description: "Get a Dependabot alert",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      alert_number: z.string().describe("alert_number")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/dependabot/alerts/${args.alert_number}`, undefined, undefined);
    },
  },
  {
    name: "github_dependabot_update_alert",
    description: "Update a Dependabot alert",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      alert_number: z.string().describe("alert_number"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("PATCH", `/repos/${args.owner}/${args.repo}/dependabot/alerts/${args.alert_number}`, args.body, undefined);
    },
  },
  {
    name: "github_dependabot_list_repo_secrets",
    description: "List repository secrets",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/dependabot/secrets`, undefined, { per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_dependabot_get_repo_public_key",
    description: "Get a repository public key",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/dependabot/secrets/public-key`, undefined, undefined);
    },
  },
  {
    name: "github_dependabot_get_repo_secret",
    description: "Get a repository secret",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      secret_name: z.string().describe("secret_name")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/dependabot/secrets/${args.secret_name}`, undefined, undefined);
    },
  },
  {
    name: "github_dependabot_create_or_update_repo_secret",
    description: "Create or update a repository secret",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      secret_name: z.string().describe("secret_name"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("PUT", `/repos/${args.owner}/${args.repo}/dependabot/secrets/${args.secret_name}`, args.body, undefined);
    },
  },
  {
    name: "github_dependabot_delete_repo_secret",
    description: "Delete a repository secret",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      secret_name: z.string().describe("secret_name")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("DELETE", `/repos/${args.owner}/${args.repo}/dependabot/secrets/${args.secret_name}`, undefined, undefined);
    },
  },
];
