// AUTO-GENERATED by scripts/generate.ts — DO NOT EDIT
import { z } from "zod";
import { githubRequest } from "../client.js";

export const dependencyGraphTools = [
  {
    name: "github_dependency_graph_diff_range",
    description: "Get a diff of the dependencies between commits",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      basehead: z.string().describe("basehead"),
      name: z.string().optional().describe("The full path, relative to the repository root, of the dependency manifest file.")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/dependency-graph/compare/${args.basehead}`, undefined, { name: args.name });
    },
  },
  {
    name: "github_dependency_graph_export_sbom",
    description: "Export a software bill of materials (SBOM) for a repository.",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/dependency-graph/sbom`, undefined, undefined);
    },
  },
  {
    name: "github_dependency_graph_create_repository_snapshot",
    description: "Create a snapshot of dependencies for a repository",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/repos/${args.owner}/${args.repo}/dependency-graph/snapshots`, args.body, undefined);
    },
  },
];
