// AUTO-GENERATED by scripts/generate.ts — DO NOT EDIT
import { z } from "zod";
import { githubRequest } from "../client.js";

export const emojisTools = [
  {
    name: "github_emojis_get",
    description: "Get emojis",
    inputSchema: z.object({}),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/emojis`, undefined, undefined);
    },
  },
];
