// AUTO-GENERATED by scripts/generate.ts — DO NOT EDIT
import { z } from "zod";
import { githubRequest } from "../client.js";

export const enterpriseTeamOrganizationsTools = [
  {
    name: "github_enterprise_team_organizations_get_assignments",
    description: "Get organization assignments",
    inputSchema: z.object({
      enterprise: z.string().describe("enterprise"),
      enterprise_team: z.string().describe("enterprise-team"),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/enterprises/${args.enterprise}/teams/${args.enterprise_team}/organizations`, undefined, { per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_enterprise_team_organizations_bulk_add",
    description: "Add organization assignments",
    inputSchema: z.object({
      enterprise: z.string().describe("enterprise"),
      enterprise_team: z.string().describe("enterprise-team"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/enterprises/${args.enterprise}/teams/${args.enterprise_team}/organizations/add`, args.body, undefined);
    },
  },
  {
    name: "github_enterprise_team_organizations_bulk_remove",
    description: "Remove organization assignments",
    inputSchema: z.object({
      enterprise: z.string().describe("enterprise"),
      enterprise_team: z.string().describe("enterprise-team"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/enterprises/${args.enterprise}/teams/${args.enterprise_team}/organizations/remove`, args.body, undefined);
    },
  },
  {
    name: "github_enterprise_team_organizations_get_assignment",
    description: "Get organization assignment",
    inputSchema: z.object({
      enterprise: z.string().describe("enterprise"),
      enterprise_team: z.string().describe("enterprise-team"),
      org: z.string().describe("org")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/enterprises/${args.enterprise}/teams/${args.enterprise_team}/organizations/${args.org}`, undefined, undefined);
    },
  },
  {
    name: "github_enterprise_team_organizations_add",
    description: "Add an organization assignment",
    inputSchema: z.object({
      enterprise: z.string().describe("enterprise"),
      enterprise_team: z.string().describe("enterprise-team"),
      org: z.string().describe("org")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("PUT", `/enterprises/${args.enterprise}/teams/${args.enterprise_team}/organizations/${args.org}`, undefined, undefined);
    },
  },
  {
    name: "github_enterprise_team_organizations_delete",
    description: "Delete an organization assignment",
    inputSchema: z.object({
      enterprise: z.string().describe("enterprise"),
      enterprise_team: z.string().describe("enterprise-team"),
      org: z.string().describe("org")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("DELETE", `/enterprises/${args.enterprise}/teams/${args.enterprise_team}/organizations/${args.org}`, undefined, undefined);
    },
  },
];
