// AUTO-GENERATED by scripts/generate.ts — DO NOT EDIT
import { z } from "zod";
import { githubRequest } from "../client.js";

export const gistsTools = [
  {
    name: "github_gists_list",
    description: "List gists for the authenticated user",
    inputSchema: z.object({
      since: z.string().optional().describe("Only show results that were last updated after the given time. This is a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ`."),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/gists`, undefined, { since: args.since, per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_gists_create",
    description: "Create a gist",
    inputSchema: z.object({
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/gists`, args.body, undefined);
    },
  },
  {
    name: "github_gists_list_public",
    description: "List public gists",
    inputSchema: z.object({
      since: z.string().optional().describe("Only show results that were last updated after the given time. This is a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ`."),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/gists/public`, undefined, { since: args.since, per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_gists_list_starred",
    description: "List starred gists",
    inputSchema: z.object({
      since: z.string().optional().describe("Only show results that were last updated after the given time. This is a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ`."),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/gists/starred`, undefined, { since: args.since, per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_gists_get",
    description: "Get a gist",
    inputSchema: z.object({
      gist_id: z.string().describe("gist_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/gists/${args.gist_id}`, undefined, undefined);
    },
  },
  {
    name: "github_gists_update",
    description: "Update a gist",
    inputSchema: z.object({
      gist_id: z.string().describe("gist_id"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("PATCH", `/gists/${args.gist_id}`, args.body, undefined);
    },
  },
  {
    name: "github_gists_delete",
    description: "Delete a gist",
    inputSchema: z.object({
      gist_id: z.string().describe("gist_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("DELETE", `/gists/${args.gist_id}`, undefined, undefined);
    },
  },
  {
    name: "github_gists_list_comments",
    description: "List gist comments",
    inputSchema: z.object({
      gist_id: z.string().describe("gist_id"),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/gists/${args.gist_id}/comments`, undefined, { per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_gists_create_comment",
    description: "Create a gist comment",
    inputSchema: z.object({
      gist_id: z.string().describe("gist_id"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/gists/${args.gist_id}/comments`, args.body, undefined);
    },
  },
  {
    name: "github_gists_get_comment",
    description: "Get a gist comment",
    inputSchema: z.object({
      gist_id: z.string().describe("gist_id"),
      comment_id: z.string().describe("comment_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/gists/${args.gist_id}/comments/${args.comment_id}`, undefined, undefined);
    },
  },
  {
    name: "github_gists_update_comment",
    description: "Update a gist comment",
    inputSchema: z.object({
      gist_id: z.string().describe("gist_id"),
      comment_id: z.string().describe("comment_id"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("PATCH", `/gists/${args.gist_id}/comments/${args.comment_id}`, args.body, undefined);
    },
  },
  {
    name: "github_gists_delete_comment",
    description: "Delete a gist comment",
    inputSchema: z.object({
      gist_id: z.string().describe("gist_id"),
      comment_id: z.string().describe("comment_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("DELETE", `/gists/${args.gist_id}/comments/${args.comment_id}`, undefined, undefined);
    },
  },
  {
    name: "github_gists_list_commits",
    description: "List gist commits",
    inputSchema: z.object({
      gist_id: z.string().describe("gist_id"),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/gists/${args.gist_id}/commits`, undefined, { per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_gists_list_forks",
    description: "List gist forks",
    inputSchema: z.object({
      gist_id: z.string().describe("gist_id"),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/gists/${args.gist_id}/forks`, undefined, { per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_gists_fork",
    description: "Fork a gist",
    inputSchema: z.object({
      gist_id: z.string().describe("gist_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/gists/${args.gist_id}/forks`, undefined, undefined);
    },
  },
  {
    name: "github_gists_check_is_starred",
    description: "Check if a gist is starred",
    inputSchema: z.object({
      gist_id: z.string().describe("gist_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/gists/${args.gist_id}/star`, undefined, undefined);
    },
  },
  {
    name: "github_gists_star",
    description: "Star a gist",
    inputSchema: z.object({
      gist_id: z.string().describe("gist_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("PUT", `/gists/${args.gist_id}/star`, undefined, undefined);
    },
  },
  {
    name: "github_gists_unstar",
    description: "Unstar a gist",
    inputSchema: z.object({
      gist_id: z.string().describe("gist_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("DELETE", `/gists/${args.gist_id}/star`, undefined, undefined);
    },
  },
  {
    name: "github_gists_get_revision",
    description: "Get a gist revision",
    inputSchema: z.object({
      gist_id: z.string().describe("gist_id"),
      sha: z.string().describe("sha")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/gists/${args.gist_id}/${args.sha}`, undefined, undefined);
    },
  },
  {
    name: "github_gists_list_for_user",
    description: "List gists for a user",
    inputSchema: z.object({
      username: z.string().describe("username"),
      since: z.string().optional().describe("Only show results that were last updated after the given time. This is a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ`."),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/users/${args.username}/gists`, undefined, { since: args.since, per_page: args.per_page, page: args.page });
    },
  },
];
