// AUTO-GENERATED by scripts/generate.ts — DO NOT EDIT
import { z } from "zod";
import { githubRequest } from "../client.js";

export const gitTools = [
  {
    name: "github_git_create_blob",
    description: "Create a blob",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/repos/${args.owner}/${args.repo}/git/blobs`, args.body, undefined);
    },
  },
  {
    name: "github_git_get_blob",
    description: "Get a blob",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      file_sha: z.string().describe("file_sha")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/git/blobs/${args.file_sha}`, undefined, undefined);
    },
  },
  {
    name: "github_git_create_commit",
    description: "Create a commit",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/repos/${args.owner}/${args.repo}/git/commits`, args.body, undefined);
    },
  },
  {
    name: "github_git_get_commit",
    description: "Get a commit object",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      commit_sha: z.string().describe("commit_sha")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/git/commits/${args.commit_sha}`, undefined, undefined);
    },
  },
  {
    name: "github_git_list_matching_refs",
    description: "List matching references",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      ref: z.string().describe("ref")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/git/matching-refs/${args.ref}`, undefined, undefined);
    },
  },
  {
    name: "github_git_get_ref",
    description: "Get a reference",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      ref: z.string().describe("ref")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/git/ref/${args.ref}`, undefined, undefined);
    },
  },
  {
    name: "github_git_create_ref",
    description: "Create a reference",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/repos/${args.owner}/${args.repo}/git/refs`, args.body, undefined);
    },
  },
  {
    name: "github_git_update_ref",
    description: "Update a reference",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      ref: z.string().describe("ref"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("PATCH", `/repos/${args.owner}/${args.repo}/git/refs/${args.ref}`, args.body, undefined);
    },
  },
  {
    name: "github_git_delete_ref",
    description: "Delete a reference",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      ref: z.string().describe("ref")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("DELETE", `/repos/${args.owner}/${args.repo}/git/refs/${args.ref}`, undefined, undefined);
    },
  },
  {
    name: "github_git_create_tag",
    description: "Create a tag object",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/repos/${args.owner}/${args.repo}/git/tags`, args.body, undefined);
    },
  },
  {
    name: "github_git_get_tag",
    description: "Get a tag",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      tag_sha: z.string().describe("tag_sha")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/git/tags/${args.tag_sha}`, undefined, undefined);
    },
  },
  {
    name: "github_git_create_tree",
    description: "Create a tree",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/repos/${args.owner}/${args.repo}/git/trees`, args.body, undefined);
    },
  },
  {
    name: "github_git_get_tree",
    description: "Get a tree",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      tree_sha: z.string().describe("tree_sha"),
      recursive: z.string().optional().describe("Setting this parameter to any value returns the objects or subtrees referenced by the tree specified in `:tree_sha`. For example, setting `recursive` to any of the following will enable returning objects or subtrees: `0`, `1`, `\"true\"`, and `\"false\"`. Omit this parameter to prevent recursively returning objects or subtrees.")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/git/trees/${args.tree_sha}`, undefined, { recursive: args.recursive });
    },
  },
];
