// AUTO-GENERATED by scripts/generate.ts — DO NOT EDIT
import { z } from "zod";
import { githubRequest } from "../client.js";

export const hostedComputeTools = [
  {
    name: "github_hosted_compute_list_network_configurations_for_org",
    description: "List hosted compute network configurations for an organization",
    inputSchema: z.object({
      org: z.string().describe("org"),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/settings/network-configurations`, undefined, { per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_hosted_compute_create_network_configuration_for_org",
    description: "Create a hosted compute network configuration for an organization",
    inputSchema: z.object({
      org: z.string().describe("org"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/orgs/${args.org}/settings/network-configurations`, args.body, undefined);
    },
  },
  {
    name: "github_hosted_compute_get_network_configuration_for_org",
    description: "Get a hosted compute network configuration for an organization",
    inputSchema: z.object({
      org: z.string().describe("org"),
      network_configuration_id: z.string().describe("network_configuration_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/settings/network-configurations/${args.network_configuration_id}`, undefined, undefined);
    },
  },
  {
    name: "github_hosted_compute_update_network_configuration_for_org",
    description: "Update a hosted compute network configuration for an organization",
    inputSchema: z.object({
      org: z.string().describe("org"),
      network_configuration_id: z.string().describe("network_configuration_id"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("PATCH", `/orgs/${args.org}/settings/network-configurations/${args.network_configuration_id}`, args.body, undefined);
    },
  },
  {
    name: "github_hosted_compute_delete_network_configuration_from_org",
    description: "Delete a hosted compute network configuration from an organization",
    inputSchema: z.object({
      org: z.string().describe("org"),
      network_configuration_id: z.string().describe("network_configuration_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("DELETE", `/orgs/${args.org}/settings/network-configurations/${args.network_configuration_id}`, undefined, undefined);
    },
  },
  {
    name: "github_hosted_compute_get_network_settings_for_org",
    description: "Get a hosted compute network settings resource for an organization",
    inputSchema: z.object({
      org: z.string().describe("org"),
      network_settings_id: z.string().describe("network_settings_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/settings/network-settings/${args.network_settings_id}`, undefined, undefined);
    },
  },
];
