// AUTO-GENERATED by scripts/generate.ts — DO NOT EDIT
import { z } from "zod";
import { githubRequest } from "../client.js";

export const interactionsTools = [
  {
    name: "github_interactions_get_restrictions_for_org",
    description: "Get interaction restrictions for an organization",
    inputSchema: z.object({
      org: z.string().describe("org")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/interaction-limits`, undefined, undefined);
    },
  },
  {
    name: "github_interactions_set_restrictions_for_org",
    description: "Set interaction restrictions for an organization",
    inputSchema: z.object({
      org: z.string().describe("org"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("PUT", `/orgs/${args.org}/interaction-limits`, args.body, undefined);
    },
  },
  {
    name: "github_interactions_remove_restrictions_for_org",
    description: "Remove interaction restrictions for an organization",
    inputSchema: z.object({
      org: z.string().describe("org")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("DELETE", `/orgs/${args.org}/interaction-limits`, undefined, undefined);
    },
  },
  {
    name: "github_interactions_get_restrictions_for_repo",
    description: "Get interaction restrictions for a repository",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/interaction-limits`, undefined, undefined);
    },
  },
  {
    name: "github_interactions_set_restrictions_for_repo",
    description: "Set interaction restrictions for a repository",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("PUT", `/repos/${args.owner}/${args.repo}/interaction-limits`, args.body, undefined);
    },
  },
  {
    name: "github_interactions_remove_restrictions_for_repo",
    description: "Remove interaction restrictions for a repository",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("DELETE", `/repos/${args.owner}/${args.repo}/interaction-limits`, undefined, undefined);
    },
  },
  {
    name: "github_interactions_get_restrictions_for_authenticated_user",
    description: "Get interaction restrictions for your public repositories",
    inputSchema: z.object({}),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/user/interaction-limits`, undefined, undefined);
    },
  },
  {
    name: "github_interactions_set_restrictions_for_authenticated_user",
    description: "Set interaction restrictions for your public repositories",
    inputSchema: z.object({
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("PUT", `/user/interaction-limits`, args.body, undefined);
    },
  },
  {
    name: "github_interactions_remove_restrictions_for_authenticated_user",
    description: "Remove interaction restrictions from your public repositories",
    inputSchema: z.object({}),
    handler: async (args: Record<string, any>) => {
      return githubRequest("DELETE", `/user/interaction-limits`, undefined, undefined);
    },
  },
];
