// AUTO-GENERATED by scripts/generate.ts — DO NOT EDIT
import { z } from "zod";
import { githubRequest } from "../client.js";

export const issuesTools = [
  {
    name: "github_issues_list",
    description: "List issues assigned to the authenticated user",
    inputSchema: z.object({
      filter: z.enum(["assigned", "created", "mentioned", "subscribed", "repos", "all"]).optional().describe("Indicates which sorts of issues to return. `assigned` means issues assigned to you. `created` means issues created by you. `mentioned` means issues mentioning you. `subscribed` means issues you're subscribed to updates for. `all` or `repos` means all issues you can see, regardless of participation or creation."),
      state: z.enum(["open", "closed", "all"]).optional().describe("Indicates the state of the issues to return."),
      labels: z.string().optional().describe("A list of comma separated label names. Example: `bug,ui,@high`"),
      sort: z.enum(["created", "updated", "comments"]).optional().describe("What to sort results by."),
      direction: z.enum(["asc", "desc"]).optional().describe("The direction to sort the results by."),
      since: z.string().optional().describe("Only show results that were last updated after the given time. This is a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ`."),
      collab: z.boolean().optional().describe("collab"),
      orgs: z.boolean().optional().describe("orgs"),
      owned: z.boolean().optional().describe("owned"),
      pulls: z.boolean().optional().describe("pulls"),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/issues`, undefined, { filter: args.filter, state: args.state, labels: args.labels, sort: args.sort, direction: args.direction, since: args.since, collab: args.collab, orgs: args.orgs, owned: args.owned, pulls: args.pulls, per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_issues_list_for_org",
    description: "List organization issues assigned to the authenticated user",
    inputSchema: z.object({
      org: z.string().describe("org"),
      filter: z.enum(["assigned", "created", "mentioned", "subscribed", "repos", "all"]).optional().describe("Indicates which sorts of issues to return. `assigned` means issues assigned to you. `created` means issues created by you. `mentioned` means issues mentioning you. `subscribed` means issues you're subscribed to updates for. `all` or `repos` means all issues you can see, regardless of participation or creation."),
      state: z.enum(["open", "closed", "all"]).optional().describe("Indicates the state of the issues to return."),
      labels: z.string().optional().describe("A list of comma separated label names. Example: `bug,ui,@high`"),
      type: z.string().optional().describe("Can be the name of an issue type."),
      sort: z.enum(["created", "updated", "comments"]).optional().describe("What to sort results by."),
      direction: z.enum(["asc", "desc"]).optional().describe("The direction to sort the results by."),
      since: z.string().optional().describe("Only show results that were last updated after the given time. This is a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ`."),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/issues`, undefined, { filter: args.filter, state: args.state, labels: args.labels, type: args.type, sort: args.sort, direction: args.direction, since: args.since, per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_issues_list_assignees",
    description: "List assignees",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/assignees`, undefined, { per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_issues_check_user_can_be_assigned",
    description: "Check if a user can be assigned",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      assignee: z.string().describe("assignee")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/assignees/${args.assignee}`, undefined, undefined);
    },
  },
  {
    name: "github_issues_list_for_repo",
    description: "List repository issues",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      milestone: z.string().optional().describe("If an `integer` is passed, it should refer to a milestone by its `number` field. If the string `*` is passed, issues with any milestone are accepted. If the string `none` is passed, issues without milestones are returned."),
      state: z.enum(["open", "closed", "all"]).optional().describe("Indicates the state of the issues to return."),
      assignee: z.string().optional().describe("Can be the name of a user. Pass in `none` for issues with no assigned user, and `*` for issues assigned to any user."),
      type: z.string().optional().describe("Can be the name of an issue type. If the string `*` is passed, issues with any type are accepted. If the string `none` is passed, issues without type are returned."),
      creator: z.string().optional().describe("The user that created the issue."),
      mentioned: z.string().optional().describe("A user that's mentioned in the issue."),
      labels: z.string().optional().describe("A list of comma separated label names. Example: `bug,ui,@high`"),
      sort: z.enum(["created", "updated", "comments"]).optional().describe("What to sort results by."),
      direction: z.enum(["asc", "desc"]).optional().describe("The direction to sort the results by."),
      since: z.string().optional().describe("Only show results that were last updated after the given time. This is a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ`."),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/issues`, undefined, { milestone: args.milestone, state: args.state, assignee: args.assignee, type: args.type, creator: args.creator, mentioned: args.mentioned, labels: args.labels, sort: args.sort, direction: args.direction, since: args.since, per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_issues_create",
    description: "Create an issue",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/repos/${args.owner}/${args.repo}/issues`, args.body, undefined);
    },
  },
  {
    name: "github_issues_list_comments_for_repo",
    description: "List issue comments for a repository",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      sort: z.enum(["created", "updated"]).optional().describe("The property to sort the results by."),
      direction: z.enum(["asc", "desc"]).optional().describe("Either `asc` or `desc`. Ignored without the `sort` parameter."),
      since: z.string().optional().describe("Only show results that were last updated after the given time. This is a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ`."),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/issues/comments`, undefined, { sort: args.sort, direction: args.direction, since: args.since, per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_issues_get_comment",
    description: "Get an issue comment",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      comment_id: z.string().describe("comment_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/issues/comments/${args.comment_id}`, undefined, undefined);
    },
  },
  {
    name: "github_issues_update_comment",
    description: "Update an issue comment",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      comment_id: z.string().describe("comment_id"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("PATCH", `/repos/${args.owner}/${args.repo}/issues/comments/${args.comment_id}`, args.body, undefined);
    },
  },
  {
    name: "github_issues_delete_comment",
    description: "Delete an issue comment",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      comment_id: z.string().describe("comment_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("DELETE", `/repos/${args.owner}/${args.repo}/issues/comments/${args.comment_id}`, undefined, undefined);
    },
  },
  {
    name: "github_issues_pin_comment",
    description: "Pin an issue comment",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      comment_id: z.string().describe("comment_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("PUT", `/repos/${args.owner}/${args.repo}/issues/comments/${args.comment_id}/pin`, undefined, undefined);
    },
  },
  {
    name: "github_issues_unpin_comment",
    description: "Unpin an issue comment",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      comment_id: z.string().describe("comment_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("DELETE", `/repos/${args.owner}/${args.repo}/issues/comments/${args.comment_id}/pin`, undefined, undefined);
    },
  },
  {
    name: "github_issues_list_events_for_repo",
    description: "List issue events for a repository",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/issues/events`, undefined, { per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_issues_get_event",
    description: "Get an issue event",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      event_id: z.string().describe("event_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/issues/events/${args.event_id}`, undefined, undefined);
    },
  },
  {
    name: "github_issues_get",
    description: "Get an issue",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      issue_number: z.string().describe("issue_number")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/issues/${args.issue_number}`, undefined, undefined);
    },
  },
  {
    name: "github_issues_update",
    description: "Update an issue",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      issue_number: z.string().describe("issue_number"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("PATCH", `/repos/${args.owner}/${args.repo}/issues/${args.issue_number}`, args.body, undefined);
    },
  },
  {
    name: "github_issues_add_assignees",
    description: "Add assignees to an issue",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      issue_number: z.string().describe("issue_number"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/repos/${args.owner}/${args.repo}/issues/${args.issue_number}/assignees`, args.body, undefined);
    },
  },
  {
    name: "github_issues_remove_assignees",
    description: "Remove assignees from an issue",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      issue_number: z.string().describe("issue_number")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("DELETE", `/repos/${args.owner}/${args.repo}/issues/${args.issue_number}/assignees`, undefined, undefined);
    },
  },
  {
    name: "github_issues_check_user_can_be_assigned_to_issue",
    description: "Check if a user can be assigned to a issue",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      issue_number: z.string().describe("issue_number"),
      assignee: z.string().describe("assignee")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/issues/${args.issue_number}/assignees/${args.assignee}`, undefined, undefined);
    },
  },
  {
    name: "github_issues_list_comments",
    description: "List issue comments",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      issue_number: z.string().describe("issue_number"),
      since: z.string().optional().describe("Only show results that were last updated after the given time. This is a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ`."),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/issues/${args.issue_number}/comments`, undefined, { since: args.since, per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_issues_create_comment",
    description: "Create an issue comment",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      issue_number: z.string().describe("issue_number"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/repos/${args.owner}/${args.repo}/issues/${args.issue_number}/comments`, args.body, undefined);
    },
  },
  {
    name: "github_issues_list_dependencies_blocked_by",
    description: "List dependencies an issue is blocked by",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      issue_number: z.string().describe("issue_number"),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/issues/${args.issue_number}/dependencies/blocked_by`, undefined, { per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_issues_add_blocked_by_dependency",
    description: "Add a dependency an issue is blocked by",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      issue_number: z.string().describe("issue_number"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/repos/${args.owner}/${args.repo}/issues/${args.issue_number}/dependencies/blocked_by`, args.body, undefined);
    },
  },
  {
    name: "github_issues_remove_dependency_blocked_by",
    description: "Remove dependency an issue is blocked by",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      issue_number: z.string().describe("issue_number"),
      issue_id: z.string().describe("issue_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("DELETE", `/repos/${args.owner}/${args.repo}/issues/${args.issue_number}/dependencies/blocked_by/${args.issue_id}`, undefined, undefined);
    },
  },
  {
    name: "github_issues_list_dependencies_blocking",
    description: "List dependencies an issue is blocking",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      issue_number: z.string().describe("issue_number"),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/issues/${args.issue_number}/dependencies/blocking`, undefined, { per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_issues_list_events",
    description: "List issue events",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      issue_number: z.string().describe("issue_number"),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/issues/${args.issue_number}/events`, undefined, { per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_issues_list_issue_field_values_for_issue",
    description: "List issue field values for an issue",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      issue_number: z.string().describe("issue_number"),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/issues/${args.issue_number}/issue-field-values`, undefined, { per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_issues_list_labels_on_issue",
    description: "List labels for an issue",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      issue_number: z.string().describe("issue_number"),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/issues/${args.issue_number}/labels`, undefined, { per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_issues_add_labels",
    description: "Add labels to an issue",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      issue_number: z.string().describe("issue_number"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/repos/${args.owner}/${args.repo}/issues/${args.issue_number}/labels`, args.body, undefined);
    },
  },
  {
    name: "github_issues_set_labels",
    description: "Set labels for an issue",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      issue_number: z.string().describe("issue_number"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("PUT", `/repos/${args.owner}/${args.repo}/issues/${args.issue_number}/labels`, args.body, undefined);
    },
  },
  {
    name: "github_issues_remove_all_labels",
    description: "Remove all labels from an issue",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      issue_number: z.string().describe("issue_number")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("DELETE", `/repos/${args.owner}/${args.repo}/issues/${args.issue_number}/labels`, undefined, undefined);
    },
  },
  {
    name: "github_issues_remove_label",
    description: "Remove a label from an issue",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      issue_number: z.string().describe("issue_number"),
      name: z.string().describe("name")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("DELETE", `/repos/${args.owner}/${args.repo}/issues/${args.issue_number}/labels/${args.name}`, undefined, undefined);
    },
  },
  {
    name: "github_issues_lock",
    description: "Lock an issue",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      issue_number: z.string().describe("issue_number"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("PUT", `/repos/${args.owner}/${args.repo}/issues/${args.issue_number}/lock`, args.body, undefined);
    },
  },
  {
    name: "github_issues_unlock",
    description: "Unlock an issue",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      issue_number: z.string().describe("issue_number")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("DELETE", `/repos/${args.owner}/${args.repo}/issues/${args.issue_number}/lock`, undefined, undefined);
    },
  },
  {
    name: "github_issues_get_parent",
    description: "Get parent issue",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      issue_number: z.string().describe("issue_number")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/issues/${args.issue_number}/parent`, undefined, undefined);
    },
  },
  {
    name: "github_issues_remove_sub_issue",
    description: "Remove sub-issue",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      issue_number: z.string().describe("issue_number")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("DELETE", `/repos/${args.owner}/${args.repo}/issues/${args.issue_number}/sub_issue`, undefined, undefined);
    },
  },
  {
    name: "github_issues_list_sub_issues",
    description: "List sub-issues",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      issue_number: z.string().describe("issue_number"),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/issues/${args.issue_number}/sub_issues`, undefined, { per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_issues_add_sub_issue",
    description: "Add sub-issue",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      issue_number: z.string().describe("issue_number"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/repos/${args.owner}/${args.repo}/issues/${args.issue_number}/sub_issues`, args.body, undefined);
    },
  },
  {
    name: "github_issues_reprioritize_sub_issue",
    description: "Reprioritize sub-issue",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      issue_number: z.string().describe("issue_number"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("PATCH", `/repos/${args.owner}/${args.repo}/issues/${args.issue_number}/sub_issues/priority`, args.body, undefined);
    },
  },
  {
    name: "github_issues_list_events_for_timeline",
    description: "List timeline events for an issue",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      issue_number: z.string().describe("issue_number"),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/issues/${args.issue_number}/timeline`, undefined, { per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_issues_list_labels_for_repo",
    description: "List labels for a repository",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/labels`, undefined, { per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_issues_create_label",
    description: "Create a label",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/repos/${args.owner}/${args.repo}/labels`, args.body, undefined);
    },
  },
  {
    name: "github_issues_get_label",
    description: "Get a label",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      name: z.string().describe("name")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/labels/${args.name}`, undefined, undefined);
    },
  },
  {
    name: "github_issues_update_label",
    description: "Update a label",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      name: z.string().describe("name"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("PATCH", `/repos/${args.owner}/${args.repo}/labels/${args.name}`, args.body, undefined);
    },
  },
  {
    name: "github_issues_delete_label",
    description: "Delete a label",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      name: z.string().describe("name")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("DELETE", `/repos/${args.owner}/${args.repo}/labels/${args.name}`, undefined, undefined);
    },
  },
  {
    name: "github_issues_list_milestones",
    description: "List milestones",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      state: z.enum(["open", "closed", "all"]).optional().describe("The state of the milestone. Either `open`, `closed`, or `all`."),
      sort: z.enum(["due_on", "completeness"]).optional().describe("What to sort results by. Either `due_on` or `completeness`."),
      direction: z.enum(["asc", "desc"]).optional().describe("The direction of the sort. Either `asc` or `desc`."),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/milestones`, undefined, { state: args.state, sort: args.sort, direction: args.direction, per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_issues_create_milestone",
    description: "Create a milestone",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/repos/${args.owner}/${args.repo}/milestones`, args.body, undefined);
    },
  },
  {
    name: "github_issues_get_milestone",
    description: "Get a milestone",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      milestone_number: z.string().describe("milestone_number")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/milestones/${args.milestone_number}`, undefined, undefined);
    },
  },
  {
    name: "github_issues_update_milestone",
    description: "Update a milestone",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      milestone_number: z.string().describe("milestone_number"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("PATCH", `/repos/${args.owner}/${args.repo}/milestones/${args.milestone_number}`, args.body, undefined);
    },
  },
  {
    name: "github_issues_delete_milestone",
    description: "Delete a milestone",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      milestone_number: z.string().describe("milestone_number")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("DELETE", `/repos/${args.owner}/${args.repo}/milestones/${args.milestone_number}`, undefined, undefined);
    },
  },
  {
    name: "github_issues_list_labels_for_milestone",
    description: "List labels for issues in a milestone",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      milestone_number: z.string().describe("milestone_number"),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/milestones/${args.milestone_number}/labels`, undefined, { per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_issues_add_issue_field_values",
    description: "Add issue field values to an issue",
    inputSchema: z.object({
      repository_id: z.string().describe("repository_id"),
      issue_number: z.string().describe("issue_number"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/repositories/${args.repository_id}/issues/${args.issue_number}/issue-field-values`, args.body, undefined);
    },
  },
  {
    name: "github_issues_set_issue_field_values",
    description: "Set issue field values for an issue",
    inputSchema: z.object({
      repository_id: z.string().describe("repository_id"),
      issue_number: z.string().describe("issue_number"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("PUT", `/repositories/${args.repository_id}/issues/${args.issue_number}/issue-field-values`, args.body, undefined);
    },
  },
  {
    name: "github_issues_delete_issue_field_value",
    description: "Delete an issue field value from an issue",
    inputSchema: z.object({
      repository_id: z.string().describe("repository_id"),
      issue_number: z.string().describe("issue_number"),
      issue_field_id: z.string().describe("issue_field_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("DELETE", `/repositories/${args.repository_id}/issues/${args.issue_number}/issue-field-values/${args.issue_field_id}`, undefined, undefined);
    },
  },
  {
    name: "github_issues_list_for_authenticated_user",
    description: "List user account issues assigned to the authenticated user",
    inputSchema: z.object({
      filter: z.enum(["assigned", "created", "mentioned", "subscribed", "repos", "all"]).optional().describe("Indicates which sorts of issues to return. `assigned` means issues assigned to you. `created` means issues created by you. `mentioned` means issues mentioning you. `subscribed` means issues you're subscribed to updates for. `all` or `repos` means all issues you can see, regardless of participation or creation."),
      state: z.enum(["open", "closed", "all"]).optional().describe("Indicates the state of the issues to return."),
      labels: z.string().optional().describe("A list of comma separated label names. Example: `bug,ui,@high`"),
      sort: z.enum(["created", "updated", "comments"]).optional().describe("What to sort results by."),
      direction: z.enum(["asc", "desc"]).optional().describe("The direction to sort the results by."),
      since: z.string().optional().describe("Only show results that were last updated after the given time. This is a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ`."),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/user/issues`, undefined, { filter: args.filter, state: args.state, labels: args.labels, sort: args.sort, direction: args.direction, since: args.since, per_page: args.per_page, page: args.page });
    },
  },
];
