// AUTO-GENERATED by scripts/generate.ts — DO NOT EDIT
import { z } from "zod";
import { githubRequest } from "../client.js";

export const licensesTools = [
  {
    name: "github_licenses_get_all_commonly_used",
    description: "Get all commonly used licenses",
    inputSchema: z.object({
      featured: z.boolean().optional().describe("featured"),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/licenses`, undefined, { featured: args.featured, per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_licenses_get",
    description: "Get a license",
    inputSchema: z.object({
      license: z.string().describe("license")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/licenses/${args.license}`, undefined, undefined);
    },
  },
  {
    name: "github_licenses_get_for_repo",
    description: "Get the license for a repository",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      ref: z.unknown().optional().describe("The Git reference for the results you want to list. The `ref` for a branch can be formatted either as `refs/heads/<branch name>` or simply `<branch name>`. To reference a pull request use `refs/pull/<number>/merge`.")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/license`, undefined, { ref: args.ref });
    },
  },
];
