// AUTO-GENERATED by scripts/generate.ts — DO NOT EDIT
import { z } from "zod";
import { githubRequest } from "../client.js";

export const metaTools = [
  {
    name: "github_meta_root",
    description: "GitHub API Root",
    inputSchema: z.object({}),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/`, undefined, undefined);
    },
  },
  {
    name: "github_meta_get",
    description: "Get GitHub meta information",
    inputSchema: z.object({}),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/meta`, undefined, undefined);
    },
  },
  {
    name: "github_meta_get_octocat",
    description: "Get Octocat",
    inputSchema: z.object({
      s: z.string().optional().describe("The words to show in Octocat's speech bubble")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/octocat`, undefined, { s: args.s });
    },
  },
  {
    name: "github_meta_get_all_versions",
    description: "Get all API versions",
    inputSchema: z.object({}),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/versions`, undefined, undefined);
    },
  },
  {
    name: "github_meta_get_zen",
    description: "Get the Zen of GitHub",
    inputSchema: z.object({}),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/zen`, undefined, undefined);
    },
  },
];
