// AUTO-GENERATED by scripts/generate.ts — DO NOT EDIT
import { z } from "zod";
import { githubRequest } from "../client.js";

export const migrationsTools = [
  {
    name: "github_migrations_list_for_org",
    description: "List organization migrations",
    inputSchema: z.object({
      org: z.string().describe("org"),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      exclude: z.array(z.enum(["repositories"])).optional().describe("Exclude attributes from the API response to improve performance")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/migrations`, undefined, { per_page: args.per_page, page: args.page, exclude: args.exclude });
    },
  },
  {
    name: "github_migrations_start_for_org",
    description: "Start an organization migration",
    inputSchema: z.object({
      org: z.string().describe("org"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/orgs/${args.org}/migrations`, args.body, undefined);
    },
  },
  {
    name: "github_migrations_get_status_for_org",
    description: "Get an organization migration status",
    inputSchema: z.object({
      org: z.string().describe("org"),
      migration_id: z.string().describe("migration_id"),
      exclude: z.array(z.enum(["repositories"])).optional().describe("Exclude attributes from the API response to improve performance")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/migrations/${args.migration_id}`, undefined, { exclude: args.exclude });
    },
  },
  {
    name: "github_migrations_download_archive_for_org",
    description: "Download an organization migration archive",
    inputSchema: z.object({
      org: z.string().describe("org"),
      migration_id: z.string().describe("migration_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/migrations/${args.migration_id}/archive`, undefined, undefined);
    },
  },
  {
    name: "github_migrations_delete_archive_for_org",
    description: "Delete an organization migration archive",
    inputSchema: z.object({
      org: z.string().describe("org"),
      migration_id: z.string().describe("migration_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("DELETE", `/orgs/${args.org}/migrations/${args.migration_id}/archive`, undefined, undefined);
    },
  },
  {
    name: "github_migrations_unlock_repo_for_org",
    description: "Unlock an organization repository",
    inputSchema: z.object({
      org: z.string().describe("org"),
      migration_id: z.string().describe("migration_id"),
      repo_name: z.string().describe("repo_name")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("DELETE", `/orgs/${args.org}/migrations/${args.migration_id}/repos/${args.repo_name}/lock`, undefined, undefined);
    },
  },
  {
    name: "github_migrations_list_repos_for_org",
    description: "List repositories in an organization migration",
    inputSchema: z.object({
      org: z.string().describe("org"),
      migration_id: z.string().describe("migration_id"),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/migrations/${args.migration_id}/repositories`, undefined, { per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_migrations_get_import_status",
    description: "Get an import status",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/import`, undefined, undefined);
    },
  },
  {
    name: "github_migrations_start_import",
    description: "Start an import",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("PUT", `/repos/${args.owner}/${args.repo}/import`, args.body, undefined);
    },
  },
  {
    name: "github_migrations_update_import",
    description: "Update an import",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("PATCH", `/repos/${args.owner}/${args.repo}/import`, args.body, undefined);
    },
  },
  {
    name: "github_migrations_cancel_import",
    description: "Cancel an import",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("DELETE", `/repos/${args.owner}/${args.repo}/import`, undefined, undefined);
    },
  },
  {
    name: "github_migrations_get_commit_authors",
    description: "Get commit authors",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      since: z.number().optional().describe("A user ID. Only return users with an ID greater than this ID.")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/import/authors`, undefined, { since: args.since });
    },
  },
  {
    name: "github_migrations_map_commit_author",
    description: "Map a commit author",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      author_id: z.string().describe("author_id"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("PATCH", `/repos/${args.owner}/${args.repo}/import/authors/${args.author_id}`, args.body, undefined);
    },
  },
  {
    name: "github_migrations_get_large_files",
    description: "Get large files",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/import/large_files`, undefined, undefined);
    },
  },
  {
    name: "github_migrations_set_lfs_preference",
    description: "Update Git LFS preference",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("PATCH", `/repos/${args.owner}/${args.repo}/import/lfs`, args.body, undefined);
    },
  },
  {
    name: "github_migrations_list_for_authenticated_user",
    description: "List user migrations",
    inputSchema: z.object({
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/user/migrations`, undefined, { per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_migrations_start_for_authenticated_user",
    description: "Start a user migration",
    inputSchema: z.object({
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/user/migrations`, args.body, undefined);
    },
  },
  {
    name: "github_migrations_get_status_for_authenticated_user",
    description: "Get a user migration status",
    inputSchema: z.object({
      migration_id: z.string().describe("migration_id"),
      exclude: z.array(z.string()).optional().describe("exclude")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/user/migrations/${args.migration_id}`, undefined, { exclude: args.exclude });
    },
  },
  {
    name: "github_migrations_get_archive_for_authenticated_user",
    description: "Download a user migration archive",
    inputSchema: z.object({
      migration_id: z.string().describe("migration_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/user/migrations/${args.migration_id}/archive`, undefined, undefined);
    },
  },
  {
    name: "github_migrations_delete_archive_for_authenticated_user",
    description: "Delete a user migration archive",
    inputSchema: z.object({
      migration_id: z.string().describe("migration_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("DELETE", `/user/migrations/${args.migration_id}/archive`, undefined, undefined);
    },
  },
  {
    name: "github_migrations_unlock_repo_for_authenticated_user",
    description: "Unlock a user repository",
    inputSchema: z.object({
      migration_id: z.string().describe("migration_id"),
      repo_name: z.string().describe("repo_name")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("DELETE", `/user/migrations/${args.migration_id}/repos/${args.repo_name}/lock`, undefined, undefined);
    },
  },
  {
    name: "github_migrations_list_repos_for_authenticated_user",
    description: "List repositories for a user migration",
    inputSchema: z.object({
      migration_id: z.string().describe("migration_id"),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/user/migrations/${args.migration_id}/repositories`, undefined, { per_page: args.per_page, page: args.page });
    },
  },
];
