// AUTO-GENERATED by scripts/generate.ts — DO NOT EDIT
import { z } from "zod";
import { githubRequest } from "../client.js";

export const oidcTools = [
  {
    name: "github_oidc_list_oidc_custom_property_inclusions_for_enterprise",
    description: "List OIDC custom property inclusions for an enterprise",
    inputSchema: z.object({
      enterprise: z.string().describe("enterprise")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/enterprises/${args.enterprise}/actions/oidc/customization/properties/repo`, undefined, undefined);
    },
  },
  {
    name: "github_oidc_create_oidc_custom_property_inclusion_for_enterprise",
    description: "Create an OIDC custom property inclusion for an enterprise",
    inputSchema: z.object({
      enterprise: z.string().describe("enterprise"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/enterprises/${args.enterprise}/actions/oidc/customization/properties/repo`, args.body, undefined);
    },
  },
  {
    name: "github_oidc_delete_oidc_custom_property_inclusion_for_enterprise",
    description: "Delete an OIDC custom property inclusion for an enterprise",
    inputSchema: z.object({
      enterprise: z.string().describe("enterprise"),
      custom_property_name: z.string().describe("custom_property_name")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("DELETE", `/enterprises/${args.enterprise}/actions/oidc/customization/properties/repo/${args.custom_property_name}`, undefined, undefined);
    },
  },
  {
    name: "github_oidc_list_oidc_custom_property_inclusions_for_org",
    description: "List OIDC custom property inclusions for an organization",
    inputSchema: z.object({
      org: z.string().describe("org")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/actions/oidc/customization/properties/repo`, undefined, undefined);
    },
  },
  {
    name: "github_oidc_create_oidc_custom_property_inclusion_for_org",
    description: "Create an OIDC custom property inclusion for an organization",
    inputSchema: z.object({
      org: z.string().describe("org"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/orgs/${args.org}/actions/oidc/customization/properties/repo`, args.body, undefined);
    },
  },
  {
    name: "github_oidc_delete_oidc_custom_property_inclusion_for_org",
    description: "Delete an OIDC custom property inclusion for an organization",
    inputSchema: z.object({
      org: z.string().describe("org"),
      custom_property_name: z.string().describe("custom_property_name")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("DELETE", `/orgs/${args.org}/actions/oidc/customization/properties/repo/${args.custom_property_name}`, undefined, undefined);
    },
  },
  {
    name: "github_oidc_get_oidc_custom_sub_template_for_org",
    description: "Get the customization template for an OIDC subject claim for an organization",
    inputSchema: z.object({
      org: z.string().describe("org")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/actions/oidc/customization/sub`, undefined, undefined);
    },
  },
  {
    name: "github_oidc_update_oidc_custom_sub_template_for_org",
    description: "Set the customization template for an OIDC subject claim for an organization",
    inputSchema: z.object({
      org: z.string().describe("org"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("PUT", `/orgs/${args.org}/actions/oidc/customization/sub`, args.body, undefined);
    },
  },
];
