// AUTO-GENERATED by scripts/generate.ts — DO NOT EDIT
import { z } from "zod";
import { githubRequest } from "../client.js";

export const orgsTools = [
  {
    name: "github_orgs_list",
    description: "List organizations",
    inputSchema: z.object({
      since: z.number().optional().describe("An organization ID. Only return organizations with an ID greater than this ID."),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/organizations`, undefined, { since: args.since, per_page: args.per_page });
    },
  },
  {
    name: "github_orgs_get",
    description: "Get an organization",
    inputSchema: z.object({
      org: z.string().describe("org")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}`, undefined, undefined);
    },
  },
  {
    name: "github_orgs_update",
    description: "Update an organization",
    inputSchema: z.object({
      org: z.string().describe("org"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("PATCH", `/orgs/${args.org}`, args.body, undefined);
    },
  },
  {
    name: "github_orgs_delete",
    description: "Delete an organization",
    inputSchema: z.object({
      org: z.string().describe("org")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("DELETE", `/orgs/${args.org}`, undefined, undefined);
    },
  },
  {
    name: "github_orgs_create_artifact_deployment_record",
    description: "Create an artifact deployment record",
    inputSchema: z.object({
      org: z.string().describe("org"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/orgs/${args.org}/artifacts/metadata/deployment-record`, args.body, undefined);
    },
  },
  {
    name: "github_orgs_set_cluster_deployment_records",
    description: "Set cluster deployment records",
    inputSchema: z.object({
      org: z.string().describe("org"),
      cluster: z.string().describe("cluster"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/orgs/${args.org}/artifacts/metadata/deployment-record/cluster/${args.cluster}`, args.body, undefined);
    },
  },
  {
    name: "github_orgs_create_artifact_storage_record",
    description: "Create artifact metadata storage record",
    inputSchema: z.object({
      org: z.string().describe("org"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/orgs/${args.org}/artifacts/metadata/storage-record`, args.body, undefined);
    },
  },
  {
    name: "github_orgs_list_artifact_deployment_records",
    description: "List artifact deployment records",
    inputSchema: z.object({
      org: z.string().describe("org"),
      subject_digest: z.string().describe("subject_digest")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/artifacts/${args.subject_digest}/metadata/deployment-records`, undefined, undefined);
    },
  },
  {
    name: "github_orgs_list_artifact_storage_records",
    description: "List artifact storage records",
    inputSchema: z.object({
      org: z.string().describe("org"),
      subject_digest: z.string().describe("subject_digest")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/artifacts/${args.subject_digest}/metadata/storage-records`, undefined, undefined);
    },
  },
  {
    name: "github_orgs_list_attestations_bulk",
    description: "List attestations by bulk subject digests",
    inputSchema: z.object({
      org: z.string().describe("org"),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      before: z.string().optional().describe("A cursor, as given in the [Link header](https://docs.github.com/rest/guides/using-pagination-in-the-rest-api#using-link-headers). If specified, the query only searches for results before this cursor. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      after: z.string().optional().describe("A cursor, as given in the [Link header](https://docs.github.com/rest/guides/using-pagination-in-the-rest-api#using-link-headers). If specified, the query only searches for results after this cursor. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/orgs/${args.org}/attestations/bulk-list`, args.body, { per_page: args.per_page, before: args.before, after: args.after });
    },
  },
  {
    name: "github_orgs_delete_attestations_bulk",
    description: "Delete attestations in bulk",
    inputSchema: z.object({
      org: z.string().describe("org"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/orgs/${args.org}/attestations/delete-request`, args.body, undefined);
    },
  },
  {
    name: "github_orgs_delete_attestations_by_subject_digest",
    description: "Delete attestations by subject digest",
    inputSchema: z.object({
      org: z.string().describe("org"),
      subject_digest: z.string().describe("subject_digest")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("DELETE", `/orgs/${args.org}/attestations/digest/${args.subject_digest}`, undefined, undefined);
    },
  },
  {
    name: "github_orgs_list_attestation_repositories",
    description: "List attestation repositories",
    inputSchema: z.object({
      org: z.string().describe("org"),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      before: z.string().optional().describe("A cursor, as given in the [Link header](https://docs.github.com/rest/guides/using-pagination-in-the-rest-api#using-link-headers). If specified, the query only searches for results before this cursor. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      after: z.string().optional().describe("A cursor, as given in the [Link header](https://docs.github.com/rest/guides/using-pagination-in-the-rest-api#using-link-headers). If specified, the query only searches for results after this cursor. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      predicate_type: z.string().optional().describe("Optional filter for fetching attestations with a given predicate type. This option accepts `provenance`, `sbom`, `release`, or freeform text for custom predicate types.")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/attestations/repositories`, undefined, { per_page: args.per_page, before: args.before, after: args.after, predicate_type: args.predicate_type });
    },
  },
  {
    name: "github_orgs_delete_attestations_by_id",
    description: "Delete attestations by ID",
    inputSchema: z.object({
      org: z.string().describe("org"),
      attestation_id: z.string().describe("attestation_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("DELETE", `/orgs/${args.org}/attestations/${args.attestation_id}`, undefined, undefined);
    },
  },
  {
    name: "github_orgs_list_attestations",
    description: "List attestations",
    inputSchema: z.object({
      org: z.string().describe("org"),
      subject_digest: z.string().describe("subject_digest"),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      before: z.string().optional().describe("A cursor, as given in the [Link header](https://docs.github.com/rest/guides/using-pagination-in-the-rest-api#using-link-headers). If specified, the query only searches for results before this cursor. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      after: z.string().optional().describe("A cursor, as given in the [Link header](https://docs.github.com/rest/guides/using-pagination-in-the-rest-api#using-link-headers). If specified, the query only searches for results after this cursor. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      predicate_type: z.string().optional().describe("Optional filter for fetching attestations with a given predicate type. This option accepts `provenance`, `sbom`, `release`, or freeform text for custom predicate types.")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/attestations/${args.subject_digest}`, undefined, { per_page: args.per_page, before: args.before, after: args.after, predicate_type: args.predicate_type });
    },
  },
  {
    name: "github_orgs_list_blocked_users",
    description: "List users blocked by an organization",
    inputSchema: z.object({
      org: z.string().describe("org"),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/blocks`, undefined, { per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_orgs_check_blocked_user",
    description: "Check if a user is blocked by an organization",
    inputSchema: z.object({
      org: z.string().describe("org"),
      username: z.string().describe("username")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/blocks/${args.username}`, undefined, undefined);
    },
  },
  {
    name: "github_orgs_block_user",
    description: "Block a user from an organization",
    inputSchema: z.object({
      org: z.string().describe("org"),
      username: z.string().describe("username")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("PUT", `/orgs/${args.org}/blocks/${args.username}`, undefined, undefined);
    },
  },
  {
    name: "github_orgs_unblock_user",
    description: "Unblock a user from an organization",
    inputSchema: z.object({
      org: z.string().describe("org"),
      username: z.string().describe("username")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("DELETE", `/orgs/${args.org}/blocks/${args.username}`, undefined, undefined);
    },
  },
  {
    name: "github_orgs_list_failed_invitations",
    description: "List failed organization invitations",
    inputSchema: z.object({
      org: z.string().describe("org"),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/failed_invitations`, undefined, { per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_orgs_list_webhooks",
    description: "List organization webhooks",
    inputSchema: z.object({
      org: z.string().describe("org"),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/hooks`, undefined, { per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_orgs_create_webhook",
    description: "Create an organization webhook",
    inputSchema: z.object({
      org: z.string().describe("org"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/orgs/${args.org}/hooks`, args.body, undefined);
    },
  },
  {
    name: "github_orgs_get_webhook",
    description: "Get an organization webhook",
    inputSchema: z.object({
      org: z.string().describe("org"),
      hook_id: z.string().describe("hook_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/hooks/${args.hook_id}`, undefined, undefined);
    },
  },
  {
    name: "github_orgs_update_webhook",
    description: "Update an organization webhook",
    inputSchema: z.object({
      org: z.string().describe("org"),
      hook_id: z.string().describe("hook_id"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("PATCH", `/orgs/${args.org}/hooks/${args.hook_id}`, args.body, undefined);
    },
  },
  {
    name: "github_orgs_delete_webhook",
    description: "Delete an organization webhook",
    inputSchema: z.object({
      org: z.string().describe("org"),
      hook_id: z.string().describe("hook_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("DELETE", `/orgs/${args.org}/hooks/${args.hook_id}`, undefined, undefined);
    },
  },
  {
    name: "github_orgs_get_webhook_config_for_org",
    description: "Get a webhook configuration for an organization",
    inputSchema: z.object({
      org: z.string().describe("org"),
      hook_id: z.string().describe("hook_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/hooks/${args.hook_id}/config`, undefined, undefined);
    },
  },
  {
    name: "github_orgs_update_webhook_config_for_org",
    description: "Update a webhook configuration for an organization",
    inputSchema: z.object({
      org: z.string().describe("org"),
      hook_id: z.string().describe("hook_id"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("PATCH", `/orgs/${args.org}/hooks/${args.hook_id}/config`, args.body, undefined);
    },
  },
  {
    name: "github_orgs_list_webhook_deliveries",
    description: "List deliveries for an organization webhook",
    inputSchema: z.object({
      org: z.string().describe("org"),
      hook_id: z.string().describe("hook_id"),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      cursor: z.string().optional().describe("Used for pagination: the starting delivery from which the page of deliveries is fetched. Refer to the `link` header for the next and previous page cursors."),
      status: z.enum(["success", "failure"]).optional().describe("Returns webhook deliveries filtered by delivery outcome classification based on `status_code` range. A `status` of `success` returns deliveries with a `status_code` in the 200-399 range (inclusive). A `status` of `failure` returns deliveries with a `status_code` in the 400-599 range (inclusive).")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/hooks/${args.hook_id}/deliveries`, undefined, { per_page: args.per_page, cursor: args.cursor, status: args.status });
    },
  },
  {
    name: "github_orgs_get_webhook_delivery",
    description: "Get a webhook delivery for an organization webhook",
    inputSchema: z.object({
      org: z.string().describe("org"),
      hook_id: z.string().describe("hook_id"),
      delivery_id: z.string().describe("delivery_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/hooks/${args.hook_id}/deliveries/${args.delivery_id}`, undefined, undefined);
    },
  },
  {
    name: "github_orgs_redeliver_webhook_delivery",
    description: "Redeliver a delivery for an organization webhook",
    inputSchema: z.object({
      org: z.string().describe("org"),
      hook_id: z.string().describe("hook_id"),
      delivery_id: z.string().describe("delivery_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/orgs/${args.org}/hooks/${args.hook_id}/deliveries/${args.delivery_id}/attempts`, undefined, undefined);
    },
  },
  {
    name: "github_orgs_ping_webhook",
    description: "Ping an organization webhook",
    inputSchema: z.object({
      org: z.string().describe("org"),
      hook_id: z.string().describe("hook_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/orgs/${args.org}/hooks/${args.hook_id}/pings`, undefined, undefined);
    },
  },
  {
    name: "github_api_insights_get_route_stats_by_actor",
    description: "Get route stats by actor",
    inputSchema: z.object({
      org: z.string().describe("org"),
      actor_type: z.string().describe("actor_type"),
      actor_id: z.string().describe("actor_id"),
      min_timestamp: z.string().describe("The minimum timestamp to query for stats. This is a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ`."),
      max_timestamp: z.string().optional().describe("The maximum timestamp to query for stats. Defaults to the time 30 days ago. This is a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ`."),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      direction: z.enum(["asc", "desc"]).optional().describe("The direction to sort the results by."),
      sort: z.array(z.enum(["last_rate_limited_timestamp", "last_request_timestamp", "rate_limited_request_count", "http_method", "api_route", "total_request_count"])).optional().describe("The property to sort the results by."),
      api_route_substring: z.string().optional().describe("Providing a substring will filter results where the API route contains the substring. This is a case-insensitive search.")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/insights/api/route-stats/${args.actor_type}/${args.actor_id}`, undefined, { min_timestamp: args.min_timestamp, max_timestamp: args.max_timestamp, page: args.page, per_page: args.per_page, direction: args.direction, sort: args.sort, api_route_substring: args.api_route_substring });
    },
  },
  {
    name: "github_api_insights_get_subject_stats",
    description: "Get subject stats",
    inputSchema: z.object({
      org: z.string().describe("org"),
      min_timestamp: z.string().describe("The minimum timestamp to query for stats. This is a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ`."),
      max_timestamp: z.string().optional().describe("The maximum timestamp to query for stats. Defaults to the time 30 days ago. This is a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ`."),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      direction: z.enum(["asc", "desc"]).optional().describe("The direction to sort the results by."),
      sort: z.array(z.enum(["last_rate_limited_timestamp", "last_request_timestamp", "rate_limited_request_count", "subject_name", "total_request_count"])).optional().describe("The property to sort the results by."),
      subject_name_substring: z.string().optional().describe("Providing a substring will filter results where the subject name contains the substring. This is a case-insensitive search.")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/insights/api/subject-stats`, undefined, { min_timestamp: args.min_timestamp, max_timestamp: args.max_timestamp, page: args.page, per_page: args.per_page, direction: args.direction, sort: args.sort, subject_name_substring: args.subject_name_substring });
    },
  },
  {
    name: "github_api_insights_get_summary_stats",
    description: "Get summary stats",
    inputSchema: z.object({
      org: z.string().describe("org"),
      min_timestamp: z.string().describe("The minimum timestamp to query for stats. This is a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ`."),
      max_timestamp: z.string().optional().describe("The maximum timestamp to query for stats. Defaults to the time 30 days ago. This is a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ`.")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/insights/api/summary-stats`, undefined, { min_timestamp: args.min_timestamp, max_timestamp: args.max_timestamp });
    },
  },
  {
    name: "github_api_insights_get_summary_stats_by_user",
    description: "Get summary stats by user",
    inputSchema: z.object({
      org: z.string().describe("org"),
      user_id: z.string().describe("user_id"),
      min_timestamp: z.string().describe("The minimum timestamp to query for stats. This is a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ`."),
      max_timestamp: z.string().optional().describe("The maximum timestamp to query for stats. Defaults to the time 30 days ago. This is a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ`.")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/insights/api/summary-stats/users/${args.user_id}`, undefined, { min_timestamp: args.min_timestamp, max_timestamp: args.max_timestamp });
    },
  },
  {
    name: "github_api_insights_get_summary_stats_by_actor",
    description: "Get summary stats by actor",
    inputSchema: z.object({
      org: z.string().describe("org"),
      actor_type: z.string().describe("actor_type"),
      actor_id: z.string().describe("actor_id"),
      min_timestamp: z.string().describe("The minimum timestamp to query for stats. This is a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ`."),
      max_timestamp: z.string().optional().describe("The maximum timestamp to query for stats. Defaults to the time 30 days ago. This is a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ`.")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/insights/api/summary-stats/${args.actor_type}/${args.actor_id}`, undefined, { min_timestamp: args.min_timestamp, max_timestamp: args.max_timestamp });
    },
  },
  {
    name: "github_api_insights_get_time_stats",
    description: "Get time stats",
    inputSchema: z.object({
      org: z.string().describe("org"),
      min_timestamp: z.string().describe("The minimum timestamp to query for stats. This is a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ`."),
      max_timestamp: z.string().optional().describe("The maximum timestamp to query for stats. Defaults to the time 30 days ago. This is a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ`."),
      timestamp_increment: z.string().describe("The increment of time used to breakdown the query results (5m, 10m, 1h, etc.)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/insights/api/time-stats`, undefined, { min_timestamp: args.min_timestamp, max_timestamp: args.max_timestamp, timestamp_increment: args.timestamp_increment });
    },
  },
  {
    name: "github_api_insights_get_time_stats_by_user",
    description: "Get time stats by user",
    inputSchema: z.object({
      org: z.string().describe("org"),
      user_id: z.string().describe("user_id"),
      min_timestamp: z.string().describe("The minimum timestamp to query for stats. This is a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ`."),
      max_timestamp: z.string().optional().describe("The maximum timestamp to query for stats. Defaults to the time 30 days ago. This is a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ`."),
      timestamp_increment: z.string().describe("The increment of time used to breakdown the query results (5m, 10m, 1h, etc.)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/insights/api/time-stats/users/${args.user_id}`, undefined, { min_timestamp: args.min_timestamp, max_timestamp: args.max_timestamp, timestamp_increment: args.timestamp_increment });
    },
  },
  {
    name: "github_api_insights_get_time_stats_by_actor",
    description: "Get time stats by actor",
    inputSchema: z.object({
      org: z.string().describe("org"),
      actor_type: z.string().describe("actor_type"),
      actor_id: z.string().describe("actor_id"),
      min_timestamp: z.string().describe("The minimum timestamp to query for stats. This is a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ`."),
      max_timestamp: z.string().optional().describe("The maximum timestamp to query for stats. Defaults to the time 30 days ago. This is a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ`."),
      timestamp_increment: z.string().describe("The increment of time used to breakdown the query results (5m, 10m, 1h, etc.)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/insights/api/time-stats/${args.actor_type}/${args.actor_id}`, undefined, { min_timestamp: args.min_timestamp, max_timestamp: args.max_timestamp, timestamp_increment: args.timestamp_increment });
    },
  },
  {
    name: "github_api_insights_get_user_stats",
    description: "Get user stats",
    inputSchema: z.object({
      org: z.string().describe("org"),
      user_id: z.string().describe("user_id"),
      min_timestamp: z.string().describe("The minimum timestamp to query for stats. This is a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ`."),
      max_timestamp: z.string().optional().describe("The maximum timestamp to query for stats. Defaults to the time 30 days ago. This is a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ`."),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      direction: z.enum(["asc", "desc"]).optional().describe("The direction to sort the results by."),
      sort: z.array(z.enum(["last_rate_limited_timestamp", "last_request_timestamp", "rate_limited_request_count", "subject_name", "total_request_count"])).optional().describe("The property to sort the results by."),
      actor_name_substring: z.string().optional().describe("Providing a substring will filter results where the actor name contains the substring. This is a case-insensitive search.")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/insights/api/user-stats/${args.user_id}`, undefined, { min_timestamp: args.min_timestamp, max_timestamp: args.max_timestamp, page: args.page, per_page: args.per_page, direction: args.direction, sort: args.sort, actor_name_substring: args.actor_name_substring });
    },
  },
  {
    name: "github_orgs_list_app_installations",
    description: "List app installations for an organization",
    inputSchema: z.object({
      org: z.string().describe("org"),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/installations`, undefined, { per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_orgs_list_pending_invitations",
    description: "List pending organization invitations",
    inputSchema: z.object({
      org: z.string().describe("org"),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      role: z.enum(["all", "admin", "direct_member", "billing_manager", "hiring_manager"]).optional().describe("Filter invitations by their member role."),
      invitation_source: z.enum(["all", "member", "scim"]).optional().describe("Filter invitations by their invitation source.")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/invitations`, undefined, { per_page: args.per_page, page: args.page, role: args.role, invitation_source: args.invitation_source });
    },
  },
  {
    name: "github_orgs_create_invitation",
    description: "Create an organization invitation",
    inputSchema: z.object({
      org: z.string().describe("org"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/orgs/${args.org}/invitations`, args.body, undefined);
    },
  },
  {
    name: "github_orgs_cancel_invitation",
    description: "Cancel an organization invitation",
    inputSchema: z.object({
      org: z.string().describe("org"),
      invitation_id: z.string().describe("invitation_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("DELETE", `/orgs/${args.org}/invitations/${args.invitation_id}`, undefined, undefined);
    },
  },
  {
    name: "github_orgs_list_invitation_teams",
    description: "List organization invitation teams",
    inputSchema: z.object({
      org: z.string().describe("org"),
      invitation_id: z.string().describe("invitation_id"),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/invitations/${args.invitation_id}/teams`, undefined, { per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_orgs_list_issue_fields",
    description: "List issue fields for an organization",
    inputSchema: z.object({
      org: z.string().describe("org")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/issue-fields`, undefined, undefined);
    },
  },
  {
    name: "github_orgs_create_issue_field",
    description: "Create issue field for an organization",
    inputSchema: z.object({
      org: z.string().describe("org"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/orgs/${args.org}/issue-fields`, args.body, undefined);
    },
  },
  {
    name: "github_orgs_update_issue_field",
    description: "Update issue field for an organization",
    inputSchema: z.object({
      org: z.string().describe("org"),
      issue_field_id: z.string().describe("issue_field_id"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("PATCH", `/orgs/${args.org}/issue-fields/${args.issue_field_id}`, args.body, undefined);
    },
  },
  {
    name: "github_orgs_delete_issue_field",
    description: "Delete issue field for an organization",
    inputSchema: z.object({
      org: z.string().describe("org"),
      issue_field_id: z.string().describe("issue_field_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("DELETE", `/orgs/${args.org}/issue-fields/${args.issue_field_id}`, undefined, undefined);
    },
  },
  {
    name: "github_orgs_list_issue_types",
    description: "List issue types for an organization",
    inputSchema: z.object({
      org: z.string().describe("org")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/issue-types`, undefined, undefined);
    },
  },
  {
    name: "github_orgs_create_issue_type",
    description: "Create issue type for an organization",
    inputSchema: z.object({
      org: z.string().describe("org"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/orgs/${args.org}/issue-types`, args.body, undefined);
    },
  },
  {
    name: "github_orgs_update_issue_type",
    description: "Update issue type for an organization",
    inputSchema: z.object({
      org: z.string().describe("org"),
      issue_type_id: z.string().describe("issue_type_id"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("PUT", `/orgs/${args.org}/issue-types/${args.issue_type_id}`, args.body, undefined);
    },
  },
  {
    name: "github_orgs_delete_issue_type",
    description: "Delete issue type for an organization",
    inputSchema: z.object({
      org: z.string().describe("org"),
      issue_type_id: z.string().describe("issue_type_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("DELETE", `/orgs/${args.org}/issue-types/${args.issue_type_id}`, undefined, undefined);
    },
  },
  {
    name: "github_orgs_list_members",
    description: "List organization members",
    inputSchema: z.object({
      org: z.string().describe("org"),
      filter: z.enum(["2fa_disabled", "2fa_insecure", "all"]).optional().describe("Filter members returned in the list. `2fa_disabled` means that only members without [two-factor authentication](https://github.com/blog/1614-two-factor-authentication) enabled will be returned. `2fa_insecure` means that only members with [insecure 2FA methods](https://docs.github.com/organizations/keeping-your-organization-secure/managing-two-factor-authentication-for-your-organization/requiring-two-factor-authentication-in-your-organization#requiring-secure-methods-of-two-factor-authentication-in-your-organization) will be returned. These options are only available for organization owners."),
      role: z.enum(["all", "admin", "member"]).optional().describe("Filter members returned by their role."),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/members`, undefined, { filter: args.filter, role: args.role, per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_orgs_check_membership_for_user",
    description: "Check organization membership for a user",
    inputSchema: z.object({
      org: z.string().describe("org"),
      username: z.string().describe("username")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/members/${args.username}`, undefined, undefined);
    },
  },
  {
    name: "github_orgs_remove_member",
    description: "Remove an organization member",
    inputSchema: z.object({
      org: z.string().describe("org"),
      username: z.string().describe("username")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("DELETE", `/orgs/${args.org}/members/${args.username}`, undefined, undefined);
    },
  },
  {
    name: "github_orgs_get_membership_for_user",
    description: "Get organization membership for a user",
    inputSchema: z.object({
      org: z.string().describe("org"),
      username: z.string().describe("username")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/memberships/${args.username}`, undefined, undefined);
    },
  },
  {
    name: "github_orgs_set_membership_for_user",
    description: "Set organization membership for a user",
    inputSchema: z.object({
      org: z.string().describe("org"),
      username: z.string().describe("username"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("PUT", `/orgs/${args.org}/memberships/${args.username}`, args.body, undefined);
    },
  },
  {
    name: "github_orgs_remove_membership_for_user",
    description: "Remove organization membership for a user",
    inputSchema: z.object({
      org: z.string().describe("org"),
      username: z.string().describe("username")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("DELETE", `/orgs/${args.org}/memberships/${args.username}`, undefined, undefined);
    },
  },
  {
    name: "github_orgs_list_org_roles",
    description: "Get all organization roles for an organization",
    inputSchema: z.object({
      org: z.string().describe("org")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/organization-roles`, undefined, undefined);
    },
  },
  {
    name: "github_orgs_revoke_all_org_roles_team",
    description: "Remove all organization roles for a team",
    inputSchema: z.object({
      org: z.string().describe("org"),
      team_slug: z.string().describe("team_slug")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("DELETE", `/orgs/${args.org}/organization-roles/teams/${args.team_slug}`, undefined, undefined);
    },
  },
  {
    name: "github_orgs_assign_team_to_org_role",
    description: "Assign an organization role to a team",
    inputSchema: z.object({
      org: z.string().describe("org"),
      team_slug: z.string().describe("team_slug"),
      role_id: z.string().describe("role_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("PUT", `/orgs/${args.org}/organization-roles/teams/${args.team_slug}/${args.role_id}`, undefined, undefined);
    },
  },
  {
    name: "github_orgs_revoke_org_role_team",
    description: "Remove an organization role from a team",
    inputSchema: z.object({
      org: z.string().describe("org"),
      team_slug: z.string().describe("team_slug"),
      role_id: z.string().describe("role_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("DELETE", `/orgs/${args.org}/organization-roles/teams/${args.team_slug}/${args.role_id}`, undefined, undefined);
    },
  },
  {
    name: "github_orgs_revoke_all_org_roles_user",
    description: "Remove all organization roles for a user",
    inputSchema: z.object({
      org: z.string().describe("org"),
      username: z.string().describe("username")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("DELETE", `/orgs/${args.org}/organization-roles/users/${args.username}`, undefined, undefined);
    },
  },
  {
    name: "github_orgs_assign_user_to_org_role",
    description: "Assign an organization role to a user",
    inputSchema: z.object({
      org: z.string().describe("org"),
      username: z.string().describe("username"),
      role_id: z.string().describe("role_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("PUT", `/orgs/${args.org}/organization-roles/users/${args.username}/${args.role_id}`, undefined, undefined);
    },
  },
  {
    name: "github_orgs_revoke_org_role_user",
    description: "Remove an organization role from a user",
    inputSchema: z.object({
      org: z.string().describe("org"),
      username: z.string().describe("username"),
      role_id: z.string().describe("role_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("DELETE", `/orgs/${args.org}/organization-roles/users/${args.username}/${args.role_id}`, undefined, undefined);
    },
  },
  {
    name: "github_orgs_get_org_role",
    description: "Get an organization role",
    inputSchema: z.object({
      org: z.string().describe("org"),
      role_id: z.string().describe("role_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/organization-roles/${args.role_id}`, undefined, undefined);
    },
  },
  {
    name: "github_orgs_list_org_role_teams",
    description: "List teams that are assigned to an organization role",
    inputSchema: z.object({
      org: z.string().describe("org"),
      role_id: z.string().describe("role_id"),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/organization-roles/${args.role_id}/teams`, undefined, { per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_orgs_list_org_role_users",
    description: "List users that are assigned to an organization role",
    inputSchema: z.object({
      org: z.string().describe("org"),
      role_id: z.string().describe("role_id"),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/organization-roles/${args.role_id}/users`, undefined, { per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_orgs_list_outside_collaborators",
    description: "List outside collaborators for an organization",
    inputSchema: z.object({
      org: z.string().describe("org"),
      filter: z.enum(["2fa_disabled", "2fa_insecure", "all"]).optional().describe("Filter the list of outside collaborators. `2fa_disabled` means that only outside collaborators without [two-factor authentication](https://github.com/blog/1614-two-factor-authentication) enabled will be returned. `2fa_insecure` means that only outside collaborators with [insecure 2FA methods](https://docs.github.com/organizations/keeping-your-organization-secure/managing-two-factor-authentication-for-your-organization/requiring-two-factor-authentication-in-your-organization#requiring-secure-methods-of-two-factor-authentication-in-your-organization) will be returned."),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/outside_collaborators`, undefined, { filter: args.filter, per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_orgs_convert_member_to_outside_collaborator",
    description: "Convert an organization member to outside collaborator",
    inputSchema: z.object({
      org: z.string().describe("org"),
      username: z.string().describe("username"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("PUT", `/orgs/${args.org}/outside_collaborators/${args.username}`, args.body, undefined);
    },
  },
  {
    name: "github_orgs_remove_outside_collaborator",
    description: "Remove outside collaborator from an organization",
    inputSchema: z.object({
      org: z.string().describe("org"),
      username: z.string().describe("username")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("DELETE", `/orgs/${args.org}/outside_collaborators/${args.username}`, undefined, undefined);
    },
  },
  {
    name: "github_orgs_list_pat_grant_requests",
    description: "List requests to access organization resources with fine-grained personal access tokens",
    inputSchema: z.object({
      org: z.string().describe("org"),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      sort: z.enum(["created_at"]).optional().describe("The property by which to sort the results."),
      direction: z.enum(["asc", "desc"]).optional().describe("The direction to sort the results by."),
      owner: z.array(z.string()).optional().describe("A list of owner usernames to use to filter the results."),
      repository: z.string().optional().describe("The name of the repository to use to filter the results."),
      permission: z.string().optional().describe("The permission to use to filter the results."),
      last_used_before: z.string().optional().describe("Only show fine-grained personal access tokens used before the given time. This is a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ`."),
      last_used_after: z.string().optional().describe("Only show fine-grained personal access tokens used after the given time. This is a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ`."),
      token_id: z.array(z.string()).optional().describe("The ID of the token")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/personal-access-token-requests`, undefined, { per_page: args.per_page, page: args.page, sort: args.sort, direction: args.direction, owner: args.owner, repository: args.repository, permission: args.permission, last_used_before: args.last_used_before, last_used_after: args.last_used_after, token_id: args.token_id });
    },
  },
  {
    name: "github_orgs_review_pat_grant_requests_in_bulk",
    description: "Review requests to access organization resources with fine-grained personal access tokens",
    inputSchema: z.object({
      org: z.string().describe("org"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/orgs/${args.org}/personal-access-token-requests`, args.body, undefined);
    },
  },
  {
    name: "github_orgs_review_pat_grant_request",
    description: "Review a request to access organization resources with a fine-grained personal access token",
    inputSchema: z.object({
      org: z.string().describe("org"),
      pat_request_id: z.string().describe("pat_request_id"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/orgs/${args.org}/personal-access-token-requests/${args.pat_request_id}`, args.body, undefined);
    },
  },
  {
    name: "github_orgs_list_pat_grant_request_repositories",
    description: "List repositories requested to be accessed by a fine-grained personal access token",
    inputSchema: z.object({
      org: z.string().describe("org"),
      pat_request_id: z.string().describe("pat_request_id"),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/personal-access-token-requests/${args.pat_request_id}/repositories`, undefined, { per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_orgs_list_pat_grants",
    description: "List fine-grained personal access tokens with access to organization resources",
    inputSchema: z.object({
      org: z.string().describe("org"),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      sort: z.enum(["created_at"]).optional().describe("The property by which to sort the results."),
      direction: z.enum(["asc", "desc"]).optional().describe("The direction to sort the results by."),
      owner: z.array(z.string()).optional().describe("A list of owner usernames to use to filter the results."),
      repository: z.string().optional().describe("The name of the repository to use to filter the results."),
      permission: z.string().optional().describe("The permission to use to filter the results."),
      last_used_before: z.string().optional().describe("Only show fine-grained personal access tokens used before the given time. This is a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ`."),
      last_used_after: z.string().optional().describe("Only show fine-grained personal access tokens used after the given time. This is a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ`."),
      token_id: z.array(z.string()).optional().describe("The ID of the token")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/personal-access-tokens`, undefined, { per_page: args.per_page, page: args.page, sort: args.sort, direction: args.direction, owner: args.owner, repository: args.repository, permission: args.permission, last_used_before: args.last_used_before, last_used_after: args.last_used_after, token_id: args.token_id });
    },
  },
  {
    name: "github_orgs_update_pat_accesses",
    description: "Update the access to organization resources via fine-grained personal access tokens",
    inputSchema: z.object({
      org: z.string().describe("org"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/orgs/${args.org}/personal-access-tokens`, args.body, undefined);
    },
  },
  {
    name: "github_orgs_update_pat_access",
    description: "Update the access a fine-grained personal access token has to organization resources",
    inputSchema: z.object({
      org: z.string().describe("org"),
      pat_id: z.string().describe("pat_id"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/orgs/${args.org}/personal-access-tokens/${args.pat_id}`, args.body, undefined);
    },
  },
  {
    name: "github_orgs_list_pat_grant_repositories",
    description: "List repositories a fine-grained personal access token has access to",
    inputSchema: z.object({
      org: z.string().describe("org"),
      pat_id: z.string().describe("pat_id"),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/personal-access-tokens/${args.pat_id}/repositories`, undefined, { per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_orgs_custom_properties_for_repos_get_organization_definitions",
    description: "Get all custom properties for an organization",
    inputSchema: z.object({
      org: z.string().describe("org")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/properties/schema`, undefined, undefined);
    },
  },
  {
    name: "github_orgs_custom_properties_for_repos_create_or_update_organization_definitions",
    description: "Create or update custom properties for an organization",
    inputSchema: z.object({
      org: z.string().describe("org"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("PATCH", `/orgs/${args.org}/properties/schema`, args.body, undefined);
    },
  },
  {
    name: "github_orgs_custom_properties_for_repos_get_organization_definition",
    description: "Get a custom property for an organization",
    inputSchema: z.object({
      org: z.string().describe("org"),
      custom_property_name: z.string().describe("custom_property_name")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/properties/schema/${args.custom_property_name}`, undefined, undefined);
    },
  },
  {
    name: "github_orgs_custom_properties_for_repos_create_or_update_organization_definition",
    description: "Create or update a custom property for an organization",
    inputSchema: z.object({
      org: z.string().describe("org"),
      custom_property_name: z.string().describe("custom_property_name"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("PUT", `/orgs/${args.org}/properties/schema/${args.custom_property_name}`, args.body, undefined);
    },
  },
  {
    name: "github_orgs_custom_properties_for_repos_delete_organization_definition",
    description: "Remove a custom property for an organization",
    inputSchema: z.object({
      org: z.string().describe("org"),
      custom_property_name: z.string().describe("custom_property_name")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("DELETE", `/orgs/${args.org}/properties/schema/${args.custom_property_name}`, undefined, undefined);
    },
  },
  {
    name: "github_orgs_custom_properties_for_repos_get_organization_values",
    description: "List custom property values for organization repositories",
    inputSchema: z.object({
      org: z.string().describe("org"),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      repository_query: z.string().optional().describe("Finds repositories in the organization with a query containing one or more search keywords and qualifiers. Qualifiers allow you to limit your search to specific areas of GitHub. The REST API supports the same qualifiers as the web interface for GitHub. To learn more about the format of the query, see [Constructing a search query](https://docs.github.com/rest/search/search#constructing-a-search-query). See \"[Searching for repositories](https://docs.github.com/articles/searching-for-repositories/)\" for a detailed list of qualifiers.")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/properties/values`, undefined, { per_page: args.per_page, page: args.page, repository_query: args.repository_query });
    },
  },
  {
    name: "github_orgs_custom_properties_for_repos_create_or_update_organization_values",
    description: "Create or update custom property values for organization repositories",
    inputSchema: z.object({
      org: z.string().describe("org"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("PATCH", `/orgs/${args.org}/properties/values`, args.body, undefined);
    },
  },
  {
    name: "github_orgs_list_public_members",
    description: "List public organization members",
    inputSchema: z.object({
      org: z.string().describe("org"),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/public_members`, undefined, { per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_orgs_check_public_membership_for_user",
    description: "Check public organization membership for a user",
    inputSchema: z.object({
      org: z.string().describe("org"),
      username: z.string().describe("username")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/public_members/${args.username}`, undefined, undefined);
    },
  },
  {
    name: "github_orgs_set_public_membership_for_authenticated_user",
    description: "Set public organization membership for the authenticated user",
    inputSchema: z.object({
      org: z.string().describe("org"),
      username: z.string().describe("username")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("PUT", `/orgs/${args.org}/public_members/${args.username}`, undefined, undefined);
    },
  },
  {
    name: "github_orgs_remove_public_membership_for_authenticated_user",
    description: "Remove public organization membership for the authenticated user",
    inputSchema: z.object({
      org: z.string().describe("org"),
      username: z.string().describe("username")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("DELETE", `/orgs/${args.org}/public_members/${args.username}`, undefined, undefined);
    },
  },
  {
    name: "github_orgs_get_org_ruleset_history",
    description: "Get organization ruleset history",
    inputSchema: z.object({
      org: z.string().describe("org"),
      ruleset_id: z.string().describe("ruleset_id"),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/rulesets/${args.ruleset_id}/history`, undefined, { per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_orgs_get_org_ruleset_version",
    description: "Get organization ruleset version",
    inputSchema: z.object({
      org: z.string().describe("org"),
      ruleset_id: z.string().describe("ruleset_id"),
      version_id: z.string().describe("version_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/rulesets/${args.ruleset_id}/history/${args.version_id}`, undefined, undefined);
    },
  },
  {
    name: "github_orgs_list_security_manager_teams",
    description: "List security manager teams",
    inputSchema: z.object({
      org: z.string().describe("org")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/security-managers`, undefined, undefined);
    },
  },
  {
    name: "github_orgs_add_security_manager_team",
    description: "Add a security manager team",
    inputSchema: z.object({
      org: z.string().describe("org"),
      team_slug: z.string().describe("team_slug")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("PUT", `/orgs/${args.org}/security-managers/teams/${args.team_slug}`, undefined, undefined);
    },
  },
  {
    name: "github_orgs_remove_security_manager_team",
    description: "Remove a security manager team",
    inputSchema: z.object({
      org: z.string().describe("org"),
      team_slug: z.string().describe("team_slug")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("DELETE", `/orgs/${args.org}/security-managers/teams/${args.team_slug}`, undefined, undefined);
    },
  },
  {
    name: "github_orgs_get_immutable_releases_settings",
    description: "Get immutable releases settings for an organization",
    inputSchema: z.object({
      org: z.string().describe("org")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/settings/immutable-releases`, undefined, undefined);
    },
  },
  {
    name: "github_orgs_set_immutable_releases_settings",
    description: "Set immutable releases settings for an organization",
    inputSchema: z.object({
      org: z.string().describe("org"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("PUT", `/orgs/${args.org}/settings/immutable-releases`, args.body, undefined);
    },
  },
  {
    name: "github_orgs_get_immutable_releases_settings_repositories",
    description: "List selected repositories for immutable releases enforcement",
    inputSchema: z.object({
      org: z.string().describe("org"),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/settings/immutable-releases/repositories`, undefined, { page: args.page, per_page: args.per_page });
    },
  },
  {
    name: "github_orgs_set_immutable_releases_settings_repositories",
    description: "Set selected repositories for immutable releases enforcement",
    inputSchema: z.object({
      org: z.string().describe("org"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("PUT", `/orgs/${args.org}/settings/immutable-releases/repositories`, args.body, undefined);
    },
  },
  {
    name: "github_orgs_enable_selected_repository_immutable_releases_organization",
    description: "Enable a selected repository for immutable releases in an organization",
    inputSchema: z.object({
      org: z.string().describe("org"),
      repository_id: z.string().describe("repository_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("PUT", `/orgs/${args.org}/settings/immutable-releases/repositories/${args.repository_id}`, undefined, undefined);
    },
  },
  {
    name: "github_orgs_disable_selected_repository_immutable_releases_organization",
    description: "Disable a selected repository for immutable releases in an organization",
    inputSchema: z.object({
      org: z.string().describe("org"),
      repository_id: z.string().describe("repository_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("DELETE", `/orgs/${args.org}/settings/immutable-releases/repositories/${args.repository_id}`, undefined, undefined);
    },
  },
  {
    name: "github_orgs_enable_or_disable_security_product_on_all_org_repos",
    description: "Enable or disable a security feature for an organization",
    inputSchema: z.object({
      org: z.string().describe("org"),
      security_product: z.string().describe("security_product"),
      enablement: z.string().describe("enablement"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/orgs/${args.org}/${args.security_product}/${args.enablement}`, args.body, undefined);
    },
  },
  {
    name: "github_orgs_list_memberships_for_authenticated_user",
    description: "List organization memberships for the authenticated user",
    inputSchema: z.object({
      state: z.enum(["active", "pending"]).optional().describe("Indicates the state of the memberships to return. If not specified, the API returns both active and pending memberships."),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/user/memberships/orgs`, undefined, { state: args.state, per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_orgs_get_membership_for_authenticated_user",
    description: "Get an organization membership for the authenticated user",
    inputSchema: z.object({
      org: z.string().describe("org")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/user/memberships/orgs/${args.org}`, undefined, undefined);
    },
  },
  {
    name: "github_orgs_update_membership_for_authenticated_user",
    description: "Update an organization membership for the authenticated user",
    inputSchema: z.object({
      org: z.string().describe("org"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("PATCH", `/user/memberships/orgs/${args.org}`, args.body, undefined);
    },
  },
  {
    name: "github_orgs_list_for_authenticated_user",
    description: "List organizations for the authenticated user",
    inputSchema: z.object({
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/user/orgs`, undefined, { per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_orgs_list_for_user",
    description: "List organizations for a user",
    inputSchema: z.object({
      username: z.string().describe("username"),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/users/${args.username}/orgs`, undefined, { per_page: args.per_page, page: args.page });
    },
  },
];
