// AUTO-GENERATED by scripts/generate.ts — DO NOT EDIT
import { z } from "zod";
import { githubRequest } from "../client.js";

export const projectsTools = [
  {
    name: "github_projects_list_for_org",
    description: "List projects for organization",
    inputSchema: z.object({
      org: z.string().describe("org"),
      q: z.string().optional().describe("Limit results to projects of the specified type."),
      before: z.string().optional().describe("A cursor, as given in the [Link header](https://docs.github.com/rest/guides/using-pagination-in-the-rest-api#using-link-headers). If specified, the query only searches for results before this cursor. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      after: z.string().optional().describe("A cursor, as given in the [Link header](https://docs.github.com/rest/guides/using-pagination-in-the-rest-api#using-link-headers). If specified, the query only searches for results after this cursor. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/projectsV2`, undefined, { q: args.q, before: args.before, after: args.after, per_page: args.per_page });
    },
  },
  {
    name: "github_projects_get_for_org",
    description: "Get project for organization",
    inputSchema: z.object({
      org: z.string().describe("org"),
      project_number: z.string().describe("project_number")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/projectsV2/${args.project_number}`, undefined, undefined);
    },
  },
  {
    name: "github_projects_create_draft_item_for_org",
    description: "Create draft item for organization owned project",
    inputSchema: z.object({
      org: z.string().describe("org"),
      project_number: z.string().describe("project_number"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/orgs/${args.org}/projectsV2/${args.project_number}/drafts`, args.body, undefined);
    },
  },
  {
    name: "github_projects_list_fields_for_org",
    description: "List project fields for organization",
    inputSchema: z.object({
      org: z.string().describe("org"),
      project_number: z.string().describe("project_number"),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      before: z.string().optional().describe("A cursor, as given in the [Link header](https://docs.github.com/rest/guides/using-pagination-in-the-rest-api#using-link-headers). If specified, the query only searches for results before this cursor. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      after: z.string().optional().describe("A cursor, as given in the [Link header](https://docs.github.com/rest/guides/using-pagination-in-the-rest-api#using-link-headers). If specified, the query only searches for results after this cursor. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/projectsV2/${args.project_number}/fields`, undefined, { per_page: args.per_page, before: args.before, after: args.after });
    },
  },
  {
    name: "github_projects_add_field_for_org",
    description: "Add a field to an organization-owned project.",
    inputSchema: z.object({
      org: z.string().describe("org"),
      project_number: z.string().describe("project_number"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/orgs/${args.org}/projectsV2/${args.project_number}/fields`, args.body, undefined);
    },
  },
  {
    name: "github_projects_get_field_for_org",
    description: "Get project field for organization",
    inputSchema: z.object({
      org: z.string().describe("org"),
      project_number: z.string().describe("project_number"),
      field_id: z.string().describe("field_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/projectsV2/${args.project_number}/fields/${args.field_id}`, undefined, undefined);
    },
  },
  {
    name: "github_projects_list_items_for_org",
    description: "List items for an organization owned project",
    inputSchema: z.object({
      org: z.string().describe("org"),
      project_number: z.string().describe("project_number"),
      q: z.string().optional().describe("Search query to filter items, see [Filtering projects](https://docs.github.com/issues/planning-and-tracking-with-projects/customizing-views-in-your-project/filtering-projects) for more information."),
      fields: z.unknown().optional().describe("Limit results to specific fields, by their IDs. If not specified, the title field will be returned.  Example: `fields[]=123&fields[]=456&fields[]=789` or `fields=123,456,789`"),
      before: z.string().optional().describe("A cursor, as given in the [Link header](https://docs.github.com/rest/guides/using-pagination-in-the-rest-api#using-link-headers). If specified, the query only searches for results before this cursor. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      after: z.string().optional().describe("A cursor, as given in the [Link header](https://docs.github.com/rest/guides/using-pagination-in-the-rest-api#using-link-headers). If specified, the query only searches for results after this cursor. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/projectsV2/${args.project_number}/items`, undefined, { q: args.q, fields: args.fields, before: args.before, after: args.after, per_page: args.per_page });
    },
  },
  {
    name: "github_projects_add_item_for_org",
    description: "Add item to organization owned project",
    inputSchema: z.object({
      org: z.string().describe("org"),
      project_number: z.string().describe("project_number"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/orgs/${args.org}/projectsV2/${args.project_number}/items`, args.body, undefined);
    },
  },
  {
    name: "github_projects_get_org_item",
    description: "Get an item for an organization owned project",
    inputSchema: z.object({
      org: z.string().describe("org"),
      project_number: z.string().describe("project_number"),
      item_id: z.string().describe("item_id"),
      fields: z.unknown().optional().describe("Limit results to specific fields, by their IDs. If not specified, the title field will be returned.  Example: fields[]=123&fields[]=456&fields[]=789 or fields=123,456,789")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/projectsV2/${args.project_number}/items/${args.item_id}`, undefined, { fields: args.fields });
    },
  },
  {
    name: "github_projects_update_item_for_org",
    description: "Update project item for organization",
    inputSchema: z.object({
      org: z.string().describe("org"),
      project_number: z.string().describe("project_number"),
      item_id: z.string().describe("item_id"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("PATCH", `/orgs/${args.org}/projectsV2/${args.project_number}/items/${args.item_id}`, args.body, undefined);
    },
  },
  {
    name: "github_projects_delete_item_for_org",
    description: "Delete project item for organization",
    inputSchema: z.object({
      org: z.string().describe("org"),
      project_number: z.string().describe("project_number"),
      item_id: z.string().describe("item_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("DELETE", `/orgs/${args.org}/projectsV2/${args.project_number}/items/${args.item_id}`, undefined, undefined);
    },
  },
  {
    name: "github_projects_create_view_for_org",
    description: "Create a view for an organization-owned project",
    inputSchema: z.object({
      org: z.string().describe("org"),
      project_number: z.string().describe("project_number"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/orgs/${args.org}/projectsV2/${args.project_number}/views`, args.body, undefined);
    },
  },
  {
    name: "github_projects_list_view_items_for_org",
    description: "List items for an organization project view",
    inputSchema: z.object({
      org: z.string().describe("org"),
      project_number: z.string().describe("project_number"),
      view_number: z.string().describe("view_number"),
      fields: z.unknown().optional().describe("Limit results to specific fields, by their IDs. If not specified, the title field will be returned.  Example: `fields[]=123&fields[]=456&fields[]=789` or `fields=123,456,789`"),
      before: z.string().optional().describe("A cursor, as given in the [Link header](https://docs.github.com/rest/guides/using-pagination-in-the-rest-api#using-link-headers). If specified, the query only searches for results before this cursor. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      after: z.string().optional().describe("A cursor, as given in the [Link header](https://docs.github.com/rest/guides/using-pagination-in-the-rest-api#using-link-headers). If specified, the query only searches for results after this cursor. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/projectsV2/${args.project_number}/views/${args.view_number}/items`, undefined, { fields: args.fields, before: args.before, after: args.after, per_page: args.per_page });
    },
  },
  {
    name: "github_projects_create_draft_item_for_authenticated_user",
    description: "Create draft item for user owned project",
    inputSchema: z.object({
      user_id: z.string().describe("user_id"),
      project_number: z.string().describe("project_number"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/user/${args.user_id}/projectsV2/${args.project_number}/drafts`, args.body, undefined);
    },
  },
  {
    name: "github_projects_create_view_for_user",
    description: "Create a view for a user-owned project",
    inputSchema: z.object({
      user_id: z.string().describe("user_id"),
      project_number: z.string().describe("project_number"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/users/${args.user_id}/projectsV2/${args.project_number}/views`, args.body, undefined);
    },
  },
  {
    name: "github_projects_list_for_user",
    description: "List projects for user",
    inputSchema: z.object({
      username: z.string().describe("username"),
      q: z.string().optional().describe("Limit results to projects of the specified type."),
      before: z.string().optional().describe("A cursor, as given in the [Link header](https://docs.github.com/rest/guides/using-pagination-in-the-rest-api#using-link-headers). If specified, the query only searches for results before this cursor. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      after: z.string().optional().describe("A cursor, as given in the [Link header](https://docs.github.com/rest/guides/using-pagination-in-the-rest-api#using-link-headers). If specified, the query only searches for results after this cursor. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/users/${args.username}/projectsV2`, undefined, { q: args.q, before: args.before, after: args.after, per_page: args.per_page });
    },
  },
  {
    name: "github_projects_get_for_user",
    description: "Get project for user",
    inputSchema: z.object({
      username: z.string().describe("username"),
      project_number: z.string().describe("project_number")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/users/${args.username}/projectsV2/${args.project_number}`, undefined, undefined);
    },
  },
  {
    name: "github_projects_list_fields_for_user",
    description: "List project fields for user",
    inputSchema: z.object({
      username: z.string().describe("username"),
      project_number: z.string().describe("project_number"),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      before: z.string().optional().describe("A cursor, as given in the [Link header](https://docs.github.com/rest/guides/using-pagination-in-the-rest-api#using-link-headers). If specified, the query only searches for results before this cursor. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      after: z.string().optional().describe("A cursor, as given in the [Link header](https://docs.github.com/rest/guides/using-pagination-in-the-rest-api#using-link-headers). If specified, the query only searches for results after this cursor. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/users/${args.username}/projectsV2/${args.project_number}/fields`, undefined, { per_page: args.per_page, before: args.before, after: args.after });
    },
  },
  {
    name: "github_projects_add_field_for_user",
    description: "Add field to user owned project",
    inputSchema: z.object({
      username: z.string().describe("username"),
      project_number: z.string().describe("project_number"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/users/${args.username}/projectsV2/${args.project_number}/fields`, args.body, undefined);
    },
  },
  {
    name: "github_projects_get_field_for_user",
    description: "Get project field for user",
    inputSchema: z.object({
      username: z.string().describe("username"),
      project_number: z.string().describe("project_number"),
      field_id: z.string().describe("field_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/users/${args.username}/projectsV2/${args.project_number}/fields/${args.field_id}`, undefined, undefined);
    },
  },
  {
    name: "github_projects_list_items_for_user",
    description: "List items for a user owned project",
    inputSchema: z.object({
      username: z.string().describe("username"),
      project_number: z.string().describe("project_number"),
      before: z.string().optional().describe("A cursor, as given in the [Link header](https://docs.github.com/rest/guides/using-pagination-in-the-rest-api#using-link-headers). If specified, the query only searches for results before this cursor. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      after: z.string().optional().describe("A cursor, as given in the [Link header](https://docs.github.com/rest/guides/using-pagination-in-the-rest-api#using-link-headers). If specified, the query only searches for results after this cursor. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      q: z.string().optional().describe("Search query to filter items, see [Filtering projects](https://docs.github.com/issues/planning-and-tracking-with-projects/customizing-views-in-your-project/filtering-projects) for more information."),
      fields: z.unknown().optional().describe("Limit results to specific fields, by their IDs. If not specified, the title field will be returned.  Example: `fields[]=123&fields[]=456&fields[]=789` or `fields=123,456,789`")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/users/${args.username}/projectsV2/${args.project_number}/items`, undefined, { before: args.before, after: args.after, per_page: args.per_page, q: args.q, fields: args.fields });
    },
  },
  {
    name: "github_projects_add_item_for_user",
    description: "Add item to user owned project",
    inputSchema: z.object({
      username: z.string().describe("username"),
      project_number: z.string().describe("project_number"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/users/${args.username}/projectsV2/${args.project_number}/items`, args.body, undefined);
    },
  },
  {
    name: "github_projects_get_user_item",
    description: "Get an item for a user owned project",
    inputSchema: z.object({
      username: z.string().describe("username"),
      project_number: z.string().describe("project_number"),
      item_id: z.string().describe("item_id"),
      fields: z.unknown().optional().describe("Limit results to specific fields, by their IDs. If not specified, the title field will be returned.  Example: fields[]=123&fields[]=456&fields[]=789 or fields=123,456,789")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/users/${args.username}/projectsV2/${args.project_number}/items/${args.item_id}`, undefined, { fields: args.fields });
    },
  },
  {
    name: "github_projects_update_item_for_user",
    description: "Update project item for user",
    inputSchema: z.object({
      username: z.string().describe("username"),
      project_number: z.string().describe("project_number"),
      item_id: z.string().describe("item_id"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("PATCH", `/users/${args.username}/projectsV2/${args.project_number}/items/${args.item_id}`, args.body, undefined);
    },
  },
  {
    name: "github_projects_delete_item_for_user",
    description: "Delete project item for user",
    inputSchema: z.object({
      username: z.string().describe("username"),
      project_number: z.string().describe("project_number"),
      item_id: z.string().describe("item_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("DELETE", `/users/${args.username}/projectsV2/${args.project_number}/items/${args.item_id}`, undefined, undefined);
    },
  },
  {
    name: "github_projects_list_view_items_for_user",
    description: "List items for a user project view",
    inputSchema: z.object({
      username: z.string().describe("username"),
      project_number: z.string().describe("project_number"),
      view_number: z.string().describe("view_number"),
      fields: z.unknown().optional().describe("Limit results to specific fields, by their IDs. If not specified, the title field will be returned.  Example: `fields[]=123&fields[]=456&fields[]=789` or `fields=123,456,789`"),
      before: z.string().optional().describe("A cursor, as given in the [Link header](https://docs.github.com/rest/guides/using-pagination-in-the-rest-api#using-link-headers). If specified, the query only searches for results before this cursor. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      after: z.string().optional().describe("A cursor, as given in the [Link header](https://docs.github.com/rest/guides/using-pagination-in-the-rest-api#using-link-headers). If specified, the query only searches for results after this cursor. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/users/${args.username}/projectsV2/${args.project_number}/views/${args.view_number}/items`, undefined, { fields: args.fields, before: args.before, after: args.after, per_page: args.per_page });
    },
  },
];
