// AUTO-GENERATED by scripts/generate.ts — DO NOT EDIT
import { z } from "zod";
import { githubRequest } from "../client.js";

export const pullsTools = [
  {
    name: "github_pulls_list",
    description: "List pull requests",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      state: z.enum(["open", "closed", "all"]).optional().describe("Either `open`, `closed`, or `all` to filter by state."),
      head: z.string().optional().describe("Filter pulls by head user or head organization and branch name in the format of `user:ref-name` or `organization:ref-name`. For example: `github:new-script-format` or `octocat:test-branch`."),
      base: z.string().optional().describe("Filter pulls by base branch name. Example: `gh-pages`."),
      sort: z.enum(["created", "updated", "popularity", "long-running"]).optional().describe("What to sort results by. `popularity` will sort by the number of comments. `long-running` will sort by date created and will limit the results to pull requests that have been open for more than a month and have had activity within the past month."),
      direction: z.enum(["asc", "desc"]).optional().describe("The direction of the sort. Default: `desc` when sort is `created` or sort is not specified, otherwise `asc`."),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/pulls`, undefined, { state: args.state, head: args.head, base: args.base, sort: args.sort, direction: args.direction, per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_pulls_create",
    description: "Create a pull request",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/repos/${args.owner}/${args.repo}/pulls`, args.body, undefined);
    },
  },
  {
    name: "github_pulls_list_review_comments_for_repo",
    description: "List review comments in a repository",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      sort: z.enum(["created", "updated", "created_at"]).optional().describe("sort"),
      direction: z.enum(["asc", "desc"]).optional().describe("The direction to sort results. Ignored without `sort` parameter."),
      since: z.string().optional().describe("Only show results that were last updated after the given time. This is a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ`."),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/pulls/comments`, undefined, { sort: args.sort, direction: args.direction, since: args.since, per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_pulls_get_review_comment",
    description: "Get a review comment for a pull request",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      comment_id: z.string().describe("comment_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/pulls/comments/${args.comment_id}`, undefined, undefined);
    },
  },
  {
    name: "github_pulls_update_review_comment",
    description: "Update a review comment for a pull request",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      comment_id: z.string().describe("comment_id"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("PATCH", `/repos/${args.owner}/${args.repo}/pulls/comments/${args.comment_id}`, args.body, undefined);
    },
  },
  {
    name: "github_pulls_delete_review_comment",
    description: "Delete a review comment for a pull request",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      comment_id: z.string().describe("comment_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("DELETE", `/repos/${args.owner}/${args.repo}/pulls/comments/${args.comment_id}`, undefined, undefined);
    },
  },
  {
    name: "github_pulls_get",
    description: "Get a pull request",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      pull_number: z.string().describe("pull_number")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/pulls/${args.pull_number}`, undefined, undefined);
    },
  },
  {
    name: "github_pulls_update",
    description: "Update a pull request",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      pull_number: z.string().describe("pull_number"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("PATCH", `/repos/${args.owner}/${args.repo}/pulls/${args.pull_number}`, args.body, undefined);
    },
  },
  {
    name: "github_pulls_list_review_comments",
    description: "List review comments on a pull request",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      pull_number: z.string().describe("pull_number"),
      sort: z.enum(["created", "updated"]).optional().describe("The property to sort the results by."),
      direction: z.enum(["asc", "desc"]).optional().describe("The direction to sort results. Ignored without `sort` parameter."),
      since: z.string().optional().describe("Only show results that were last updated after the given time. This is a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ`."),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/pulls/${args.pull_number}/comments`, undefined, { sort: args.sort, direction: args.direction, since: args.since, per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_pulls_create_review_comment",
    description: "Create a review comment for a pull request",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      pull_number: z.string().describe("pull_number"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/repos/${args.owner}/${args.repo}/pulls/${args.pull_number}/comments`, args.body, undefined);
    },
  },
  {
    name: "github_pulls_create_reply_for_review_comment",
    description: "Create a reply for a review comment",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      pull_number: z.string().describe("pull_number"),
      comment_id: z.string().describe("comment_id"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/repos/${args.owner}/${args.repo}/pulls/${args.pull_number}/comments/${args.comment_id}/replies`, args.body, undefined);
    },
  },
  {
    name: "github_pulls_list_commits",
    description: "List commits on a pull request",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      pull_number: z.string().describe("pull_number"),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/pulls/${args.pull_number}/commits`, undefined, { per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_pulls_list_files",
    description: "List pull requests files",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      pull_number: z.string().describe("pull_number"),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/pulls/${args.pull_number}/files`, undefined, { per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_pulls_check_if_merged",
    description: "Check if a pull request has been merged",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      pull_number: z.string().describe("pull_number")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/pulls/${args.pull_number}/merge`, undefined, undefined);
    },
  },
  {
    name: "github_pulls_merge",
    description: "Merge a pull request",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      pull_number: z.string().describe("pull_number"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("PUT", `/repos/${args.owner}/${args.repo}/pulls/${args.pull_number}/merge`, args.body, undefined);
    },
  },
  {
    name: "github_pulls_list_requested_reviewers",
    description: "Get all requested reviewers for a pull request",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      pull_number: z.string().describe("pull_number")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/pulls/${args.pull_number}/requested_reviewers`, undefined, undefined);
    },
  },
  {
    name: "github_pulls_request_reviewers",
    description: "Request reviewers for a pull request",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      pull_number: z.string().describe("pull_number"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/repos/${args.owner}/${args.repo}/pulls/${args.pull_number}/requested_reviewers`, args.body, undefined);
    },
  },
  {
    name: "github_pulls_remove_requested_reviewers",
    description: "Remove requested reviewers from a pull request",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      pull_number: z.string().describe("pull_number")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("DELETE", `/repos/${args.owner}/${args.repo}/pulls/${args.pull_number}/requested_reviewers`, undefined, undefined);
    },
  },
  {
    name: "github_pulls_list_reviews",
    description: "List reviews for a pull request",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      pull_number: z.string().describe("pull_number"),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/pulls/${args.pull_number}/reviews`, undefined, { per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_pulls_create_review",
    description: "Create a review for a pull request",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      pull_number: z.string().describe("pull_number"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/repos/${args.owner}/${args.repo}/pulls/${args.pull_number}/reviews`, args.body, undefined);
    },
  },
  {
    name: "github_pulls_get_review",
    description: "Get a review for a pull request",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      pull_number: z.string().describe("pull_number"),
      review_id: z.string().describe("review_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/pulls/${args.pull_number}/reviews/${args.review_id}`, undefined, undefined);
    },
  },
  {
    name: "github_pulls_update_review",
    description: "Update a review for a pull request",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      pull_number: z.string().describe("pull_number"),
      review_id: z.string().describe("review_id"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("PUT", `/repos/${args.owner}/${args.repo}/pulls/${args.pull_number}/reviews/${args.review_id}`, args.body, undefined);
    },
  },
  {
    name: "github_pulls_delete_pending_review",
    description: "Delete a pending review for a pull request",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      pull_number: z.string().describe("pull_number"),
      review_id: z.string().describe("review_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("DELETE", `/repos/${args.owner}/${args.repo}/pulls/${args.pull_number}/reviews/${args.review_id}`, undefined, undefined);
    },
  },
  {
    name: "github_pulls_list_comments_for_review",
    description: "List comments for a pull request review",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      pull_number: z.string().describe("pull_number"),
      review_id: z.string().describe("review_id"),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/pulls/${args.pull_number}/reviews/${args.review_id}/comments`, undefined, { per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_pulls_dismiss_review",
    description: "Dismiss a review for a pull request",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      pull_number: z.string().describe("pull_number"),
      review_id: z.string().describe("review_id"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("PUT", `/repos/${args.owner}/${args.repo}/pulls/${args.pull_number}/reviews/${args.review_id}/dismissals`, args.body, undefined);
    },
  },
  {
    name: "github_pulls_submit_review",
    description: "Submit a review for a pull request",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      pull_number: z.string().describe("pull_number"),
      review_id: z.string().describe("review_id"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/repos/${args.owner}/${args.repo}/pulls/${args.pull_number}/reviews/${args.review_id}/events`, args.body, undefined);
    },
  },
  {
    name: "github_pulls_update_branch",
    description: "Update a pull request branch",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      pull_number: z.string().describe("pull_number"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("PUT", `/repos/${args.owner}/${args.repo}/pulls/${args.pull_number}/update-branch`, args.body, undefined);
    },
  },
];
