// AUTO-GENERATED by scripts/generate.ts — DO NOT EDIT
import { z } from "zod";
import { githubRequest } from "../client.js";

export const rateLimitTools = [
  {
    name: "github_rate_limit_get",
    description: "Get rate limit status for the authenticated user",
    inputSchema: z.object({}),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/rate_limit`, undefined, undefined);
    },
  },
];
