// AUTO-GENERATED by scripts/generate.ts — DO NOT EDIT
import { z } from "zod";
import { githubRequest } from "../client.js";

export const reactionsTools = [
  {
    name: "github_reactions_list_for_commit_comment",
    description: "List reactions for a commit comment",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      comment_id: z.string().describe("comment_id"),
      content: z.enum(["+1", "-1", "laugh", "confused", "heart", "hooray", "rocket", "eyes"]).optional().describe("Returns a single [reaction type](https://docs.github.com/rest/reactions/reactions#about-reactions). Omit this parameter to list all reactions to a commit comment."),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/comments/${args.comment_id}/reactions`, undefined, { content: args.content, per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_reactions_create_for_commit_comment",
    description: "Create reaction for a commit comment",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      comment_id: z.string().describe("comment_id"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/repos/${args.owner}/${args.repo}/comments/${args.comment_id}/reactions`, args.body, undefined);
    },
  },
  {
    name: "github_reactions_delete_for_commit_comment",
    description: "Delete a commit comment reaction",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      comment_id: z.string().describe("comment_id"),
      reaction_id: z.string().describe("reaction_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("DELETE", `/repos/${args.owner}/${args.repo}/comments/${args.comment_id}/reactions/${args.reaction_id}`, undefined, undefined);
    },
  },
  {
    name: "github_reactions_list_for_issue_comment",
    description: "List reactions for an issue comment",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      comment_id: z.string().describe("comment_id"),
      content: z.enum(["+1", "-1", "laugh", "confused", "heart", "hooray", "rocket", "eyes"]).optional().describe("Returns a single [reaction type](https://docs.github.com/rest/reactions/reactions#about-reactions). Omit this parameter to list all reactions to an issue comment."),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/issues/comments/${args.comment_id}/reactions`, undefined, { content: args.content, per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_reactions_create_for_issue_comment",
    description: "Create reaction for an issue comment",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      comment_id: z.string().describe("comment_id"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/repos/${args.owner}/${args.repo}/issues/comments/${args.comment_id}/reactions`, args.body, undefined);
    },
  },
  {
    name: "github_reactions_delete_for_issue_comment",
    description: "Delete an issue comment reaction",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      comment_id: z.string().describe("comment_id"),
      reaction_id: z.string().describe("reaction_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("DELETE", `/repos/${args.owner}/${args.repo}/issues/comments/${args.comment_id}/reactions/${args.reaction_id}`, undefined, undefined);
    },
  },
  {
    name: "github_reactions_list_for_issue",
    description: "List reactions for an issue",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      issue_number: z.string().describe("issue_number"),
      content: z.enum(["+1", "-1", "laugh", "confused", "heart", "hooray", "rocket", "eyes"]).optional().describe("Returns a single [reaction type](https://docs.github.com/rest/reactions/reactions#about-reactions). Omit this parameter to list all reactions to an issue."),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/issues/${args.issue_number}/reactions`, undefined, { content: args.content, per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_reactions_create_for_issue",
    description: "Create reaction for an issue",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      issue_number: z.string().describe("issue_number"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/repos/${args.owner}/${args.repo}/issues/${args.issue_number}/reactions`, args.body, undefined);
    },
  },
  {
    name: "github_reactions_delete_for_issue",
    description: "Delete an issue reaction",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      issue_number: z.string().describe("issue_number"),
      reaction_id: z.string().describe("reaction_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("DELETE", `/repos/${args.owner}/${args.repo}/issues/${args.issue_number}/reactions/${args.reaction_id}`, undefined, undefined);
    },
  },
  {
    name: "github_reactions_list_for_pull_request_review_comment",
    description: "List reactions for a pull request review comment",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      comment_id: z.string().describe("comment_id"),
      content: z.enum(["+1", "-1", "laugh", "confused", "heart", "hooray", "rocket", "eyes"]).optional().describe("Returns a single [reaction type](https://docs.github.com/rest/reactions/reactions#about-reactions). Omit this parameter to list all reactions to a pull request review comment."),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/pulls/comments/${args.comment_id}/reactions`, undefined, { content: args.content, per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_reactions_create_for_pull_request_review_comment",
    description: "Create reaction for a pull request review comment",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      comment_id: z.string().describe("comment_id"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/repos/${args.owner}/${args.repo}/pulls/comments/${args.comment_id}/reactions`, args.body, undefined);
    },
  },
  {
    name: "github_reactions_delete_for_pull_request_comment",
    description: "Delete a pull request comment reaction",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      comment_id: z.string().describe("comment_id"),
      reaction_id: z.string().describe("reaction_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("DELETE", `/repos/${args.owner}/${args.repo}/pulls/comments/${args.comment_id}/reactions/${args.reaction_id}`, undefined, undefined);
    },
  },
  {
    name: "github_reactions_list_for_release",
    description: "List reactions for a release",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      release_id: z.string().describe("release_id"),
      content: z.enum(["+1", "laugh", "heart", "hooray", "rocket", "eyes"]).optional().describe("Returns a single [reaction type](https://docs.github.com/rest/reactions/reactions#about-reactions). Omit this parameter to list all reactions to a release."),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/releases/${args.release_id}/reactions`, undefined, { content: args.content, per_page: args.per_page, page: args.page });
    },
  },
  {
    name: "github_reactions_create_for_release",
    description: "Create reaction for a release",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      release_id: z.string().describe("release_id"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/repos/${args.owner}/${args.repo}/releases/${args.release_id}/reactions`, args.body, undefined);
    },
  },
  {
    name: "github_reactions_delete_for_release",
    description: "Delete a release reaction",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      release_id: z.string().describe("release_id"),
      reaction_id: z.string().describe("reaction_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("DELETE", `/repos/${args.owner}/${args.repo}/releases/${args.release_id}/reactions/${args.reaction_id}`, undefined, undefined);
    },
  },
];
