// AUTO-GENERATED by scripts/generate.ts — DO NOT EDIT
import { z } from "zod";
import { githubRequest } from "../client.js";

export const secretScanningTools = [
  {
    name: "github_secret_scanning_list_alerts_for_org",
    description: "List secret scanning alerts for an organization",
    inputSchema: z.object({
      org: z.string().describe("org"),
      state: z.enum(["open", "resolved"]).optional().describe("Set to `open` or `resolved` to only list secret scanning alerts in a specific state."),
      secret_type: z.string().optional().describe("A comma-separated list of secret types to return. All default secret patterns are returned. To return generic patterns, pass the token name(s) in the parameter. See \"[Supported secret scanning patterns](https://docs.github.com/code-security/secret-scanning/introduction/supported-secret-scanning-patterns#supported-secrets)\" for a complete list of secret types."),
      exclude_secret_types: z.string().optional().describe("A comma-separated list of secret types to exclude from the results. All default secret patterns are returned except those matching the specified types. Cannot be combined with the `secret_type` parameter. See \"[Supported secret scanning patterns](https://docs.github.com/code-security/secret-scanning/introduction/supported-secret-scanning-patterns#supported-secrets)\" for a complete list of secret types."),
      exclude_providers: z.string().optional().describe("A comma-separated list of provider slugs to exclude from the results. Provider slugs use lowercase with underscores (e.g., `github_secret_scanning`, `clojars`). You can find the provider slug in the `provider_slug` field of each alert. Cannot be combined with the `providers` parameter."),
      providers: z.string().optional().describe("A comma-separated list of provider slugs to filter by. Provider slugs use lowercase with underscores (e.g., `github_secret_scanning`, `clojars`). You can find the provider slug in the `provider_slug` field of each alert. Cannot be combined with the `exclude_providers` parameter."),
      resolution: z.string().optional().describe("A comma-separated list of resolutions. Only secret scanning alerts with one of these resolutions are listed. Valid resolutions are `false_positive`, `wont_fix`, `revoked`, `pattern_edited`, `pattern_deleted` or `used_in_tests`."),
      assignee: z.string().optional().describe("Filters alerts by assignee. Use `*` to get all assigned alerts, `none` to get all unassigned alerts, or a GitHub username to get alerts assigned to a specific user."),
      sort: z.enum(["created", "updated"]).optional().describe("The property to sort the results by. `created` means when the alert was created. `updated` means when the alert was updated or resolved."),
      direction: z.enum(["asc", "desc"]).optional().describe("The direction to sort the results by."),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      before: z.string().optional().describe("A cursor, as given in the [Link header](https://docs.github.com/rest/guides/using-pagination-in-the-rest-api#using-link-headers). If specified, the query only searches for events before this cursor. To receive an initial cursor on your first request, include an empty \"before\" query string."),
      after: z.string().optional().describe("A cursor, as given in the [Link header](https://docs.github.com/rest/guides/using-pagination-in-the-rest-api#using-link-headers). If specified, the query only searches for events after this cursor.  To receive an initial cursor on your first request, include an empty \"after\" query string."),
      validity: z.string().optional().describe("A comma-separated list of validities that, when present, will return alerts that match the validities in this list. Valid options are `active`, `inactive`, and `unknown`."),
      is_publicly_leaked: z.boolean().optional().describe("A boolean value representing whether or not to filter alerts by the publicly-leaked tag being present."),
      is_multi_repo: z.boolean().optional().describe("A boolean value representing whether or not to filter alerts by the multi-repo tag being present."),
      hide_secret: z.boolean().optional().describe("A boolean value representing whether or not to hide literal secrets in the results.")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/secret-scanning/alerts`, undefined, { state: args.state, secret_type: args.secret_type, exclude_secret_types: args.exclude_secret_types, exclude_providers: args.exclude_providers, providers: args.providers, resolution: args.resolution, assignee: args.assignee, sort: args.sort, direction: args.direction, page: args.page, per_page: args.per_page, before: args.before, after: args.after, validity: args.validity, is_publicly_leaked: args.is_publicly_leaked, is_multi_repo: args.is_multi_repo, hide_secret: args.hide_secret });
    },
  },
  {
    name: "github_secret_scanning_list_org_pattern_configs",
    description: "List organization pattern configurations",
    inputSchema: z.object({
      org: z.string().describe("org")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/secret-scanning/pattern-configurations`, undefined, undefined);
    },
  },
  {
    name: "github_secret_scanning_update_org_pattern_configs",
    description: "Update organization pattern configurations",
    inputSchema: z.object({
      org: z.string().describe("org"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("PATCH", `/orgs/${args.org}/secret-scanning/pattern-configurations`, args.body, undefined);
    },
  },
  {
    name: "github_secret_scanning_list_alerts_for_repo",
    description: "List secret scanning alerts for a repository",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      state: z.enum(["open", "resolved"]).optional().describe("Set to `open` or `resolved` to only list secret scanning alerts in a specific state."),
      secret_type: z.string().optional().describe("A comma-separated list of secret types to return. All default secret patterns are returned. To return generic patterns, pass the token name(s) in the parameter. See \"[Supported secret scanning patterns](https://docs.github.com/code-security/secret-scanning/introduction/supported-secret-scanning-patterns#supported-secrets)\" for a complete list of secret types."),
      exclude_secret_types: z.string().optional().describe("A comma-separated list of secret types to exclude from the results. All default secret patterns are returned except those matching the specified types. Cannot be combined with the `secret_type` parameter. See \"[Supported secret scanning patterns](https://docs.github.com/code-security/secret-scanning/introduction/supported-secret-scanning-patterns#supported-secrets)\" for a complete list of secret types."),
      exclude_providers: z.string().optional().describe("A comma-separated list of provider slugs to exclude from the results. Provider slugs use lowercase with underscores (e.g., `github_secret_scanning`, `clojars`). You can find the provider slug in the `provider_slug` field of each alert. Cannot be combined with the `providers` parameter."),
      providers: z.string().optional().describe("A comma-separated list of provider slugs to filter by. Provider slugs use lowercase with underscores (e.g., `github_secret_scanning`, `clojars`). You can find the provider slug in the `provider_slug` field of each alert. Cannot be combined with the `exclude_providers` parameter."),
      resolution: z.string().optional().describe("A comma-separated list of resolutions. Only secret scanning alerts with one of these resolutions are listed. Valid resolutions are `false_positive`, `wont_fix`, `revoked`, `pattern_edited`, `pattern_deleted` or `used_in_tests`."),
      assignee: z.string().optional().describe("Filters alerts by assignee. Use `*` to get all assigned alerts, `none` to get all unassigned alerts, or a GitHub username to get alerts assigned to a specific user."),
      sort: z.enum(["created", "updated"]).optional().describe("The property to sort the results by. `created` means when the alert was created. `updated` means when the alert was updated or resolved."),
      direction: z.enum(["asc", "desc"]).optional().describe("The direction to sort the results by."),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      before: z.string().optional().describe("A cursor, as given in the [Link header](https://docs.github.com/rest/guides/using-pagination-in-the-rest-api#using-link-headers). If specified, the query only searches for events before this cursor. To receive an initial cursor on your first request, include an empty \"before\" query string."),
      after: z.string().optional().describe("A cursor, as given in the [Link header](https://docs.github.com/rest/guides/using-pagination-in-the-rest-api#using-link-headers). If specified, the query only searches for events after this cursor.  To receive an initial cursor on your first request, include an empty \"after\" query string."),
      validity: z.string().optional().describe("A comma-separated list of validities that, when present, will return alerts that match the validities in this list. Valid options are `active`, `inactive`, and `unknown`."),
      is_publicly_leaked: z.boolean().optional().describe("A boolean value representing whether or not to filter alerts by the publicly-leaked tag being present."),
      is_multi_repo: z.boolean().optional().describe("A boolean value representing whether or not to filter alerts by the multi-repo tag being present."),
      hide_secret: z.boolean().optional().describe("A boolean value representing whether or not to hide literal secrets in the results.")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/secret-scanning/alerts`, undefined, { state: args.state, secret_type: args.secret_type, exclude_secret_types: args.exclude_secret_types, exclude_providers: args.exclude_providers, providers: args.providers, resolution: args.resolution, assignee: args.assignee, sort: args.sort, direction: args.direction, page: args.page, per_page: args.per_page, before: args.before, after: args.after, validity: args.validity, is_publicly_leaked: args.is_publicly_leaked, is_multi_repo: args.is_multi_repo, hide_secret: args.hide_secret });
    },
  },
  {
    name: "github_secret_scanning_get_alert",
    description: "Get a secret scanning alert",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      alert_number: z.string().describe("alert_number"),
      hide_secret: z.boolean().optional().describe("A boolean value representing whether or not to hide literal secrets in the results.")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/secret-scanning/alerts/${args.alert_number}`, undefined, { hide_secret: args.hide_secret });
    },
  },
  {
    name: "github_secret_scanning_update_alert",
    description: "Update a secret scanning alert",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      alert_number: z.string().describe("alert_number"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("PATCH", `/repos/${args.owner}/${args.repo}/secret-scanning/alerts/${args.alert_number}`, args.body, undefined);
    },
  },
  {
    name: "github_secret_scanning_list_locations_for_alert",
    description: "List locations for a secret scanning alert",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      alert_number: z.string().describe("alert_number"),
      page: z.number().optional().describe("The page number of the results to fetch. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\"")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/secret-scanning/alerts/${args.alert_number}/locations`, undefined, { page: args.page, per_page: args.per_page });
    },
  },
  {
    name: "github_secret_scanning_create_push_protection_bypass",
    description: "Create a push protection bypass",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/repos/${args.owner}/${args.repo}/secret-scanning/push-protection-bypasses`, args.body, undefined);
    },
  },
  {
    name: "github_secret_scanning_get_scan_history",
    description: "Get secret scanning scan history for a repository",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/secret-scanning/scan-history`, undefined, undefined);
    },
  },
];
