// AUTO-GENERATED by scripts/generate.ts — DO NOT EDIT
import { z } from "zod";
import { githubRequest } from "../client.js";

export const securityAdvisoriesTools = [
  {
    name: "github_security_advisories_list_global_advisories",
    description: "List global security advisories",
    inputSchema: z.object({
      ghsa_id: z.string().optional().describe("If specified, only advisories with this GHSA (GitHub Security Advisory) identifier will be returned."),
      type: z.enum(["reviewed", "malware", "unreviewed"]).optional().describe("If specified, only advisories of this type will be returned. By default, a request with no other parameters defined will only return reviewed advisories that are not malware."),
      cve_id: z.string().optional().describe("If specified, only advisories with this CVE (Common Vulnerabilities and Exposures) identifier will be returned."),
      ecosystem: z.unknown().optional().describe("If specified, only advisories for these ecosystems will be returned."),
      severity: z.enum(["unknown", "low", "medium", "high", "critical"]).optional().describe("If specified, only advisories with these severities will be returned."),
      cwes: z.unknown().optional().describe("If specified, only advisories with these Common Weakness Enumerations (CWEs) will be returned.  Example: `cwes=79,284,22` or `cwes[]=79&cwes[]=284&cwes[]=22`"),
      is_withdrawn: z.boolean().optional().describe("Whether to only return advisories that have been withdrawn."),
      affects: z.unknown().optional().describe("If specified, only return advisories that affect any of `package` or `package@version`. A maximum of 1000 packages can be specified. If the query parameter causes the URL to exceed the maximum URL length supported by your client, you must specify fewer packages.  Example: `affects=package1,package2@1.0.0,package3@2.0.0` or `affects[]=package1&affects[]=package2@1.0.0`"),
      published: z.string().optional().describe("If specified, only return advisories that were published on a date or date range.  For more information on the syntax of the date range, see \"[Understanding the search syntax](https://docs.github.com/search-github/getting-started-with-searching-on-github/understanding-the-search-syntax#query-for-dates).\""),
      updated: z.string().optional().describe("If specified, only return advisories that were updated on a date or date range.  For more information on the syntax of the date range, see \"[Understanding the search syntax](https://docs.github.com/search-github/getting-started-with-searching-on-github/understanding-the-search-syntax#query-for-dates).\""),
      modified: z.string().optional().describe("If specified, only show advisories that were updated or published on a date or date range.  For more information on the syntax of the date range, see \"[Understanding the search syntax](https://docs.github.com/search-github/getting-started-with-searching-on-github/understanding-the-search-syntax#query-for-dates).\""),
      epss_percentage: z.string().optional().describe("If specified, only return advisories that have an EPSS percentage score that matches the provided value. The EPSS percentage represents the likelihood of a CVE being exploited."),
      epss_percentile: z.string().optional().describe("If specified, only return advisories that have an EPSS percentile score that matches the provided value. The EPSS percentile represents the relative rank of the CVE's likelihood of being exploited compared to other CVEs."),
      before: z.string().optional().describe("A cursor, as given in the [Link header](https://docs.github.com/rest/guides/using-pagination-in-the-rest-api#using-link-headers). If specified, the query only searches for results before this cursor. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      after: z.string().optional().describe("A cursor, as given in the [Link header](https://docs.github.com/rest/guides/using-pagination-in-the-rest-api#using-link-headers). If specified, the query only searches for results after this cursor. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      direction: z.enum(["asc", "desc"]).optional().describe("The direction to sort the results by."),
      per_page: z.number().optional().describe("The number of results per page (max 100). For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      sort: z.enum(["updated", "published", "epss_percentage", "epss_percentile"]).optional().describe("The property to sort the results by.")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/advisories`, undefined, { ghsa_id: args.ghsa_id, type: args.type, cve_id: args.cve_id, ecosystem: args.ecosystem, severity: args.severity, cwes: args.cwes, is_withdrawn: args.is_withdrawn, affects: args.affects, published: args.published, updated: args.updated, modified: args.modified, epss_percentage: args.epss_percentage, epss_percentile: args.epss_percentile, before: args.before, after: args.after, direction: args.direction, per_page: args.per_page, sort: args.sort });
    },
  },
  {
    name: "github_security_advisories_get_global_advisory",
    description: "Get a global security advisory",
    inputSchema: z.object({
      ghsa_id: z.string().describe("ghsa_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/advisories/${args.ghsa_id}`, undefined, undefined);
    },
  },
  {
    name: "github_security_advisories_list_org_repository_advisories",
    description: "List repository security advisories for an organization",
    inputSchema: z.object({
      org: z.string().describe("org"),
      direction: z.enum(["asc", "desc"]).optional().describe("The direction to sort the results by."),
      sort: z.enum(["created", "updated", "published"]).optional().describe("The property to sort the results by."),
      before: z.string().optional().describe("A cursor, as given in the [Link header](https://docs.github.com/rest/guides/using-pagination-in-the-rest-api#using-link-headers). If specified, the query only searches for results before this cursor. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      after: z.string().optional().describe("A cursor, as given in the [Link header](https://docs.github.com/rest/guides/using-pagination-in-the-rest-api#using-link-headers). If specified, the query only searches for results after this cursor. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      per_page: z.number().optional().describe("The number of advisories to return per page. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      state: z.enum(["triage", "draft", "published", "closed"]).optional().describe("Filter by the state of the repository advisories. Only advisories of this state will be returned.")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/orgs/${args.org}/security-advisories`, undefined, { direction: args.direction, sort: args.sort, before: args.before, after: args.after, per_page: args.per_page, state: args.state });
    },
  },
  {
    name: "github_security_advisories_list_repository_advisories",
    description: "List repository security advisories",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      direction: z.enum(["asc", "desc"]).optional().describe("The direction to sort the results by."),
      sort: z.enum(["created", "updated", "published"]).optional().describe("The property to sort the results by."),
      before: z.string().optional().describe("A cursor, as given in the [Link header](https://docs.github.com/rest/guides/using-pagination-in-the-rest-api#using-link-headers). If specified, the query only searches for results before this cursor. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      after: z.string().optional().describe("A cursor, as given in the [Link header](https://docs.github.com/rest/guides/using-pagination-in-the-rest-api#using-link-headers). If specified, the query only searches for results after this cursor. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      per_page: z.number().optional().describe("The number of advisories to return per page. For more information, see \"[Using pagination in the REST API](https://docs.github.com/rest/using-the-rest-api/using-pagination-in-the-rest-api).\""),
      state: z.enum(["triage", "draft", "published", "closed"]).optional().describe("Filter by state of the repository advisories. Only advisories of this state will be returned.")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/security-advisories`, undefined, { direction: args.direction, sort: args.sort, before: args.before, after: args.after, per_page: args.per_page, state: args.state });
    },
  },
  {
    name: "github_security_advisories_create_repository_advisory",
    description: "Create a repository security advisory",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/repos/${args.owner}/${args.repo}/security-advisories`, args.body, undefined);
    },
  },
  {
    name: "github_security_advisories_create_private_vulnerability_report",
    description: "Privately report a security vulnerability",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/repos/${args.owner}/${args.repo}/security-advisories/reports`, args.body, undefined);
    },
  },
  {
    name: "github_security_advisories_get_repository_advisory",
    description: "Get a repository security advisory",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      ghsa_id: z.string().describe("ghsa_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("GET", `/repos/${args.owner}/${args.repo}/security-advisories/${args.ghsa_id}`, undefined, undefined);
    },
  },
  {
    name: "github_security_advisories_update_repository_advisory",
    description: "Update a repository security advisory",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      ghsa_id: z.string().describe("ghsa_id"),
      body: z.record(z.string(), z.unknown()).optional().describe("Request body (JSON object)")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("PATCH", `/repos/${args.owner}/${args.repo}/security-advisories/${args.ghsa_id}`, args.body, undefined);
    },
  },
  {
    name: "github_security_advisories_create_repository_advisory_cve_request",
    description: "Request a CVE for a repository security advisory",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      ghsa_id: z.string().describe("ghsa_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/repos/${args.owner}/${args.repo}/security-advisories/${args.ghsa_id}/cve`, undefined, undefined);
    },
  },
  {
    name: "github_security_advisories_create_fork",
    description: "Create a temporary private fork",
    inputSchema: z.object({
      owner: z.string().describe("owner"),
      repo: z.string().describe("repo"),
      ghsa_id: z.string().describe("ghsa_id")
    }),
    handler: async (args: Record<string, any>) => {
      return githubRequest("POST", `/repos/${args.owner}/${args.repo}/security-advisories/${args.ghsa_id}/forks`, undefined, undefined);
    },
  },
];
